// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/BooleanNodes.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class BooleanNodes
{
internal abstract partial class Xor : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual bool Eval(bool self, bool other) {
return (self ^ other);
}
}

internal abstract partial class Implies : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual bool Eval(bool self, bool other) {
return (!self || other);
}
}
}
