// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/DurationNodesFactory.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class DurationNodesFactory
{
internal sealed partial class ValuePropertyNodeGen : global::DripSharp.Brine.Stdlib.@Base.DurationNodes.ValueProperty
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal ValuePropertyNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
if (((state_0 & 1) != 0)) {
if (global::DripSharp.Brine.Util.MathUtils.IsMathematicalInteger(receiverNodeValue__.GetValue())) {
return this.EvalInt(receiverNodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (!(global::DripSharp.Brine.Util.MathUtils.IsMathematicalInteger(receiverNodeValue__.GetValue()))) {
return this.EvalFloat(receiverNodeValue__);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

public override double ExecuteFloat(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if ((((state_0 & 2) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
if (!(global::DripSharp.Brine.Util.MathUtils.IsMathematicalInteger(receiverNodeValue__.GetValue()))) {
return this.EvalFloat(receiverNodeValue__);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectDouble(this.ExecuteAndSpecialize(receiverNodeValue_));
}

public override long ExecuteInt(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
if (global::DripSharp.Brine.Util.MathUtils.IsMathematicalInteger(receiverNodeValue__.GetValue())) {
return this.EvalInt(receiverNodeValue__);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteAndSpecialize(receiverNodeValue_));
}

internal object ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue!);
if (global::DripSharp.Brine.Util.MathUtils.IsMathematicalInteger(receiverNodeValue_.GetValue())) {
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.EvalInt(receiverNodeValue_);
}
if (!(global::DripSharp.Brine.Util.MathUtils.IsMathematicalInteger(receiverNodeValue_.GetValue()))) {
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.EvalFloat(receiverNodeValue_);
}
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.DurationNodes.ValueProperty Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new ValuePropertyNodeGen(receiverNode);
}
}

internal sealed partial class IsoStringNodeGen : global::DripSharp.Brine.Stdlib.@Base.DurationNodes.IsoString
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal IsoStringNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal string ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.DurationNodes.IsoString Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new IsoStringNodeGen(receiverNode);
}
}

internal sealed partial class UnitNodeGen : global::DripSharp.Brine.Stdlib.@Base.DurationNodes.Unit
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal UnitNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal string ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.DurationNodes.Unit Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new UnitNodeGen(receiverNode);
}
}

internal sealed partial class IsPositiveNodeGen : global::DripSharp.Brine.Stdlib.@Base.DurationNodes.IsPositive
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal IsPositiveNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal bool ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.DurationNodes.IsPositive Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new IsPositiveNodeGen(receiverNode);
}
}

internal sealed partial class IsBetweenNodeGen : global::DripSharp.Brine.Stdlib.@Base.DurationNodes.IsBetween
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg2Node_ = default!;

internal int state_0_;

internal IsBetweenNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node, global::DripSharp.Brine.Ast.ExpressionNode arg2Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
this.arg2Node_ = arg2Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetArg2Node() {
return this.arg2Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue, object arg2NodeValue) {
if ((((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) && (arg1NodeValue is global::DripSharp.Brine.Runtime.VmDuration)) && (arg2NodeValue is global::DripSharp.Brine.Runtime.VmDuration))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
object arg2NodeValue_ = this.arg2Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(arg1NodeValue_!);
if ((arg2NodeValue_ is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration arg2NodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(arg2NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__, arg2NodeValue__);
}
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_, arg2NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 2) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteGeneric(frameValue));
}
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
object arg2NodeValue_ = this.arg2Node_.ExecuteGeneric(frameValue);
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(arg1NodeValue_!);
if ((arg2NodeValue_ is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration arg2NodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(arg2NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__, arg2NodeValue__);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_));
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue, object arg2NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue!);
if ((arg1NodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration arg1NodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(arg1NodeValue!);
if ((arg2NodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration arg2NodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(arg2NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_);
}
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue, arg2NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.DurationNodes.IsBetween Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node, global::DripSharp.Brine.Ast.ExpressionNode arg2Node) {
return new IsBetweenNodeGen(receiverNode, arg1Node, arg2Node);
}
}

internal sealed partial class ToUnitNodeGen : global::DripSharp.Brine.Stdlib.@Base.DurationNodes.ToUnit
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal ToUnitNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) && (arg1NodeValue is string))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue_!);
if ((arg1NodeValue_ is string)) {
string arg1NodeValue__ = (string)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmDuration)(receiverNodeValue!);
if ((arg1NodeValue is string)) {
string arg1NodeValue_ = (string)(arg1NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.DurationNodes.ToUnit Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new ToUnitNodeGen(receiverNode, arg1Node);
}
}
}
