// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/Function5Nodes.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class Function5Nodes
{
internal abstract partial class Apply : global::DripSharp.Brine.Stdlib.ExternalMethod5Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction5Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction5NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmFunction self, object arg1, object arg2, object arg3, object arg4, object arg5) {
return this.applyLambdaNode.Execute(self, arg1, arg2, arg3, arg4, arg5);
}
}
}
