// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/Function0Nodes.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class Function0Nodes
{
internal abstract partial class Apply : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction0Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction0NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmFunction self) {
return this.applyLambdaNode.Execute(self);
}
}
}
