// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/ListingNodesFactory.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class ListingNodesFactory
{
internal sealed partial class LengthNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Length
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal LengthNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

public override long ExecuteInt(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal long ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Length Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new LengthNodeGen(receiverNode);
}
}

internal sealed partial class IsEmptyNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsEmpty
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal IsEmptyNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal bool ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsEmpty Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new IsEmptyNodeGen(receiverNode);
}
}

internal sealed partial class IsNotEmptyNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsNotEmpty
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal IsNotEmptyNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal bool ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsNotEmpty Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new IsNotEmptyNodeGen(receiverNode);
}
}

internal sealed partial class LastIndexNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.LastIndex
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal LastIndexNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

public override long ExecuteInt(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal long ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.LastIndex Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new LastIndexNodeGen(receiverNode);
}
}

internal sealed partial class GetOrNullNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.GetOrNull
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal GetOrNullNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg1NodeValue is long))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if ((((state_0 & 2) == 0) && (state_0 != 0))) {
return this.ExecuteGeneric_long0(state_0, frameValue);
} else {
return this.ExecuteGeneric_generic1(state_0, frameValue);
}
}

internal object ExecuteGeneric_long0(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
long arg1NodeValue_;
try {
arg1NodeValue_ = this.arg1Node_.ExecuteInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, ex.GetResult());
}
global::DripSharp.Runtime.JavaCompat.Assert(() => ((state_0 & 1) != 0));
if ((receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue_);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

internal object ExecuteGeneric_generic1(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is long)) {
long arg1NodeValue__ = (long)(arg1NodeValue_);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg1NodeValue is long)) {
long arg1NodeValue_ = (long)(arg1NodeValue);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.GetOrNull Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new GetOrNullNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class GetOrDefaultNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.GetOrDefault
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal GetOrDefaultNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg1NodeValue is long))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if ((((state_0 & 2) == 0) && (state_0 != 0))) {
return this.ExecuteGeneric_long0(state_0, frameValue);
} else {
return this.ExecuteGeneric_generic1(state_0, frameValue);
}
}

internal object ExecuteGeneric_long0(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
long arg1NodeValue_;
try {
arg1NodeValue_ = this.arg1Node_.ExecuteInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, ex.GetResult());
}
global::DripSharp.Runtime.JavaCompat.Assert(() => ((state_0 & 1) != 0));
if ((receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue_);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

internal object ExecuteGeneric_generic1(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is long)) {
long arg1NodeValue__ = (long)(arg1NodeValue_);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg1NodeValue is long)) {
long arg1NodeValue_ = (long)(arg1NodeValue);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.GetOrDefault Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new GetOrDefaultNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class IsDistinctNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsDistinct
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal IsDistinctNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal bool ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsDistinct Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new IsDistinctNodeGen(receiverNode);
}
}

internal sealed partial class IsDistinctByNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsDistinctBy
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal IsDistinctByNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 2) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteGeneric(frameValue));
}
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_));
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue_ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.IsDistinctBy Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new IsDistinctByNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class DistinctNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Distinct
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal DistinctNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal global::DripSharp.Brine.Runtime.VmListing ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Distinct Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new DistinctNodeGen(receiverNode);
}
}

internal sealed partial class FirstNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.First
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal FirstNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.First Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new FirstNodeGen(receiverNode);
}
}

internal sealed partial class FirstOrNullNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.FirstOrNull
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal FirstOrNullNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.FirstOrNull Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new FirstOrNullNodeGen(receiverNode);
}
}

internal sealed partial class LastNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Last
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal LastNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Last Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new LastNodeGen(receiverNode);
}
}

internal sealed partial class LastOrNullNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.LastOrNull
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal LastOrNullNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.LastOrNull Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new LastOrNullNodeGen(receiverNode);
}
}

internal sealed partial class SingleNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Single
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal SingleNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Single Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new SingleNodeGen(receiverNode);
}
}

internal sealed partial class SingleOrNullNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.SingleOrNull
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal SingleOrNullNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.SingleOrNull Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new SingleOrNullNodeGen(receiverNode);
}
}

internal sealed partial class DistinctByNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.DistinctBy
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal DistinctByNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue_ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.DistinctBy Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new DistinctByNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class EveryNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Every
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal EveryNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 2) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteGeneric(frameValue));
}
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_));
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue_ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Every Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new EveryNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class AnyNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Any
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal AnyNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 2) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteGeneric(frameValue));
}
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_));
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg1NodeValue is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg1NodeValue_ = (global::DripSharp.Brine.Runtime.VmFunction)(arg1NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Any Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new AnyNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class ContainsNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Contains
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal ContainsNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if ((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue_);
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 2) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteGeneric(frameValue));
}
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue_);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_));
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue);
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Contains Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new ContainsNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class FoldNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Fold
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg2Node_ = default!;

internal int state_0_;

internal FoldNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node, global::DripSharp.Brine.Ast.ExpressionNode arg2Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
this.arg2Node_ = arg2Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetArg2Node() {
return this.arg2Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue, object arg2NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg2NodeValue is global::DripSharp.Brine.Runtime.VmFunction))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
object arg2NodeValue_ = this.arg2Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg2NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg2NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg2NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue_, arg2NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_, arg2NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue, object arg2NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg2NodeValue is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg2NodeValue_ = (global::DripSharp.Brine.Runtime.VmFunction)(arg2NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue, arg2NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue, arg2NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Fold Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node, global::DripSharp.Brine.Ast.ExpressionNode arg2Node) {
return new FoldNodeGen(receiverNode, arg1Node, arg2Node);
}
}

internal sealed partial class FoldIndexedNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.FoldIndexed
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg2Node_ = default!;

internal int state_0_;

internal FoldIndexedNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node, global::DripSharp.Brine.Ast.ExpressionNode arg2Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
this.arg2Node_ = arg2Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetArg2Node() {
return this.arg2Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue, object arg2NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg2NodeValue is global::DripSharp.Brine.Runtime.VmFunction))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
object arg2NodeValue_ = this.arg2Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg2NodeValue_ is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg2NodeValue__ = (global::DripSharp.Brine.Runtime.VmFunction)(arg2NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue_, arg2NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_, arg2NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_, arg2NodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue, object arg2NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg2NodeValue is global::DripSharp.Brine.Runtime.VmFunction)) {
global::DripSharp.Brine.Runtime.VmFunction arg2NodeValue_ = (global::DripSharp.Brine.Runtime.VmFunction)(arg2NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue, arg2NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue, arg2NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.FoldIndexed Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node, global::DripSharp.Brine.Ast.ExpressionNode arg2Node) {
return new FoldIndexedNodeGen(receiverNode, arg1Node, arg2Node);
}
}

internal sealed partial class JoinNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Join
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal global::DripSharp.Brine.Ast.ExpressionNode arg1Node_ = default!;

internal int state_0_;

internal JoinNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
this.receiverNode_ = receiverNode;
this.arg1Node_ = arg1Node;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node() {
return this.arg1Node_;
}

internal bool FallbackGuard_(int state_0, object receiverNodeValue, object arg1NodeValue) {
if (((!(((state_0 & 1) != 0)) && (receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (arg1NodeValue is string))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
object arg1NodeValue_ = this.arg1Node_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
if ((arg1NodeValue_ is string)) {
string arg1NodeValue__ = (string)(arg1NodeValue_!);
return this.Eval(receiverNodeValue__, arg1NodeValue__);
}
}
if (((state_0 & 2) != 0)) {
if (this.FallbackGuard_(state_0, receiverNodeValue_, arg1NodeValue_)) {
return this.Fallback(receiverNodeValue_, arg1NodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_, arg1NodeValue_);
}

internal object ExecuteAndSpecialize(object receiverNodeValue, object arg1NodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
if ((arg1NodeValue is string)) {
string arg1NodeValue_ = (string)(arg1NodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_, arg1NodeValue_);
}
}
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Fallback(receiverNodeValue, arg1NodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.Join Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node) {
return new JoinNodeGen(receiverNode, arg1Node);
}
}

internal sealed partial class ToListNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.ToList
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal ToListNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal global::DripSharp.Brine.Runtime.VmList ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.ToList Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new ToListNodeGen(receiverNode);
}
}

internal sealed partial class ToSetNodeGen : global::DripSharp.Brine.Stdlib.@Base.ListingNodes.ToSet
{
internal global::DripSharp.Brine.Ast.ExpressionNode receiverNode_ = default!;

internal int state_0_;

internal ToSetNodeGen(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
this.receiverNode_ = receiverNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetReceiverNode() {
return this.receiverNode_;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object receiverNodeValue_ = this.receiverNode_.ExecuteGeneric(frameValue);
if (((state_0 != 0) && (receiverNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue__ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue_!);
return this.Eval(receiverNodeValue__);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(receiverNodeValue_);
}

internal global::DripSharp.Brine.Runtime.VmSet ExecuteAndSpecialize(object receiverNodeValue) {
int state_0 = this.state_0_;
if ((receiverNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing receiverNodeValue_ = (global::DripSharp.Brine.Runtime.VmListing)(receiverNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(receiverNodeValue_);
}
throw new global::DripSharp.Brine.Runtime.Truffle.api.dsl.UnsupportedSpecializationException(this, new global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node[] { this.receiverNode_ }, receiverNodeValue);
}

public static global::DripSharp.Brine.Stdlib.@Base.ListingNodes.ToSet Create(global::DripSharp.Brine.Ast.ExpressionNode receiverNode) {
return new ToSetNodeGen(receiverNode);
}
}
}
