// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/MapNodes.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class MapNodes
{
internal abstract partial class GetOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmMap self, object key) {
return self.GetOrVmNull(key);
}
}

internal abstract partial class Length : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual long Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self.GetLength();
}
}

internal abstract partial class IsEmpty : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self.IsEmpty();
}
}

internal abstract partial class IsNotEmpty : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return !(self.IsEmpty());
}
}

internal abstract partial class Keys : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self.Keys();
}
}

internal abstract partial class Values : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self.Values();
}
}

internal abstract partial class Entries : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self.Entries();
}
}

internal abstract partial class ContainsKey : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmMap self, object key) {
return self.ContainsKey(key);
}
}

internal abstract partial class ContainsValue : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmMap self, object value) {
return self.ContainsValue(value);
}
}

internal abstract partial class Put : global::DripSharp.Brine.Stdlib.ExternalMethod2Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self, object key, object value) {
return self.Put(key, value);
}
}

internal abstract partial class Remove : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self, object key) {
return self.Remove(key);
}
}

internal abstract partial class Filter : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var entry in self) {
var key = global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry);
var value = global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry);
if (this.applyLambdaNode.ExecuteBoolean(function, key, value)) {
builder.Add(key, value);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class Fold : global::DripSharp.Brine.Stdlib.ExternalMethod2Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction3Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction3NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmMap self, object initial, global::DripSharp.Brine.Runtime.VmFunction function) {
var result = new global::DripSharp.Brine.Util.MutableReference<object>(initial);
foreach (var entry in self) {
result.Set(this.applyLambdaNode.Execute(function, result.Get(), global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry)));
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result.Get();
}
}

internal abstract partial class Map : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var entry in self) {
var pair = this.applyLambdaNode.ExecutePair(function, global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry));
builder.Add(pair.GetFirst(), pair.GetSecond());
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class MapKeys : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmFunction function, global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyNode) {
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var entry in self) {
builder.Add(applyNode.Execute(function, global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry)), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry));
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class MapValues : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmFunction function, global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyNode) {
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var entry in self) {
builder.Add(global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), applyNode.Execute(function, global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry)));
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class FlatMap : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var entry in self) {
global::DripSharp.Brine.Runtime.VmMap flatMapResult = this.applyLambdaNode.ExecuteMap(function, global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry));
foreach (global::DripSharp.Runtime.JavaMapEntry<object, object> flatMapEntry in flatMapResult) {
builder.Add(global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(flatMapEntry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(flatMapEntry));
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class Every : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmFunction function) {
foreach (var entry in self) {
if (!(this.applyLambdaNode.ExecuteBoolean(function, global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry)))) {
return false;
}
}
return true;
}
}

internal abstract partial class Any : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmFunction function) {
foreach (var entry in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry))) {
return true;
}
}
return false;
}
}

internal abstract partial class ToMap : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self;
}
}

internal abstract partial class ToDynamic : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmDynamic Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self.ToDynamic();
}
}

internal abstract partial class ToTyped : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmTyped Eval(global::DripSharp.Brine.Runtime.VmMap self, global::DripSharp.Brine.Runtime.VmClass clazz) {
if (!(clazz.IsSubclassOf(global::DripSharp.Brine.Runtime.BaseModule.GetTypedClass()))) {
throw this.ExceptionBuilder().EvalError("notASubclassOfTyped", clazz).Build();
}
global::DripSharp.Brine.Runtime.VmUtils.CheckIsInstantiable(clazz, (global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node?)default!);
var result = new global::DripSharp.Brine.Runtime.VmTyped(global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyMaterializedFrame(), clazz.GetPrototype(), clazz, clazz.GetMapToTypedMembers());
result.SetExtraStorage(self);
return result;
}
}

internal abstract partial class ToMapping : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmMapping Eval(global::DripSharp.Brine.Runtime.VmMap self) {
return self.ToMapping();
}
}
}
