// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/PcfRenderer.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class PcfRenderer : global::DripSharp.Brine.Stdlib.AbstractStringRenderer
{
private readonly global::DripSharp.Brine.ValueFormatter valueFormatter = default!;

private bool isDocument;

private object topLevelValue = default!;

public PcfRenderer(global::System.Text.StringBuilder builder, string indent, global::DripSharp.Brine.Stdlib.PklConverter converter, bool omitNullProperties, bool useCustomStringDelimiters) : base("Pcf", builder, indent, converter, omitNullProperties, false) {

this.valueFormatter = new global::DripSharp.Brine.ValueFormatter(true, useCustomStringDelimiters);
}

public override void VisitString(string value) {
this.IncreaseIndent();
(this.valueFormatter).FormatStringValue(value, (base.currIndent.ToString()).ToString(), base.builder);
this.DecreaseIndent();
}

private void RenderStringElement(string value) {
(this.valueFormatter).FormatStringValue(value, (base.currIndent.ToString()).ToString(), base.builder);
}

public override void VisitTyped(global::DripSharp.Brine.Runtime.VmTyped value) {
if (global::DripSharp.Brine.Runtime.VmUtils.IsPcfRenderDirective(value)) {
this.VisitPcfRenderDirective(value);
} else {
base.VisitTyped(value);
}
}

public override void VisitInt(long value) {
global::DripSharp.Runtime.JavaCompat.StringBuilderAppendInvariant(base.builder, (long)((long)(value)));
}

public override void VisitFloat(double value) {
global::DripSharp.Runtime.JavaCompat.StringBuilderAppendInvariant(base.builder, (double)((double)(value)));
}

public override void VisitBoolean(bool value) {
global::DripSharp.Runtime.JavaCompat.StringBuilderAppendInvariant(base.builder, (bool)(value));
}

public override void VisitDuration(global::DripSharp.Brine.Runtime.VmDuration value) {
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(value));
}

public override void VisitDataSize(global::DripSharp.Brine.Runtime.VmDataSize value) {
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(value));
}

public override void VisitBytes(global::DripSharp.Brine.Runtime.VmBytes value) {
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(value));
}

public override void VisitPair(global::DripSharp.Brine.Runtime.VmPair value) {
base.builder.Append("Pair(");
this.VisitStandaloneValue(value.GetFirst());
base.builder.Append(", ");
this.VisitStandaloneValue(value.GetSecond());
base.builder.Append(')');
}

public override void VisitRegex(global::DripSharp.Brine.Runtime.VmRegex value) {
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(value));
}

public override void VisitIntSeq(global::DripSharp.Brine.Runtime.VmIntSeq value) {
base.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(value));
}

public override void VisitNull(global::DripSharp.Brine.Runtime.VmNull value) {
base.builder.Append("null");
}

protected internal override void VisitRenderDirective(global::DripSharp.Brine.Runtime.VmTyped value) {
base.builder.Append(global::DripSharp.Brine.Runtime.VmUtils.ReadTextProperty(value));
}

private void VisitPcfRenderDirective(global::DripSharp.Brine.Runtime.VmTyped value) {
var before = global::DripSharp.Brine.Runtime.VmUtils.ReadMember(value, global::DripSharp.Brine.Runtime.Identifier.BEFORE);
if ((before is string @string__139_34)) {
base.builder.Append(@string__139_34);
}
this.Visit(global::DripSharp.Brine.Runtime.VmUtils.ReadMember(value, global::DripSharp.Brine.Runtime.Identifier.VALUE));
var after = global::DripSharp.Brine.Runtime.VmUtils.ReadMember(value, global::DripSharp.Brine.Runtime.Identifier.AFTER);
if ((after is string @string__144_33)) {
base.builder.Append(@string__144_33);
}
}

protected internal override void VisitDocument(object value) {
if (!(((value is global::DripSharp.Brine.Runtime.VmTyped) || (value is global::DripSharp.Brine.Runtime.VmDynamic)))) {
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().EvalError("invalidPcfTopLevelValue", global::DripSharp.Brine.Runtime.VmUtils.GetClass(value)).WithProgramValue("Value", value).Build();
}
this.isDocument = true;
this.topLevelValue = value;
this.Visit(value);
if (!((base.builder.Length) == 0)) {
base.builder.Append('\n');
}
}

protected internal override void VisitTopLevelValue(object value) {
this.topLevelValue = value;
this.Visit(value);
}

protected internal override bool CanRenderPropertyOrEntryOf(global::DripSharp.Brine.Runtime.VmDynamic @object) {
return true;
}

protected internal override void StartDynamic(global::DripSharp.Brine.Runtime.VmDynamic value) {
this.StartObject(value);
}

protected internal override void StartTyped(global::DripSharp.Brine.Runtime.VmTyped value) {
this.StartObject(value);
}

protected internal override void StartListing(global::DripSharp.Brine.Runtime.VmListing value) {
this.StartObject(value);
}

protected internal override void StartMapping(global::DripSharp.Brine.Runtime.VmMapping value) {
this.StartObject(value);
}

protected internal override void StartList(global::DripSharp.Brine.Runtime.VmList value) {
base.builder.Append("List(");
}

protected internal override void StartSet(global::DripSharp.Brine.Runtime.VmSet value) {
base.builder.Append("Set(");
}

protected internal override void StartMap(global::DripSharp.Brine.Runtime.VmMap value) {
base.builder.Append("Map(");
}

protected internal override void VisitElement(long index, object value, bool isFirst) {
if ((base.enclosingValue! is global::DripSharp.Brine.Runtime.VmObjectLike)) {
base.builder.Append('\n');
base.builder.Append(base.currIndent.ToString());
if ((value is string @string)) {
this.RenderStringElement(@string);
} else {
this.VisitStandaloneValue(value);
}
} else {
if (!isFirst) {
base.builder.Append(", ");
}
this.VisitStandaloneValue(value);
}
}

private void VisitStandaloneValue(object value) {
if (((value is global::DripSharp.Brine.Runtime.VmObjectLike) && !(this.IsRenderDirective(value)))) {
base.builder.Append("new ");
}
this.Visit(value);
}

protected internal override void VisitEntryKey(object key, bool isFirst) {
if ((base.enclosingValue! is global::DripSharp.Brine.Runtime.VmObjectLike)) {
base.builder.Append('\n');
base.builder.Append(base.currIndent.ToString());
base.builder.Append('[');
this.VisitStandaloneValue(key);
base.builder.Append(']');
} else {
if (!isFirst) {
base.builder.Append(", ");
}
this.VisitStandaloneValue(key);
}
}

protected internal override void VisitEntryValue(object value) {
if ((base.enclosingValue! is global::DripSharp.Brine.Runtime.VmObjectLike)) {
if ((value is global::DripSharp.Brine.Runtime.VmObjectLike)) {
base.builder.Append(' ');
} else {
base.builder.Append(" = ");
}
this.Visit(value);
} else {
base.builder.Append(", ");
this.VisitStandaloneValue(value);
}
}

protected internal override void VisitProperty(global::DripSharp.Brine.Runtime.Identifier name, object value, bool isFirst) {
if (!((base.builder.Length) == 0)) {
base.builder.Append('\n');
base.builder.Append(base.currIndent.ToString());
}
base.builder.Append(global::DripSharp.Brine.Parser.Lexer.MaybeQuoteIdentifier(name.ToString()));
if ((value is global::DripSharp.Brine.Runtime.VmObjectLike)) {
base.builder.Append(' ');
} else {
base.builder.Append(" = ");
}
this.Visit(value);
}

protected internal override void EndDynamic(global::DripSharp.Brine.Runtime.VmDynamic value, bool isEmpty) {
this.EndObject(value, isEmpty);
}

protected internal override void EndTyped(global::DripSharp.Brine.Runtime.VmTyped value, bool isEmpty) {
this.EndObject(value, isEmpty);
}

protected internal override void EndListing(global::DripSharp.Brine.Runtime.VmListing value, bool isEmpty) {
this.EndObject(value, isEmpty);
}

protected internal override void EndMapping(global::DripSharp.Brine.Runtime.VmMapping value, bool isEmpty) {
this.EndObject(value, isEmpty);
}

protected internal override void EndList(global::DripSharp.Brine.Runtime.VmList value) {
base.builder.Append(')');
}

protected internal override void EndSet(global::DripSharp.Brine.Runtime.VmSet value) {
base.builder.Append(')');
}

protected internal override void EndMap(global::DripSharp.Brine.Runtime.VmMap value) {
base.builder.Append(')');
}

private void StartObject(global::DripSharp.Brine.Runtime.VmObjectLike value) {
if ((this.isDocument && (value == this.topLevelValue))) {
return;
}
this.IncreaseIndent();
base.builder.Append('{');
}

private void EndObject(global::DripSharp.Brine.Runtime.VmObjectLike value, bool isEmpty) {
if ((this.isDocument && (value == this.topLevelValue))) {
return;
}
this.DecreaseIndent();
if (!isEmpty) {
base.builder.Append('\n');
base.builder.Append(base.currIndent.ToString());
}
base.builder.Append('}');
}
}
