// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/base/SetNodes.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.@Base;

internal sealed partial class SetNodes
{
internal abstract partial class Length : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual long Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetLength();
}
}

internal abstract partial class IsNotEmpty : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return !(self.IsEmpty());
}
}

internal abstract partial class IsEmpty : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.IsEmpty();
}
}

internal abstract partial class First : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetFirst();
}
}

internal abstract partial class FirstOrNull : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetFirstOrNull();
}
}

internal abstract partial class Rest : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetRest();
}
}

internal abstract partial class RestOrNull : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetRestOrNull();
}
}

internal abstract partial class Last : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetLast();
}
}

internal abstract partial class LastOrNull : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetLastOrNull();
}
}

internal abstract partial class Single : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetSingle();
}
}

internal abstract partial class SingleOrNull : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.GetSingleOrNull();
}
}

internal abstract partial class StartsWith : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmCollection other) {
return self.StartsWith(other);
}
}

internal abstract partial class EndsWith : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmCollection other) {
return self.EndsWith(other);
}
}

internal abstract partial class Split : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmPair Eval(global::DripSharp.Brine.Runtime.VmSet self, long index) {
if (((index < 0) || (index > self.GetLength()))) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().EvalError("elementIndexOutOfRange", index, 0, self.GetLength()).WithProgramValue("Collection", self).Build();
}
return self.Split(index);
}
}

internal abstract partial class SplitOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, long index) {
return self.SplitOrNull(index);
}
}

internal abstract partial class Partition : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmPair Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder1 = self.CreateBuilder();
var builder2 = self.CreateBuilder();
foreach (var elem in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
builder1.Add(elem);
} else {
builder2.Add(elem);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return new global::DripSharp.Brine.Runtime.VmPair(builder1.Build(), builder2.Build());
}
}

internal abstract partial class Contains : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmSet self, object element) {
return self.Contains(element);
}
}

internal abstract partial class Find : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
foreach (var elem in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
return elem;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().EvalError("cannotFindMatchingCollectionElement").WithProgramValue("Collection", self).Build();
}
}

internal abstract partial class FindOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
foreach (var elem in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
return elem;
}
}
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
}

internal abstract partial class FindLast : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var iterator = self.ReverseIterator();
while (iterator.HasNext()) {
var elem = iterator.Next()!;
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
return elem;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().EvalError("cannotFindMatchingCollectionElement").WithProgramValue("Collection", self).Build();
}
}

internal abstract partial class FindLastOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var iterator = self.ReverseIterator();
while (iterator.HasNext()) {
var elem = iterator.Next()!;
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
return elem;
}
}
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
}

internal abstract partial class Every : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
foreach (var elem in self) {
if (!(this.applyLambdaNode.ExecuteBoolean(function, elem))) {
return false;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return true;
}
}

internal abstract partial class Any : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
foreach (var elem in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
return true;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return false;
}
}

internal abstract partial class Filter : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
foreach (var elem in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
builder.Add(elem);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class FilterNonNull : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self) {
var builder = self.CreateBuilder();
foreach (var elem in self) {
if ((elem is global::DripSharp.Brine.Runtime.VmNull)) {
continue;
}
builder.Add(elem);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class FilterIndexed : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
long index = 0;
foreach (var elem in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, index++, elem)) {
builder.Add(elem);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class FilterIsInstance : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.@Internal.IsInstanceOfNode isInstanceOfNode = global::DripSharp.Brine.Ast.@Internal.IsInstanceOfNodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmClass clazz) {
var builder = self.CreateBuilder();
foreach (var elem in self) {
if (this.isInstanceOfNode.ExecuteBoolean(elem, clazz)) {
builder.Add(elem);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class Map : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
foreach (var elem in self) {
builder.Add(this.applyLambdaNode.Execute(function, elem));
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class MapIndexed : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
long index = 0;
foreach (var elem in self) {
builder.Add(this.applyLambdaNode.Execute(function, index++, elem));
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class MapNonNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
foreach (var elem in self) {
var newValue = this.applyLambdaNode.Execute(function, elem);
if ((newValue is global::DripSharp.Brine.Runtime.VmNull)) {
continue;
}
builder.Add(newValue);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class MapNonNullIndexed : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
long index = 0;
foreach (var elem in self) {
var newValue = this.applyLambdaNode.Execute(function, index++, elem);
if ((newValue is global::DripSharp.Brine.Runtime.VmNull)) {
continue;
}
builder.Add(newValue);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class FlatMap : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
foreach (var elem in self) {
builder.AddAll(this.applyLambdaNode.ExecuteCollection(function, elem));
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class FlatMapIndexed : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
long index = 0;
foreach (var elem in self) {
builder.AddAll(this.applyLambdaNode.ExecuteCollection(function, index++, elem));
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class Flatten : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return (global::DripSharp.Brine.Runtime.VmSet)(self.Flatten()!);
}
}

internal abstract partial class Take : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, long n) {
return self.Take(n);
}
}

internal abstract partial class TakeWhile : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = self.CreateBuilder();
foreach (var elem in self) {
if (!(this.applyLambdaNode.ExecuteBoolean(function, elem))) {
return builder.Build();
}
builder.Add(elem);
}
return self;
}
}

internal abstract partial class TakeLast : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, long n) {
return self.TakeLast(n);
}
}

internal abstract partial class TakeLastWhile : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var idx = self.GetLength();
var iter = self.ReverseIterator();
while (iter.HasNext()) {
if (!(this.applyLambdaNode.ExecuteBoolean(function, iter.Next()!))) {
break;
}
idx -= 1;
}
return self.Drop((long)(idx));
}
}

internal abstract partial class Drop : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, long n) {
return self.Drop(n);
}
}

internal abstract partial class DropWhile : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var idx = 0;
foreach (var elem in self) {
if (!(this.applyLambdaNode.ExecuteBoolean(function, elem))) {
break;
}
idx += 1;
}
return self.Drop((long)(idx));
}
}

internal abstract partial class DropLast : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, long n) {
return self.DropLast(n);
}
}

internal abstract partial class DropLastWhile : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var idx = self.GetLength();
var iter = self.ReverseIterator();
while (iter.HasNext()) {
if (!(this.applyLambdaNode.ExecuteBoolean(function, iter.Next()!))) {
break;
}
idx -= 1;
}
return self.Take((long)(idx));
}
}

internal abstract partial class Fold : global::DripSharp.Brine.Stdlib.ExternalMethod2Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, object initial, global::DripSharp.Brine.Runtime.VmFunction function) {
var iter = self.Iterator();
var result = initial;
while (iter.HasNext()) {
var elem = iter.Next()!;
result = this.applyLambdaNode.Execute(function, result, elem);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class FoldBack : global::DripSharp.Brine.Stdlib.ExternalMethod2Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, object initial, global::DripSharp.Brine.Runtime.VmFunction function) {
var iter = self.ReverseIterator();
var result = initial;
while (iter.HasNext()) {
var elem = iter.Next()!;
result = this.applyLambdaNode.Execute(function, elem, result);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class FoldIndexed : global::DripSharp.Brine.Stdlib.ExternalMethod2Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction3Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction3NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, object initial, global::DripSharp.Brine.Runtime.VmFunction function) {
var iter = self.Iterator();
var result = initial;
long index = 0;
while (iter.HasNext()) {
var elem = iter.Next()!;
result = this.applyLambdaNode.Execute(function, index++, result, elem);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class Reduce : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
self.CheckNonEmpty();
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
result = this.applyLambdaNode.Execute(function, result, elem);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class ReduceOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
if (self.IsEmpty()) {
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
result = this.applyLambdaNode.Execute(function, result, elem);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class GroupBy : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (object elem in self) {
var key = this.applyLambdaNode.Execute(function, elem);
var value = builder.Get(key)!;
var newValue = ((value! == default!) ? global::DripSharp.Brine.Runtime.VmSet.Of(elem) : ((global::DripSharp.Brine.Runtime.VmSet)(value!)).Add(elem));
builder.Add(key, newValue);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class Min : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
internal global::DripSharp.Brine.Ast.Expression.Binary.LessThanNode lessThanNode = global::DripSharp.Brine.Ast.Expression.Binary.LessThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self) {
self.CheckNonEmpty();
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
if (this.lessThanNode.ExecuteWith(frame, elem, result)) {
result = elem;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MinOrNull : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
internal global::DripSharp.Brine.Ast.Expression.Binary.LessThanNode lessThanNode = global::DripSharp.Brine.Ast.Expression.Binary.LessThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self) {
if (self.IsEmpty()) {
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
if (this.lessThanNode.ExecuteWith(frame, elem, result)) {
result = elem;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MinBy : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

internal global::DripSharp.Brine.Ast.Expression.Binary.LessThanNode lessThanNode = global::DripSharp.Brine.Ast.Expression.Binary.LessThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
self.CheckNonEmpty();
var iterator = self.Iterator();
var result = iterator.Next()!;
var resultValue = this.applyLambdaNode.Execute(function, result);
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var elemValue = this.applyLambdaNode.Execute(function, elem);
if (this.lessThanNode.ExecuteWith(frame, elemValue, resultValue)) {
result = elem;
resultValue = elemValue;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MinByOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

internal global::DripSharp.Brine.Ast.Expression.Binary.LessThanNode lessThanNode = global::DripSharp.Brine.Ast.Expression.Binary.LessThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
if (self.IsEmpty()) {
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
var iterator = self.Iterator();
var result = iterator.Next()!;
var resultValue = this.applyLambdaNode.Execute(function, result);
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var elemValue = this.applyLambdaNode.Execute(function, elem);
if (this.lessThanNode.ExecuteWith(frame, elemValue, resultValue)) {
result = elem;
resultValue = elemValue;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MinWith : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
self.CheckNonEmpty();
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var cmpResult = this.applyLambdaNode.Execute(function, elem, result);
if ((cmpResult is bool b)) {
if (b) {
result = elem;
}
} else {
if ((cmpResult is long l)) {
if ((l < 0)) {
result = elem;
}
} else {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().TypeMismatch(cmpResult, global::DripSharp.Brine.Runtime.BaseModule.GetBooleanClass(), global::DripSharp.Brine.Runtime.BaseModule.GetIntClass()).Build();
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MinWithOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
if (self.IsEmpty()) {
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var cmpResult = this.applyLambdaNode.Execute(function, elem, result);
if ((cmpResult is bool b)) {
if (b) {
result = elem;
}
} else {
if ((cmpResult is long l)) {
if ((l < 0)) {
result = elem;
}
} else {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().TypeMismatch(cmpResult, global::DripSharp.Brine.Runtime.BaseModule.GetBooleanClass(), global::DripSharp.Brine.Runtime.BaseModule.GetIntClass()).Build();
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class Max : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
internal global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNode greaterThanNode = global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self) {
self.CheckNonEmpty();
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
if (this.greaterThanNode.ExecuteWith(frame, elem, result)) {
result = elem;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MaxOrNull : global::DripSharp.Brine.Stdlib.ExternalPropertyNode
{
internal global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNode greaterThanNode = global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self) {
if (self.IsEmpty()) {
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
if (this.greaterThanNode.ExecuteWith(frame, elem, result)) {
result = elem;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MaxBy : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

internal global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNode greaterThanNode = global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
self.CheckNonEmpty();
var iterator = self.Iterator();
var result = iterator.Next()!;
var resultValue = this.applyLambdaNode.Execute(function, result);
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var elemValue = this.applyLambdaNode.Execute(function, elem);
if (this.greaterThanNode.ExecuteWith(frame, elemValue, resultValue)) {
result = elem;
resultValue = elemValue;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MaxByOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

internal global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNode greaterThanNode = global::DripSharp.Brine.Ast.Expression.Binary.GreaterThanNodeGen.Create(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection(), (global::DripSharp.Brine.Ast.ExpressionNode)default!, (global::DripSharp.Brine.Ast.ExpressionNode)default!);

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
if (self.IsEmpty()) {
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
var iterator = self.Iterator();
var result = iterator.Next()!;
var resultValue = this.applyLambdaNode.Execute(function, result);
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var elemValue = this.applyLambdaNode.Execute(function, elem);
if (this.greaterThanNode.ExecuteWith(frame, elemValue, resultValue)) {
result = elem;
resultValue = elemValue;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MaxWith : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
self.CheckNonEmpty();
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var cmpResult = this.applyLambdaNode.Execute(function, elem, result);
if ((cmpResult is bool b)) {
if (b) {
result = elem;
}
} else {
if ((cmpResult is long l)) {
if ((l < 0)) {
result = elem;
}
} else {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().TypeMismatch(cmpResult, global::DripSharp.Brine.Runtime.BaseModule.GetBooleanClass(), global::DripSharp.Brine.Runtime.BaseModule.GetIntClass()).Build();
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class MaxWithOrNull : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction2NodeGen.Create();

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
if (self.IsEmpty()) {
return global::DripSharp.Brine.Runtime.VmNull.WithoutDefault();
}
var iterator = self.Iterator();
var result = iterator.Next()!;
while (iterator.HasNext()) {
var elem = iterator.Next()!;
var cmpResult = this.applyLambdaNode.Execute(function, result, elem);
if ((cmpResult is bool b)) {
if (b) {
result = elem;
}
} else {
if ((cmpResult is long l)) {
if ((l < 0)) {
result = elem;
}
} else {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().TypeMismatch(cmpResult, global::DripSharp.Brine.Runtime.BaseModule.GetBooleanClass(), global::DripSharp.Brine.Runtime.BaseModule.GetIntClass()).Build();
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return result;
}
}

internal abstract partial class Sort : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
internal global::DripSharp.Brine.Stdlib.@Base.CollectionNodes.CompareNode compareNode = new global::DripSharp.Brine.Stdlib.@Base.CollectionNodes.CompareNode();

protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self) {
return global::DripSharp.Brine.Runtime.VmList.Create(global::DripSharp.Brine.Stdlib.@Base.MergeSort.Sort(frame, self.ToArray(), this.compareNode, (global::DripSharp.Brine.Runtime.VmFunction?)default!));
}
}

internal abstract partial class SortBy : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Stdlib.@Base.CollectionNodes.CompareByNode compareByNode = new global::DripSharp.Brine.Stdlib.@Base.CollectionNodes.CompareByNode();

protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction selector) {
return global::DripSharp.Brine.Runtime.VmList.Create(global::DripSharp.Brine.Stdlib.@Base.MergeSort.Sort(frame, self.ToArray(), this.compareByNode, selector));
}
}

internal abstract partial class SortWith : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Stdlib.@Base.CollectionNodes.CompareWithNode compareWithNode = new global::DripSharp.Brine.Stdlib.@Base.CollectionNodes.CompareWithNode();

protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
return global::DripSharp.Brine.Runtime.VmList.Create(global::DripSharp.Brine.Stdlib.@Base.MergeSort.Sort(frame, self.ToArray(), this.compareWithNode, function));
}
}

internal abstract partial class Add : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, object element) {
return self.Add(element);
}
}

internal abstract partial class Repeat : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.VmSet self, long n) {
return self.Repeat(n);
}
}

internal abstract partial class Count : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyLambdaNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual long Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction function) {
var count = 0;
foreach (var elem in self) {
if (this.applyLambdaNode.ExecuteBoolean(function, elem)) {
count += 1;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return count;
}
}

internal abstract partial class Reverse : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.Reverse();
}
}

internal abstract partial class Join : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual string Eval(global::DripSharp.Brine.Runtime.VmSet self, string separator) {
return self.Join(separator);
}
}

internal abstract partial class Zip : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmCollection Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmCollection coll) {
return self.Zip(coll);
}
}

internal abstract partial class ToList : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmList Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.ToList();
}
}

internal abstract partial class ToSet : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self;
}
}

internal abstract partial class ToMap : global::DripSharp.Brine.Stdlib.ExternalMethod2Node
{
internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyKeyExtractorNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

internal global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyValueExtractorNode = global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();

protected internal virtual global::DripSharp.Brine.Runtime.VmMap Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmFunction keyExtractor, global::DripSharp.Brine.Runtime.VmFunction valueExtractor) {
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var elem in self) {
var key = this.applyKeyExtractorNode.Execute(keyExtractor, elem);
var value = this.applyValueExtractorNode.Execute(valueExtractor, elem);
builder.Add(key, value);
}
global::DripSharp.Brine.Runtime.Truffle.api.nodes.LoopNode.ReportLoopCount(this, self.GetLength());
return builder.Build();
}
}

internal abstract partial class ToListing : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmListing Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.ToListing();
}
}

internal abstract partial class ToDynamic : global::DripSharp.Brine.Stdlib.ExternalMethod0Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmDynamic Eval(global::DripSharp.Brine.Runtime.VmSet self) {
return self.ToDynamic();
}
}

internal abstract partial class Intersect : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmSet other) {
global::DripSharp.Brine.Runtime.VmSet smaller;
global::DripSharp.Brine.Runtime.VmSet larger;
if ((self.GetLength() <= other.GetLength())) {
smaller = self;
larger = other;
} else {
smaller = other;
larger = self;
}
var builder = global::DripSharp.Brine.Runtime.VmSet.EMPTY.CreateBuilder();
foreach (var elem in smaller) {
if (larger.Contains(elem)) {
builder.Add(elem);
}
}
return builder.Build();
}
}

internal abstract partial class Difference : global::DripSharp.Brine.Stdlib.ExternalMethod1Node
{
protected internal virtual global::DripSharp.Brine.Runtime.VmSet Eval(global::DripSharp.Brine.Runtime.VmSet self, global::DripSharp.Brine.Runtime.VmSet other) {
var builder = global::DripSharp.Brine.Runtime.VmSet.EMPTY.CreateBuilder();
foreach (var elem in self) {
if (!(other.Contains(elem))) {
builder.Add(elem);
}
}
return builder.Build();
}
}
}
