// <auto-generated />
// Mechanically translated from: org/pkl/parser/util/ErrorMessages.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Parser.Util;

public sealed partial class ErrorMessages
{
public static string Create(string messageName, params object[] args) {
var locale = global::System.Globalization.CultureInfo.CurrentCulture;
var errorMessage = global::DripSharp.Runtime.JavaCompat.GetResourceString(global::DripSharp.Runtime.JavaCompat.GetResourceBundle("org.pkl.parser.errorMessages", locale), messageName);
if ((args.Length == 0)) {
return errorMessage;
}
var formatter = new global::DripSharp.Runtime.JavaMessageFormat(errorMessage, locale);
return global::DripSharp.Runtime.JavaCompat.Format(formatter, args);
}
}
