// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/literal/CheckIsAnnotationClassNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Literal;

internal sealed partial class CheckIsAnnotationClassNode : global::DripSharp.Brine.Ast.ExpressionNode
{
private global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode unresolvedTypeNode = default!;

private global::DripSharp.Brine.Ast.Type.TypeNode? typeNode = default!;

public CheckIsAnnotationClassNode(global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode unresolvedTypeNode) : base(unresolvedTypeNode.GetSourceSection()) {

this.unresolvedTypeNode = unresolvedTypeNode;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
if ((this.typeNode! == default!)) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
this.typeNode = this.Insert(this.unresolvedTypeNode.Execute(frame));
this.unresolvedTypeNode = default!;
}
var clazz = this.typeNode!.GetVmClass()!;
if (((clazz! != default!) && clazz!.IsSubclassOf(global::DripSharp.Brine.Runtime.BaseModule.GetAnnotationClass()))) {
return this.typeNode!.GetVmClass()!;
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().EvalError("expectedAnnotationClass").Build();
}
}
