// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/literal/EmptyObjectLiteralNodeGen.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Literal;

internal sealed partial class EmptyObjectLiteralNodeGen : global::DripSharp.Brine.Ast.Expression.Literal.EmptyObjectLiteralNode
{
private global::DripSharp.Brine.Ast.ExpressionNode parentNode_ = default!;

private int state_0_;

private EmptyObjectLiteralNodeGen(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Ast.ExpressionNode parentNode) : base(sourceSection) {

this.parentNode_ = parentNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetParentNode() {
return this.parentNode_;
}

private bool FallbackGuard_(int state_0, object parentNodeValue) {
if ((!(((state_0 & 1) != 0)) && (parentNodeValue is global::DripSharp.Brine.Runtime.VmClass))) {
return false;
}
if ((!(((state_0 & 2) != 0)) && (parentNodeValue is global::DripSharp.Brine.Runtime.VmObjectLike))) {
return false;
}
if ((!(((state_0 & 4) != 0)) && (parentNodeValue is global::DripSharp.Brine.Runtime.VmNull))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
object parentNodeValue_ = this.parentNode_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (parentNodeValue_ is global::DripSharp.Brine.Runtime.VmClass))) {
global::DripSharp.Brine.Runtime.VmClass parentNodeValue____74_25 = (global::DripSharp.Brine.Runtime.VmClass)(parentNodeValue_!);
return this.Eval(parentNodeValue____74_25);
}
if ((((state_0 & 2) != 0) && (parentNodeValue_ is global::DripSharp.Brine.Runtime.VmObjectLike))) {
global::DripSharp.Brine.Runtime.VmObjectLike parentNodeValue____78_30 = (global::DripSharp.Brine.Runtime.VmObjectLike)(parentNodeValue_!);
return this.Eval(parentNodeValue____78_30);
}
if ((((state_0 & 4) != 0) && (parentNodeValue_ is global::DripSharp.Brine.Runtime.VmNull))) {
global::DripSharp.Brine.Runtime.VmNull parentNodeValue____82_24 = (global::DripSharp.Brine.Runtime.VmNull)(parentNodeValue_!);
return this.Eval(parentNodeValue____82_24);
}
if (((state_0 & 8) != 0)) {
if (this.FallbackGuard_(state_0, parentNodeValue_)) {
this.Fallback(parentNodeValue_);
return default!;
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(parentNodeValue_);
}

private object ExecuteAndSpecialize(object parentNodeValue) {
int state_0 = this.state_0_;
if ((parentNodeValue is global::DripSharp.Brine.Runtime.VmClass)) {
global::DripSharp.Brine.Runtime.VmClass parentNodeValue___99_21 = (global::DripSharp.Brine.Runtime.VmClass)(parentNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(parentNodeValue___99_21);
}
if ((parentNodeValue is global::DripSharp.Brine.Runtime.VmObjectLike)) {
global::DripSharp.Brine.Runtime.VmObjectLike parentNodeValue___105_26 = (global::DripSharp.Brine.Runtime.VmObjectLike)(parentNodeValue!);
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Eval(parentNodeValue___105_26);
}
if ((parentNodeValue is global::DripSharp.Brine.Runtime.VmNull)) {
global::DripSharp.Brine.Runtime.VmNull parentNodeValue___111_20 = (global::DripSharp.Brine.Runtime.VmNull)(parentNodeValue!);
state_0 = (state_0 | 4);
this.state_0_ = state_0;
return this.Eval(parentNodeValue___111_20);
}
state_0 = (state_0 | 8);
this.state_0_ = state_0;
this.Fallback(parentNodeValue);
return default!;
}

public static global::DripSharp.Brine.Ast.Expression.Literal.EmptyObjectLiteralNode Create(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Ast.ExpressionNode parentNode) {
return new EmptyObjectLiteralNodeGen(sourceSection, parentNode);
}
}
