// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/generator/GeneratorElementNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Generator;

internal abstract partial class GeneratorElementNode : global::DripSharp.Brine.Ast.Expression.Generator.GeneratorMemberNode
{
private readonly global::DripSharp.Brine.Ast.Member.ObjectMember element = default!;

protected internal GeneratorElementNode(global::DripSharp.Brine.Ast.Member.ObjectMember element, bool isFrameStored) : base(element.GetSourceSection(), isFrameStored) {

this.element = element;
}

protected internal virtual void EvalDynamic(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmDynamic parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data) {
data.AddElement(frame, this.element, this);
}

protected internal virtual void EvalListing(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmListing parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data) {
data.AddElement(frame, this.element, this);
}

protected internal virtual void EvalDynamicClass(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmClass parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data) {
data.AddElement(frame, this.element, this);
}

protected internal virtual void EvalListingClass(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmClass parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data) {
data.AddElement(frame, this.element, this);
}

internal virtual void Fallback(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
var parentClass = ((parent is global::DripSharp.Brine.Runtime.VmClass) ? (global::DripSharp.Brine.Runtime.VmClass)((global::DripSharp.Brine.Runtime.VmClass)(parent!)) : global::DripSharp.Brine.Runtime.VmUtils.GetClass(parent));
throw this.ExceptionBuilder().EvalError("objectCannotHaveElement", parentClass).Build();
}
}
