// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/generator/GeneratorForNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Generator;

internal abstract partial class GeneratorForNode : global::DripSharp.Brine.Ast.Expression.Generator.GeneratorMemberNode
{
private readonly global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameDescriptor generatorDescriptor = default!;

private global::DripSharp.Brine.Ast.ExpressionNode iterableNode = default!;

private global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode? unresolvedKeyTypeNode = default!;

private global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode? unresolvedValueTypeNode = default!;

private readonly global::DripSharp.Brine.Ast.Expression.Generator.GeneratorMemberNode[] childNodes = default!;

private global::DripSharp.Brine.Ast.Type.TypeNode? keyTypeNode = default!;

private global::DripSharp.Brine.Ast.Type.TypeNode? valueTypeNode = default!;

private readonly int keySlot;

private readonly int valueSlot;

private readonly int[] slotsToCopy = default!;

public GeneratorForNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameDescriptor generatorDescriptor, global::DripSharp.Brine.Ast.ExpressionNode iterableNode, global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode? unresolvedKeyTypeNode, global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode? unresolvedValueTypeNode, global::DripSharp.Brine.Ast.Expression.Generator.GeneratorMemberNode[] childNodes, global::DripSharp.Brine.Ast.Type.TypeNode? keyTypeNode, global::DripSharp.Brine.Ast.Type.TypeNode? valueTypeNode, int keySlot, int valueSlot, int[] outerForGeneratorSlots, int[] parameterSlots) : base(sourceSection, false) {

this.generatorDescriptor = generatorDescriptor;
this.iterableNode = iterableNode;
this.unresolvedKeyTypeNode = unresolvedKeyTypeNode!;
this.unresolvedValueTypeNode = unresolvedValueTypeNode!;
this.childNodes = childNodes;
this.keyTypeNode = keyTypeNode!;
this.valueTypeNode = valueTypeNode!;
this.keySlot = keySlot;
this.valueSlot = valueSlot;
this.slotsToCopy = global::DripSharp.Brine.Util.ArrayUtils.Concat(parameterSlots, outerForGeneratorSlots);
}

protected internal abstract void ExecuteWithIterable(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, object iterable);

public sealed override void Execute(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data) {
this.Initialize(frame);
this.ExecuteWithIterable(frame, parent, data, this.iterableNode.ExecuteGeneric(frame));
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmListing iterable) {
this.DoEvalObject(frame, iterable, parent, data);
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmMapping iterable) {
this.DoEvalObject(frame, iterable, parent, data);
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmDynamic iterable) {
this.DoEvalObject(frame, iterable, parent, data);
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmList iterable) {
long idx = 0;
foreach (var element in iterable) {
this.ExecuteIteration(frame, parent, data, idx++, element);
}
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmMap iterable) {
foreach (var entry in iterable) {
this.ExecuteIteration(frame, parent, data, global::DripSharp.Brine.Runtime.VmUtils.GetKey<object, object>(entry), global::DripSharp.Brine.Runtime.VmUtils.GetValue<object, object>(entry));
}
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmSet iterable) {
long idx = 0;
foreach (var element in iterable) {
this.ExecuteIteration(frame, parent, data, idx++, element);
}
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmIntSeq iterable) {
var length = iterable.GetLength();
for (long key = 0, value = iterable.start; (key < length); key++, value += iterable.step) {
this.ExecuteIteration(frame, parent, data, key, value);
}
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, global::DripSharp.Brine.Runtime.VmBytes iterable) {
long idx = 0;
foreach (var byt in iterable.GetBytes()) {
this.ExecuteIteration(frame, parent, data, idx++, (long)(byt));
}
}

protected internal virtual void Fallback(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, object iterable) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().EvalError("cannotIterateOverThisValue", global::DripSharp.Brine.Runtime.VmUtils.GetClass(iterable)).WithLocation(this.iterableNode).WithProgramValue("Value", iterable).Build();
}

private void DoEvalObject(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmObject iterable, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data) {
iterable.ForceAndIterateMemberValues((key, member, value) => {
var convertedKey = (member.IsProp() ? (object)(global::DripSharp.Runtime.JavaCompat.StringValueOf(key)) : key);
this.ExecuteIteration(frame, parent, data, convertedKey, value);
return true;
});
}

private void ExecuteIteration(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, object parent, global::DripSharp.Brine.Ast.Expression.Generator.ObjectData data, object key, object value) {
var newFrame = global::DripSharp.Brine.Runtime.Truffle.api.Truffle.GetRuntime().CreateVirtualFrame(frame.GetArguments(), this.generatorDescriptor);
global::DripSharp.Brine.Runtime.VmUtils.CopyLocals(frame, newFrame, this.slotsToCopy);
if ((this.keyTypeNode! != default!)) {
this.keyTypeNode!.ExecuteAndSet(newFrame, key);
}
if ((this.valueTypeNode! != default!)) {
this.valueTypeNode!.ExecuteAndSet(newFrame, value);
}
for (int i = 0; (i < this.childNodes.Length); i++) {
this.childNodes[i].Execute(newFrame, parent, data);
}
}

private void Initialize(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
if ((this.unresolvedKeyTypeNode! != default!)) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
this.keyTypeNode = this.Insert(this.unresolvedKeyTypeNode!.Execute(frame)).InitWriteSlotNode(this.keySlot);
this.generatorDescriptor.SetSlotKind(this.keySlot, this.keyTypeNode!.GetFrameSlotKind());
this.unresolvedKeyTypeNode = default!;
}
if ((this.unresolvedValueTypeNode! != default!)) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
this.valueTypeNode = this.Insert(this.unresolvedValueTypeNode!.Execute(frame)).InitWriteSlotNode(this.valueSlot);
this.generatorDescriptor.SetSlotKind(this.valueSlot, this.valueTypeNode!.GetFrameSlotKind());
this.unresolvedValueTypeNode = default!;
}
}
}
