// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/generator/RestoreForBindingsNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Generator;

internal sealed partial class RestoreForBindingsNode : global::DripSharp.Brine.Ast.ExpressionNode
{
private global::DripSharp.Brine.Ast.ExpressionNode child = default!;

private readonly int[] slotsToCopy = default!;

public RestoreForBindingsNode(global::DripSharp.Brine.Ast.ExpressionNode child, int[] parameterSlots, int[] forGeneratorSlots) : base(child.GetSourceSection()) {

this.child = child;
this.slotsToCopy = global::DripSharp.Brine.Util.ArrayUtils.Concat(parameterSlots, forGeneratorSlots);
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
var generatorFrame = global::DripSharp.Brine.Ast.Expression.Generator.ObjectData.GetGeneratorFrame(frame);
global::DripSharp.Brine.Runtime.VmUtils.CopyLocals(generatorFrame, frame, this.slotsToCopy);
return this.child.ExecuteGeneric(frame);
}
}
