// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/type/IdentityMixinNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Type;

internal sealed partial class IdentityMixinNode : global::DripSharp.Brine.Ast.PklRootNode
{
private readonly global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection = default!;

private readonly string qualifiedName = default!;

private global::DripSharp.Brine.Ast.Type.TypeNode? argumentTypeNode = default!;

public IdentityMixinNode(global::DripSharp.Brine.Runtime.VmLanguage language, global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameDescriptor descriptor, global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, string qualifiedName, global::DripSharp.Brine.Ast.Type.TypeNode? argumentTypeNode) : base(language, descriptor) {

this.qualifiedName = qualifiedName;
this.sourceSection = sourceSection;
this.argumentTypeNode = argumentTypeNode!;
}

public override global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection GetSourceSection() {
return this.sourceSection;
}

public override string GetName() {
return this.qualifiedName;
}

protected internal override object ExecuteImpl(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
var arguments = frame.GetArguments();
if ((arguments.Length != 3)) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().EvalError("wrongFunctionArgumentCount", 1, (arguments.Length - 2)).WithSourceSection(this.sourceSection).Build();
}
var argument = arguments[2];
if ((this.argumentTypeNode! != default!)) {
return this.argumentTypeNode!.Execute(frame, argument);
}
return argument;
}
}
