// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/type/TypeConstraintNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Type;

internal abstract partial class TypeConstraintNode : global::DripSharp.Brine.Ast.PklNode
{
private int customThisSlot = -1;

protected internal TypeConstraintNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection) : base(sourceSection) {

}

public abstract void Execute(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame);

protected internal abstract global::DripSharp.Brine.Ast.ExpressionNode GetBodyNode();

public virtual string Export() {
return this.GetSourceSection().GetCharacters();
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, bool result) {
this.InitConstraintSlot(frame);
if (!result) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
var vmContext = global::DripSharp.Brine.Runtime.VmContext.Get(this);
var localContext = global::DripSharp.Brine.Runtime.VmLanguage.Get(this).localContext.Get();
var usePowerAssertions = (vmContext.GetPowerAssertionsEnabled() && (!(localContext.IsInTypeTest()) || localContext.HasActiveTracker()));
if (usePowerAssertions) {
using (var valueTracker = vmContext.GetValueTrackerFactory().Create()) {
this.GetBodyNode().ExecuteGeneric(frame);
throw new global::DripSharp.Brine.Ast.Type.VmTypeMismatchException.Constraint(base.sourceSection, frame.GetAuxiliarySlot(this.customThisSlot), base.sourceSection, valueTracker.Values());
}
} else {
throw new global::DripSharp.Brine.Ast.Type.VmTypeMismatchException.Constraint(base.sourceSection, frame.GetAuxiliarySlot(this.customThisSlot), base.sourceSection, (global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node, global::System.Collections.Generic.IList<object>>)default!);
}
}
}

protected internal virtual void Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Runtime.VmFunction function, global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node applyNode) {
this.InitConstraintSlot(frame);
var value = frame.GetAuxiliarySlot(this.customThisSlot);
var result = applyNode.ExecuteBoolean(function, value);
if (!result) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
var vmContext = global::DripSharp.Brine.Runtime.VmContext.Get(this);
var localContext = global::DripSharp.Brine.Runtime.VmLanguage.Get(this).localContext.Get();
var usePowerAssertions = (vmContext.GetPowerAssertionsEnabled() && (!(localContext.IsInTypeTest()) || localContext.HasActiveTracker()));
if (usePowerAssertions) {
using (var valueTracker = vmContext.GetValueTrackerFactory().Create()) {
applyNode.ExecuteBoolean(function, value);
throw new global::DripSharp.Brine.Ast.Type.VmTypeMismatchException.Constraint(base.sourceSection, value, function.GetRootNode().GetSourceSection(), valueTracker.Values());
}
} else {
throw new global::DripSharp.Brine.Ast.Type.VmTypeMismatchException.Constraint(base.sourceSection, value, function.GetRootNode().GetSourceSection(), (global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node, global::System.Collections.Generic.IList<object>>)default!);
}
}
}

protected internal virtual void Fallback(object @object) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().TypeMismatch(@object, global::DripSharp.Brine.Runtime.BaseModule.GetBooleanClass(), global::DripSharp.Brine.Runtime.BaseModule.GetFunctionClass()).Build();
}

protected internal static global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node CreateApplyNode() {
return global::DripSharp.Brine.Ast.Lambda.ApplyVmFunction1Node.Create();
}

private void InitConstraintSlot(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
if ((this.customThisSlot == -1)) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
this.customThisSlot = global::DripSharp.Brine.Runtime.VmUtils.FindCustomThisSlot(frame);
}
}
}
