// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/primary/GetMemberKeyNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Primary;

internal sealed partial class GetMemberKeyNode : global::DripSharp.Brine.Ast.ExpressionNode
{
public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
return global::DripSharp.Brine.Runtime.VmUtils.GetMemberKey(frame);
}
}
