// <auto-generated />
// Mechanically translated from: org/pkl/core/http/HttpClientException.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Http;

public sealed partial class HttpClientException : global::System.Exception
{
public HttpClientException(string message) : base(message) {

}

public HttpClientException(global::System.Exception cause) : base(global::DripSharp.Runtime.JavaCompat.ExceptionMessage(cause), cause) {

}

public HttpClientException(string message, global::System.Exception cause) : base(message, cause) {

}
}
