// <auto-generated />
// Mechanically translated from: org/pkl/core/http/HttpClient.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Http;

public partial interface HttpClient : global::System.IDisposable
{
public void Dispose() => this.Close();

public partial interface Builder
{
public Builder SetUserAgent(string userAgent);

public Builder SetConnectTimeout(global::System.TimeSpan timeout);

public Builder SetRequestTimeout(global::System.TimeSpan timeout);

public Builder AddCertificates(string path);

public Builder AddCertificates(byte[] certificateBytes);

internal Builder SetTestPort(int port);

/* Java ProxySelector configuration (global::DripSharp.Brine.Runtime.JavaProxySelector proxySelector) remains an internal HTTP builder adapter. */

public Builder SetProxy(global::System.Uri? proxyAddress, global::System.Collections.Generic.IReadOnlyList<string> noProxy);

public Builder SetRewrites(global::System.Collections.Generic.IReadOnlyDictionary<global::System.Uri, global::System.Uri> rewrites);

public Builder AddRewrite(global::System.Uri sourcePrefix, global::System.Uri targetPrefix);

public Builder SetHeaders(global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Collections.Generic.IReadOnlyList<string>>> headerRules);

public Builder AddHeaders(string globPattern, global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Collections.Generic.IReadOnlyList<string>> headers);

public HttpClient Build();

public HttpClient BuildLazily();
}

public static Builder CreateBuilder() {
return new global::DripSharp.Brine.Http.HttpClientBuilder();
}

public static HttpClient DummyClient() {
return new global::DripSharp.Brine.Http.DummyHttpClient();
}

/* Java HttpClient.send<T>(global::DripSharp.Brine.Runtime.JavaHttpRequest request, global::DripSharp.Brine.Runtime.JavaHttpBodyHandler<T> responseBodyHandler, HttpRequestChecker httpRequestChecker) is supplied by the internal compatibility adapter. */

public void Close();

public delegate void HttpRequestChecker(global::System.Uri uri);
}
