// <auto-generated />
// Mechanically translated from: org/pkl/core/http/RequestRewritingClient.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Http;

internal sealed partial class RequestRewritingClient : global::DripSharp.Brine.Http.HttpClient
{
public void Dispose() => this.Close();

public global::DripSharp.Brine.Http.HttpClient.Builder CreateBuilder() {
return new global::DripSharp.Brine.Http.HttpClientBuilder();
}

public global::DripSharp.Brine.Http.HttpClient DummyClient() {
return new global::DripSharp.Brine.Http.DummyHttpClient();
}

internal readonly string userAgent = default!;

internal readonly global::System.TimeSpan requestTimeout = default!;

internal readonly int testPort;

internal readonly global::DripSharp.Brine.Http.HttpClient @delegate = default!;

internal readonly global::System.Collections.Generic.IDictionary<global::System.Uri, global::System.Uri> rewritesMap = default!;

internal readonly global::System.Collections.Generic.IDictionary<global::System.Text.RegularExpressions.Regex, global::System.Collections.Generic.IDictionary<string, global::System.Collections.Generic.IList<string>>> headers = default!;

private readonly global::System.Collections.Generic.IList<global::DripSharp.Runtime.JavaMapEntry<global::System.Uri, global::System.Uri>> rewrites = default!;

private readonly global::DripSharp.Brine.Runtime.JavaAtomicBoolean closed = new global::DripSharp.Brine.Runtime.JavaAtomicBoolean();

private static readonly int MAX_HTTP_REDIRECTS;

internal RequestRewritingClient(string userAgent, global::System.TimeSpan requestTimeout, int testPort, global::DripSharp.Brine.Http.HttpClient @delegate, global::System.Collections.Generic.IDictionary<global::System.Uri, global::System.Uri> rewrites, global::System.Collections.Generic.IDictionary<global::System.Text.RegularExpressions.Regex, global::System.Collections.Generic.IDictionary<string, global::System.Collections.Generic.IList<string>>> headers) {
this.userAgent = userAgent;
this.requestTimeout = requestTimeout;
this.testPort = testPort;
this.@delegate = @delegate;
this.rewritesMap = rewrites;
this.rewrites = global::DripSharp.Runtime.JavaCompat.ToListValues(global::DripSharp.Runtime.JavaCompat.StreamSorted(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(global::DripSharp.Runtime.JavaCompat.MapEntrySet(rewrites)), (it) => global::DripSharp.Runtime.JavaCompat.MapEntry(this.NormalizeRewrite(it.Key), this.NormalizeRewrite(it.Value))), global::DripSharp.Runtime.JavaCompat.ToComparison(global::DripSharp.Runtime.JavaCompat.ComparingInt<global::DripSharp.Runtime.JavaMapEntry<global::System.Uri, global::System.Uri>>((it) => -(global::DripSharp.Runtime.JavaCompat.UriToString(it.Key).Length)))));
this.headers = headers;
}

private global::DripSharp.Brine.Runtime.JavaHttpResponse<T> DoSend<T>(global::DripSharp.Brine.Runtime.JavaHttpRequest request, global::DripSharp.Brine.Runtime.JavaHttpBodyHandler<T> responseBodyHandler, global::DripSharp.Brine.Http.HttpClient.HttpRequestChecker httpRequestChecker) {
var redirectCount = 0;
var currentRequestUri = this.RewriteUri(request.Uri());
var currentRequest = this.RewriteRequest(request, currentRequestUri);
while (true) {
httpRequestChecker(currentRequestUri);
var response = global::DripSharp.Brine.Http.HttpClientCompatibility.Send<T>(this.@delegate, currentRequest, responseBodyHandler, httpRequestChecker);
if (!(global::DripSharp.Brine.Util.HttpUtils.IsRedirectStatusCode(response.StatusCode()))) {
return response;
}
if ((redirectCount >= RequestRewritingClient.MAX_HTTP_REDIRECTS)) {
throw new global::DripSharp.Brine.Http.HttpClientException(global::DripSharp.Brine.Util.ErrorMessages.Create("httpTooManyRedirects", RequestRewritingClient.MAX_HTTP_REDIRECTS));
}
var location = response.Headers().FirstValue("Location");
if (location.IsEmpty()) {
throw new global::DripSharp.Brine.Http.HttpClientException(global::DripSharp.Brine.Util.ErrorMessages.Create("httpRedirectNoLocation", currentRequestUri));
}
global::System.Uri redirectUri;
try {
redirectUri = global::DripSharp.Runtime.JavaCompat.ResolveUri(currentRequestUri, location.Get());
} catch (global::System.ArgumentException) {
throw new global::DripSharp.Brine.Http.HttpClientException(global::DripSharp.Brine.Util.ErrorMessages.Create("httpRedirectInvalidUri", currentRequestUri, location.Get()));
}
if ((global::DripSharp.Runtime.JavaCompat.EqualsIgnoreCase(global::DripSharp.Runtime.JavaCompat.UriScheme(currentRequestUri)!, "https") && global::DripSharp.Runtime.JavaCompat.EqualsIgnoreCase(global::DripSharp.Runtime.JavaCompat.UriScheme(redirectUri)!, "http"))) {
throw new global::DripSharp.Brine.Http.HttpClientException(global::DripSharp.Brine.Util.ErrorMessages.Create("httpRedirectCannotDowngrade", currentRequestUri, redirectUri));
}
currentRequestUri = this.RewriteUri(redirectUri);
currentRequest = this.RewriteRequest(request, currentRequestUri);
redirectCount++;
}
}

public global::DripSharp.Brine.Runtime.JavaHttpResponse<T> SendCompatibility<T>(global::DripSharp.Brine.Runtime.JavaHttpRequest request, global::DripSharp.Brine.Runtime.JavaHttpBodyHandler<T> responseBodyHandler, global::DripSharp.Brine.Http.HttpClient.HttpRequestChecker httpRequestChecker) {
this.CheckNotClosed(request);
try {
return this.DoSend(request, responseBodyHandler, httpRequestChecker);
} catch (global::System.IO.IOException e) {
var rewrittenUri = this.RewriteUri(request.Uri());
if ((rewrittenUri != request.Uri())) {
throw new global::System.IO.IOException(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.ExceptionMessage(e), global::DripSharp.Runtime.JavaCompat.Formatted(" (request was rewritten: %s -> %s)", request.Uri(), rewrittenUri)), e);
}
global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(e);
throw new global::System.InvalidOperationException("unreachable");
}
}

public void Close() {
if (!(this.closed).GetAndSet(true)) {
this.@delegate.Close();
}
}

private global::DripSharp.Brine.Runtime.JavaHttpRequest RewriteRequest(global::DripSharp.Brine.Runtime.JavaHttpRequest original, global::System.Uri newUri) {
global::DripSharp.Brine.Runtime.JavaHttpRequest.Builder builder = global::DripSharp.Brine.Runtime.JavaHttpRequest.NewBuilder();
builder.Uri(newUri).ExpectContinue(original.ExpectContinue()).Timeout(original.Timeout().OrElse(this.requestTimeout)).Version(original.Version().OrElse(global::DripSharp.Brine.Runtime.JavaHttpVersion.HTTP_2));
global::DripSharp.Runtime.JavaCompat.ForEach(original.Headers().Map(), (name, values) => global::DripSharp.Runtime.JavaCompat.ForEach(values, (value) => builder.Header(name, value)));
var isUserAgentSet = false;
foreach (var header in this.GetHeaders(newUri)) {
var headerName = header.GetFirst();
isUserAgentSet = (isUserAgentSet || global::DripSharp.Runtime.JavaCompat.EqualsIgnoreCase(headerName, "user-agent"));
builder.Header(header.GetFirst(), header.GetSecond());
}
if (!isUserAgentSet) {
builder.SetHeader("User-Agent", this.userAgent);
}
var method = original.Method();
original.BodyPublisher().IfPresentOrElse((publisher) => builder.Method(method, publisher), () => {
switch (method) {
case var __case_206_22_0 when global::System.Object.Equals(__case_206_22_0, "GET"):
builder.GET();
break;
case var __case_207_22_0 when global::System.Object.Equals(__case_207_22_0, "DELETE"):
builder.DELETE();
break;
default:
builder.Method(method, global::DripSharp.Brine.Runtime.JavaHttpBodyPublishers.NoBody());
break;
}
});
return builder.Build();
}

private static bool NotEqualCaseInsensitive(string? a, string? b) {
if (((a! == default!) || (b! == default!))) {
return !(global::DripSharp.Runtime.JavaCompat.Equals(a!, b!));
}
return !(global::DripSharp.Runtime.JavaCompat.EqualsIgnoreCase(a!, b!));
}

public static bool MatchesRewriteRule(global::System.Uri uri, global::System.Uri rule) {
if (RequestRewritingClient.NotEqualCaseInsensitive(global::DripSharp.Runtime.JavaCompat.UriScheme(uri)!, global::DripSharp.Runtime.JavaCompat.UriScheme(rule)!)) {
return false;
}
if (!(global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.Runtime.JavaCompat.UriUserInfo(uri)!, global::DripSharp.Runtime.JavaCompat.UriUserInfo(rule)!))) {
return false;
}
if (RequestRewritingClient.NotEqualCaseInsensitive(global::DripSharp.Runtime.JavaCompat.UriHost(uri)!, global::DripSharp.Runtime.JavaCompat.UriHost(rule)!)) {
return false;
}
if (!(global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.Runtime.JavaCompat.UriPath(uri)!, global::DripSharp.Runtime.JavaCompat.UriPath(rule)!))) {
if (((((global::DripSharp.Runtime.JavaCompat.UriPath(uri)! != default!) && (global::DripSharp.Runtime.JavaCompat.UriPath(rule)! != default!)) && (global::DripSharp.Runtime.JavaCompat.UriQuery(rule)! == default!)) && (global::DripSharp.Runtime.JavaCompat.UriFragment(rule)! == default!))) {
return global::DripSharp.Runtime.JavaCompat.StringStartsWith(global::DripSharp.Runtime.JavaCompat.UriPath(uri)!, global::DripSharp.Runtime.JavaCompat.UriPath(rule)!);
}
return false;
}
if (!(global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.Runtime.JavaCompat.UriQuery(uri)!, global::DripSharp.Runtime.JavaCompat.UriQuery(rule)!))) {
if ((((global::DripSharp.Runtime.JavaCompat.UriQuery(uri)! != default!) && (global::DripSharp.Runtime.JavaCompat.UriQuery(rule)! != default!)) && (global::DripSharp.Runtime.JavaCompat.UriFragment(rule)! == default!))) {
return global::DripSharp.Runtime.JavaCompat.StringStartsWith(global::DripSharp.Runtime.JavaCompat.UriQuery(uri)!, global::DripSharp.Runtime.JavaCompat.UriQuery(rule)!);
}
return false;
}
if (((global::DripSharp.Runtime.JavaCompat.UriFragment(uri)! != default!) && (global::DripSharp.Runtime.JavaCompat.UriFragment(rule)! != default!))) {
return global::DripSharp.Runtime.JavaCompat.StringStartsWith(global::DripSharp.Runtime.JavaCompat.UriFragment(uri)!, global::DripSharp.Runtime.JavaCompat.UriFragment(rule)!);
}
return global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.Runtime.JavaCompat.UriFragment(uri)!, global::DripSharp.Runtime.JavaCompat.UriFragment(rule)!);
}

private global::DripSharp.Runtime.JavaMapEntry<global::System.Uri, global::System.Uri>? FindRewrite(global::System.Uri uri) {
foreach (var entry in this.rewrites) {
if (RequestRewritingClient.MatchesRewriteRule(uri, entry.Key)) {
return entry;
}
}
return default!;
}

private global::System.Uri NormalizeRewrite(global::System.Uri uri) {
try {
return global::DripSharp.Runtime.JavaCompat.NewUri(global::DripSharp.Runtime.JavaCompat.UriScheme(uri)!.ToLowerInvariant(), global::DripSharp.Runtime.JavaCompat.UriUserInfo(uri)!, global::DripSharp.Runtime.JavaCompat.UriHost(uri)!.ToLowerInvariant(), global::DripSharp.Runtime.JavaCompat.UriPort(uri), global::DripSharp.Runtime.JavaCompat.UriPath(uri)!, global::DripSharp.Runtime.JavaCompat.UriQuery(uri)!, global::DripSharp.Runtime.JavaCompat.UriFragment(uri)!);
} catch (global::System.UriFormatException) {
throw global::DripSharp.Brine.PklBugException.UnreachableCode();
}
}

private global::System.Uri RewriteUri(global::System.Uri uri) {
var rewrite = this.FindRewrite(uri)!;
var ret = uri;
if ((rewrite! != default!)) {
var normalized = this.NormalizeRewrite(uri);
var fromUri = rewrite!.Key;
var toUri = rewrite!.Value;
var relativePath = global::DripSharp.Runtime.JavaCompat.RelativizeUri(fromUri, normalized);
ret = global::DripSharp.Runtime.JavaCompat.ResolveUri(toUri, relativePath);
}
if (((this.testPort != -1) && (global::DripSharp.Runtime.JavaCompat.UriPort(ret) == 0))) {
ret = global::DripSharp.Brine.Util.HttpUtils.SetPort(ret, this.testPort);
}
return ret;
}

private bool Matches(global::System.Text.RegularExpressions.Regex pattern, global::System.Uri uri) {
if ((pattern == global::DripSharp.Brine.Util.IoUtils.doubleStarGlob)) {
return true;
}
return global::DripSharp.Runtime.JavaCompat.RegexMatcher(pattern, global::DripSharp.Runtime.JavaCompat.UriToString(uri)).Matches();
}

private global::System.Collections.Generic.IList<global::DripSharp.Brine.Util.Pair<string, string>> GetHeaders(global::System.Uri uri) {
var result = new global::System.Collections.Generic.List<global::DripSharp.Brine.Util.Pair<string, string>>();
foreach (var rule in global::DripSharp.Runtime.JavaCompat.MapEntrySet(this.headers)) {
var pattern = rule.Key;
if (!(this.Matches(pattern, uri))) {
continue;
}
foreach (var header in global::DripSharp.Runtime.JavaCompat.MapEntrySet(rule.Value)) {
foreach (var value in header.Value) {
global::DripSharp.Runtime.JavaCompat.Add(result, global::DripSharp.Brine.Util.Pair<object, object>.Of<string, string>(header.Key, value));
}
}
}
return result;
}

private void CheckNotClosed(global::DripSharp.Brine.Runtime.JavaHttpRequest request) {
if ((this.closed).Get()) {
throw new global::System.InvalidOperationException(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Cannot send request ", request), " because this client has already been closed."));
}
}
}
