// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/test/report/JUnitReporter.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.Test.Report;

internal sealed partial class JUnitReporter : global::DripSharp.Brine.Stdlib.Test.Report.TestReporter
{
public string Report(global::DripSharp.Brine.TestResults results) {
try {
var builder = new global::System.Text.StringBuilder();
var writer = new global::DripSharp.Brine.Util.StringBuilderWriter(builder);
this.Report(results, writer);
return builder.ToString();
} catch (global::System.IO.IOException e) {
throw new global::DripSharp.Brine.PklBugException("Unexpected IO exception.", e);
}
}

public void ReportToPath(global::DripSharp.Brine.TestResults results, string path) {
using (var writer = global::DripSharp.Runtime.JavaCompat.NewFileWriter(new global::System.IO.FileInfo(path), global::DripSharp.Runtime.JavaStandardCharsets.UTF8)) {
this.Report(results, writer);
}
}

public void SummarizeToPath(global::System.Collections.Generic.IList<global::DripSharp.Brine.TestResults> allTestResults, string path) {
using (var writer = global::DripSharp.Runtime.JavaCompat.NewFileWriter(new global::System.IO.FileInfo(path), global::DripSharp.Runtime.JavaStandardCharsets.UTF8)) {
this.Summarize(allTestResults, writer);
}
}

private readonly string aggregateSuiteName = default!;

public JUnitReporter(string aggregateSuiteName) {
this.aggregateSuiteName = aggregateSuiteName;
}

public JUnitReporter() : this("") {

}

public void Report(global::DripSharp.Brine.TestResults results, global::System.IO.TextWriter writer) {
global::DripSharp.Runtime.JavaCompat.WriterAppend(writer, JUnitReporter.RenderXML("    ", "1.0", this.BuildSuite(results)));
}

public void Summarize(global::System.Collections.Generic.IList<global::DripSharp.Brine.TestResults> allTestResults, global::System.IO.TextWriter writer) {
var totalTests = global::DripSharp.Runtime.JavaCompat.Sum(global::DripSharp.Runtime.JavaCompat.MapToLong(allTestResults, (value0) => value0.TotalTests()));
var totalFailures = global::DripSharp.Runtime.JavaCompat.Sum(global::DripSharp.Runtime.JavaCompat.MapToLong(allTestResults, (value0) => value0.TotalFailures()));
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.aggregateSuiteName != default!));
var attrs = this.BuildAttributes("name", this.aggregateSuiteName, "tests", totalTests, "failures", totalFailures);
var suite = this.BuildXmlElement("testsuites", attrs, global::DripSharp.Runtime.JavaCompat.ToArray(global::DripSharp.Runtime.JavaCompat.Map(allTestResults, this.BuildSuite)));
global::DripSharp.Runtime.JavaCompat.WriterAppend(writer, JUnitReporter.RenderXML("    ", "1.0", suite));
}

private global::DripSharp.Brine.Runtime.VmDynamic BuildSuite(global::DripSharp.Brine.TestResults results) {
if (!global::System.Object.ReferenceEquals(results.ErrorValue!, default!)) {
var testCase = this.RootTestCase(results, results.ErrorValue!);
var attrs__82_11 = this.BuildAttributes("name", results.ModuleName, "tests", 1, "failures", 1);
return this.BuildXmlElement("testsuite", attrs__82_11, testCase);
}
var testCases = this.TestCases(results.ModuleName, results.Facts);
global::DripSharp.Runtime.JavaCompat.AddAll(testCases, this.TestCases(results.ModuleName, results.Examples));
if (!(global::System.String.IsNullOrWhiteSpace(results.Logs))) {
var err = this.BuildXmlElement("system-err", global::DripSharp.Brine.Runtime.VmMapping.Empty(), (members) => members.Put("body", this.SyntheticElement(this.MakeCdata(results.Logs))));
global::DripSharp.Runtime.JavaCompat.Add(testCases, err);
}
var attrs__102_9 = this.BuildAttributes("name", results.ModuleName, "tests", (long)(results.TotalTests()), "failures", (long)(results.TotalFailures()));
return this.BuildXmlElement("testsuite", attrs__102_9, global::DripSharp.Runtime.JavaCompat.CollectionToArray(testCases, new global::DripSharp.Brine.Runtime.VmDynamic[0]));
}

private global::DripSharp.Brine.Runtime.VmDynamic RootTestCase(global::DripSharp.Brine.TestResults results, global::DripSharp.Brine.TestResults.Error error) {
var testCaseAttrs = this.BuildAttributes("classname", results.ModuleName, "name", results.ModuleName);
var err = this.Error(error);
return this.BuildXmlElement("testcase", testCaseAttrs, global::DripSharp.Runtime.JavaCompat.CollectionToArray(err, new global::DripSharp.Brine.Runtime.VmDynamic[0]));
}

private global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic> TestCases(string moduleName, global::DripSharp.Brine.TestResults.TestSectionResults testSectionResults) {
var elements = new global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic>(testSectionResults.TotalTests());
foreach (var res in global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::DripSharp.Brine.TestResults.TestResult>>(testSectionResults.Results)) {
var attrs = this.BuildAttributes("classname", global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(moduleName, "."), testSectionResults.Name), "name", res.Name);
var failures = this.Failures(res);
global::DripSharp.Runtime.JavaCompat.AddAll(failures, this.Errors(res));
var element = this.BuildXmlElement("testcase", attrs, global::DripSharp.Runtime.JavaCompat.CollectionToArray(failures, new global::DripSharp.Brine.Runtime.VmDynamic[0]));
global::DripSharp.Runtime.JavaCompat.Add(elements, element);
}
return elements;
}

private global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic> Failures(global::DripSharp.Brine.TestResults.TestResult res) {
var list = new global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic>();
long i = 0;
foreach (var fail in global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::DripSharp.Brine.TestResults.Failure>>(res.Failures)) {
var attrs = this.BuildAttributes("message", fail.Kind);
long element = i++;
global::DripSharp.Runtime.JavaCompat.Add(list, this.BuildXmlElement("failure", attrs, (members) => members.Put(element, this.SyntheticElement(this.StripColors(fail.Message)))));
}
return list;
}

private global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic> Errors(global::DripSharp.Brine.TestResults.TestResult res) {
var list = new global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic>();
long i = 0;
foreach (var error in global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::DripSharp.Brine.TestResults.Error>>(res.Errors)) {
var attrs = this.BuildAttributes("message", error.Message!);
long element = i++;
global::DripSharp.Runtime.JavaCompat.Add(list, this.BuildXmlElement("error", attrs, (members) => members.Put(element, this.SyntheticElement(this.StripColors(global::DripSharp.Runtime.JavaCompat.ExceptionMessage(error.Exception))))));
}
return list;
}

private global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic> Error(global::DripSharp.Brine.TestResults.Error error) {
var list = new global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmDynamic>();
var attrs = this.BuildAttributes("message", error.Message!);
global::DripSharp.Runtime.JavaCompat.Add(list, this.BuildXmlElement("error", attrs, (members) => members.Put(1, this.SyntheticElement(this.StripColors(global::DripSharp.Runtime.JavaCompat.Concat("\n", global::DripSharp.Runtime.JavaCompat.ExceptionMessage(error.Exception)))))));
return list;
}

private global::DripSharp.Brine.Runtime.VmDynamic BuildXmlElement(string name, global::DripSharp.Brine.Runtime.VmMapping attributes, params global::DripSharp.Brine.Runtime.VmDynamic[] elements) {
return this.BuildXmlElement(name, attributes, (members) => {
long i = 0;
foreach (var element in elements) {
members.Put(i++, this.SyntheticElement(element));
}
});
}

private global::DripSharp.Brine.Runtime.VmDynamic BuildXmlElement(string name, global::DripSharp.Brine.Runtime.VmMapping attributes, global::System.Action<global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember>> gen) {
global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember> members = global::DripSharp.Brine.Util.EconomicMaps.Of<object, global::DripSharp.Brine.Ast.Member.ObjectMember>(global::DripSharp.Brine.Runtime.Identifier.IS_XML_ELEMENT, global::DripSharp.Brine.Runtime.VmUtils.CreateSyntheticObjectProperty(global::DripSharp.Brine.Runtime.Identifier.IS_XML_ELEMENT, "", true), global::DripSharp.Brine.Runtime.Identifier.NAME, global::DripSharp.Brine.Runtime.VmUtils.CreateSyntheticObjectProperty(global::DripSharp.Brine.Runtime.Identifier.NAME, "", name), global::DripSharp.Brine.Runtime.Identifier.ATTRIBUTES, global::DripSharp.Brine.Runtime.VmUtils.CreateSyntheticObjectProperty(global::DripSharp.Brine.Runtime.Identifier.ATTRIBUTES, "", attributes), global::DripSharp.Brine.Runtime.Identifier.IS_BLOCK_FORMAT, global::DripSharp.Brine.Runtime.VmUtils.CreateSyntheticObjectProperty(global::DripSharp.Brine.Runtime.Identifier.IS_BLOCK_FORMAT, "", true));
gen(members);
return new global::DripSharp.Brine.Runtime.VmDynamic(global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyMaterializedFrame(), global::DripSharp.Brine.Runtime.BaseModule.GetDynamicClass().GetPrototype(), members, (members.Size() - 4));
}

private global::DripSharp.Brine.Runtime.VmMapping BuildAttributes(params object[] attributes) {
global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember> attrs = global::DripSharp.Brine.Util.EconomicMaps.Create<object, global::DripSharp.Brine.Ast.Member.ObjectMember>(attributes.Length);
for (int i = 0; (i < attributes.Length); i += 2) {
attrs.Put(attributes[i], global::DripSharp.Brine.Runtime.VmUtils.CreateSyntheticObjectEntry(global::DripSharp.Runtime.JavaCompat.StringValueOf(attributes[i]), attributes[(i + 1)]));
}
return new global::DripSharp.Brine.Runtime.VmMapping(global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyMaterializedFrame(), global::DripSharp.Brine.Runtime.BaseModule.GetMappingClass().GetPrototype(), attrs);
}

private global::DripSharp.Brine.Ast.Member.ObjectMember SyntheticElement(object constantValue) {
return global::DripSharp.Brine.Runtime.VmUtils.CreateSyntheticObjectElement("", constantValue);
}

private global::DripSharp.Brine.Runtime.VmTyped MakeCdata(string text) {
var clazz = global::DripSharp.Brine.Runtime.XmlModule.GetCDataClass();
global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember> attrs = global::DripSharp.Brine.Util.EconomicMaps.Of<object, global::DripSharp.Brine.Ast.Member.ObjectMember>(global::DripSharp.Brine.Runtime.Identifier.TEXT, global::DripSharp.Brine.Runtime.VmUtils.CreateSyntheticObjectProperty((global::DripSharp.Brine.Runtime.Identifier?)default!, "", text));
return new global::DripSharp.Brine.Runtime.VmTyped(global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyMaterializedFrame(), clazz.GetPrototype(), clazz, attrs);
}

private string StripColors(string str) {
return global::DripSharp.Runtime.JavaCompat.StringReplaceAll(str, "\u001B\\[[;\\d]*m", "");
}

private static string RenderXML(string indent, string version, global::DripSharp.Brine.Runtime.VmDynamic value) {
var builder = new global::System.Text.StringBuilder();
var renderer = new global::DripSharp.Brine.Stdlib.Xml.RendererNodes.Renderer(builder, indent, version, "", global::DripSharp.Brine.Runtime.VmMapping.Empty(), global::DripSharp.Brine.Stdlib.PklConverter.NOOP);
renderer.RenderDocument(value);
return builder.ToString();
}
}
