// <auto-generated />
// Mechanically translated from: org/pkl/core/util/ArrayUtils.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Util;

internal sealed partial class ArrayUtils
{
public static readonly int[] EMPTY_INT_ARRAY = new int[0];

public static int[] Append(int[] array, int elem) {
if ((array.Length == 0)) {
return new int[] { elem };
}
var ret = global::DripSharp.Runtime.JavaCompat.CopyOf<int>(array, (array.Length + 1));
ret[array.Length] = elem;
return ret;
}

public static int[] Append(int[] array, int elem1, int elem2) {
if ((array.Length == 0)) {
return new int[] { elem1, elem2 };
}
var ret = global::DripSharp.Runtime.JavaCompat.CopyOf<int>(array, (array.Length + 2));
ret[array.Length] = elem1;
ret[(array.Length + 1)] = elem2;
return ret;
}

public static int[] Concat(int[] array1, int[] array2) {
var result = new int[(array1.Length + array2.Length)];
global::DripSharp.Runtime.JavaCompat.ArrayCopy(array1, 0, result, 0, array1.Length);
global::DripSharp.Runtime.JavaCompat.ArrayCopy(array2, 0, result, array1.Length, array2.Length);
return result;
}
}
