// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/member/InvokeSuperMethodNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Member;

internal abstract partial class InvokeSuperMethodNode : global::DripSharp.Brine.Ast.ExpressionNode
{
private readonly global::DripSharp.Brine.Runtime.Identifier methodName = default!;

private readonly global::DripSharp.Brine.Ast.ExpressionNode[] argumentNodes = default!;

private readonly bool needsConst;

protected internal InvokeSuperMethodNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Runtime.Identifier methodName, global::DripSharp.Brine.Ast.ExpressionNode[] argumentNodes, bool needsConst) : base(sourceSection) {

this.needsConst = needsConst;
global::DripSharp.Runtime.JavaCompat.Assert(() => !(methodName.IsLocalMethod()));
this.methodName = methodName;
this.argumentNodes = argumentNodes;
}

protected internal virtual object Eval(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame, global::DripSharp.Brine.Ast.Member.ClassMethod supermethod, global::DripSharp.Brine.Runtime.Truffle.api.nodes.DirectCallNode callNode) {
var args = new object[(2 + this.argumentNodes.Length)];
args[0] = global::DripSharp.Brine.Runtime.VmUtils.GetReceiverOrNull(frame)!;
args[1] = supermethod.GetOwner();
for (int i = 0; (i < this.argumentNodes.Length); i++) {
args[(2 + i)] = this.argumentNodes[i].ExecuteGeneric(frame);
}
return callNode.Call(args);
}

protected internal virtual global::DripSharp.Brine.Ast.Member.ClassMethod FindSupermethod(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
var owner = global::DripSharp.Brine.Runtime.VmUtils.GetOwner(frame);
while ((owner is global::DripSharp.Brine.Runtime.VmFunction)) {
owner = owner.GetEnclosingOwner()!;
}
global::DripSharp.Runtime.JavaCompat.Assert(() => (owner != default!), () => "VmFunction always has a parent");
global::DripSharp.Runtime.JavaCompat.Assert(() => owner.IsPrototype());
var superclass = owner.GetVmClass().GetSuperclass()!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (superclass! != default!));
var supermethod = superclass!.GetMethod(this.methodName)!;
if ((supermethod! != default!)) {
if ((this.needsConst && !(supermethod!.IsConst()))) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().EvalError("methodMustBeConst", this.methodName.ToString()).Build();
}
return supermethod!;
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
var parent = owner.GetParent()!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (parent! != default!));
throw this.ExceptionBuilder().CannotFindMethod(parent!, this.methodName, this.argumentNodes.Length, false).Build();
}
}
