// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/member/InvokeClassMethodNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Member;

internal sealed partial class InvokeClassMethodNode : global::DripSharp.Brine.Ast.Expression.Member.AbstractInvokeMethodLexicalNode
{
public InvokeClassMethodNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Runtime.Identifier methodName, int levelsUp, global::DripSharp.Brine.Ast.ExpressionNode[] argumentNodes, bool needsConst) : base(sourceSection, methodName, levelsUp, argumentNodes, needsConst) {

}

protected internal override void DoCheckConst(global::DripSharp.Brine.Runtime.VmObjectLike owner) {
var method = owner.GetVmClass().GetDeclaredMethod(base.methodName)!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (method! != default!));
if (!(method!.IsConst())) {
throw this.ExceptionBuilder().EvalError("methodMustBeConst", base.methodName).Build();
}
}

protected internal override global::DripSharp.Brine.Runtime.Truffle.api.CallTarget GetCallTarget(global::DripSharp.Brine.Runtime.VmObjectLike owner) {
var method = owner.GetVmClass().GetDeclaredMethod(base.methodName)!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (method! != default!));
return method!.GetCallTarget(this.GetSourceSection());
}
}
