// <auto-generated />
// Mechanically translated from: org/pkl/core/packages/PackageResolver.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Packages;

public abstract partial class PackageResolver : global::System.IDisposable
{
public abstract void Close();
public void Dispose() => this.Close();

public static PackageResolver GetInstance(global::DripSharp.Brine.SecurityManager securityManager, global::DripSharp.Brine.Http.HttpClient httpClient, string? cachedDir) {
return ((cachedDir! == default!) ? (PackageResolver)(new global::DripSharp.Brine.Packages.PackageResolvers.InMemoryPackageResolver(securityManager, httpClient)) : (PackageResolver)(new global::DripSharp.Brine.Packages.PackageResolvers.DiskCachedPackageResolver(securityManager, httpClient, cachedDir!)));
}

public abstract global::DripSharp.Brine.Packages.DependencyMetadata GetDependencyMetadata(global::DripSharp.Brine.Packages.PackageUri uri, global::DripSharp.Brine.Packages.Checksums? checksums);

internal abstract global::DripSharp.Brine.Util.Pair<global::DripSharp.Brine.Packages.DependencyMetadata, global::DripSharp.Brine.Packages.Checksums> GetDependencyMetadataAndComputeChecksum(global::DripSharp.Brine.Packages.PackageUri packageUri);

public abstract void DownloadPackage(global::DripSharp.Brine.Packages.PackageUri uri, global::DripSharp.Brine.Packages.Checksums? checksums, bool noTransitive);

public abstract byte[] GetBytes(global::DripSharp.Brine.Packages.PackageAssetUri uri, bool allowDirectories, global::DripSharp.Brine.Packages.Checksums? checksums);

public abstract global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Module.PathElement> ListElements(global::DripSharp.Brine.Packages.PackageAssetUri uri, global::DripSharp.Brine.Packages.Checksums? checksums);

public abstract bool HasElement(global::DripSharp.Brine.Packages.PackageAssetUri uri, global::DripSharp.Brine.Packages.Checksums? checksums);
}
