// <auto-generated />
// Mechanically translated from: org/pkl/core/packages/PackageLoadError.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Packages;

public sealed partial class PackageLoadError : global::System.Exception
{
private readonly string messageName = default!;

private readonly object[]? arguments = default!;

public PackageLoadError(global::System.Exception cause, string messageName, params object[]? arguments) : base(global::DripSharp.Brine.Util.ErrorMessages.Create(messageName, arguments!), cause) {

this.messageName = messageName;
this.arguments = arguments!;
}

public PackageLoadError(string messageName, params object[]? arguments) : base(global::DripSharp.Brine.Util.ErrorMessages.Create(messageName, arguments!)) {

this.messageName = messageName;
this.arguments = arguments!;
}

public string GetMessageName() {
return this.messageName;
}

public object[]? GetArguments() {
return this.arguments!;
}
}
