// <auto-generated />
// Mechanically translated from: org/pkl/core/project/ProjectDeps.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Project;

public sealed partial class ProjectDeps
{
private static readonly global::System.Collections.Generic.ISet<int> supportedSchemaVersions = global::DripSharp.Runtime.JavaCompat.EnumSetOf<int>(1);

private readonly global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<global::DripSharp.Brine.Project.CanonicalPackageUri, global::DripSharp.Brine.Packages.Dependency> resolvedDependencies = default!;

public static ProjectDeps ParseFromPath(string path) {
var input = global::DripSharp.Runtime.JavaCompat.ReadString(path);
return ProjectDeps.ParseFromString(input);
}

public static ProjectDeps ParseFromString(string input) {
var parsed = global::DripSharp.Brine.Util.Json.Json.ParseObject(input);
var schemaVersion = parsed.GetInt("schemaVersion");
if (!(global::DripSharp.Runtime.JavaCompat.CollectionContains(ProjectDeps.supportedSchemaVersions, schemaVersion))) {
throw new global::DripSharp.Brine.Packages.PackageLoadError("unsupportedProjectDepsVersion", schemaVersion);
}
var resolvedDependencies = parsed.Get<global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<global::DripSharp.Brine.Project.CanonicalPackageUri, global::DripSharp.Brine.Packages.Dependency>>("resolvedDependencies", ProjectDeps.ParseResolvedDependencies);
return new ProjectDeps(resolvedDependencies);
}

private static global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<global::DripSharp.Brine.Project.CanonicalPackageUri, global::DripSharp.Brine.Packages.Dependency> ParseResolvedDependencies(object @object) {
if (!((@object is global::DripSharp.Brine.Util.Json.Json.JsObject jsObj))) {
throw new global::DripSharp.Brine.Util.Json.Json.FormatException("resolvedDependencies", "object", ((object)(@object)).GetType());
}
var ret = global::DripSharp.Brine.Util.EconomicMaps.Create<global::DripSharp.Brine.Project.CanonicalPackageUri, global::DripSharp.Brine.Packages.Dependency>(jsObj.Size());
foreach (var entry in jsObj.EntrySet()) {
global::DripSharp.Brine.Packages.Dependency resolvedDependency = ProjectDeps.ParseResolvedDependency(entry);
var canonicalPackageUri = global::DripSharp.Brine.Project.CanonicalPackageUri.Of(entry.Key);
ret.Put(canonicalPackageUri, resolvedDependency);
}
return ret;
}

private static global::DripSharp.Brine.Packages.Dependency ParseResolvedDependency(global::DripSharp.Runtime.JavaMapEntry<string, object> entry) {
var input = entry.Value;
if (!((input is global::DripSharp.Brine.Util.Json.Json.JsObject obj))) {
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().EvalError("invalid object").Build();
}
var type = obj.GetString("type");
var uri = obj.Get<global::DripSharp.Brine.Packages.PackageUri>("uri", global::DripSharp.Brine.Packages.PackageUtils.ParsePackageUriWithoutChecksums);
if (global::DripSharp.Runtime.JavaCompat.Equals(type, "remote")) {
var checksums = global::DripSharp.Brine.Packages.DependencyMetadata.ParseChecksums(obj.GetObject("checksums"));
return new global::DripSharp.Brine.Packages.Dependency.RemoteDependency(uri, checksums);
} else {
global::DripSharp.Runtime.JavaCompat.Assert(() => global::DripSharp.Runtime.JavaCompat.Equals(type, "local"));
var pathStr = obj.GetString("path");
return new global::DripSharp.Brine.Packages.Dependency.LocalDependency(uri, global::DripSharp.Runtime.JavaCompat.PathOf(pathStr));
}
}

internal ProjectDeps(global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<global::DripSharp.Brine.Project.CanonicalPackageUri, global::DripSharp.Brine.Packages.Dependency> resolvedDependencies) {
this.resolvedDependencies = resolvedDependencies;
}

public global::DripSharp.Brine.Packages.Dependency? Get(global::DripSharp.Brine.Project.CanonicalPackageUri canonicalPackageUri) {
return this.resolvedDependencies.Get(canonicalPackageUri);
}

public void WriteTo(global::System.IO.Stream @out) {
new ProjectDepsWriter(@out, this.resolvedDependencies).Write();
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("ProjectDeps {", this.resolvedDependencies), "}");
}

public override bool Equals(object o) {
if (global::System.Object.ReferenceEquals(this, o)) return true;
if (o is not global::DripSharp.Brine.Project.ProjectDeps that) return false;
return global::DripSharp.Runtime.JavaCompat.EconomicMapEquals(this.resolvedDependencies, that.resolvedDependencies);
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.resolvedDependencies);
}

internal sealed partial class ProjectDepsWriter
{
internal readonly global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<global::DripSharp.Brine.Project.CanonicalPackageUri, global::DripSharp.Brine.Packages.Dependency> projectDeps = default!;

internal readonly global::DripSharp.Brine.Util.Json.JsonWriter jsonWriter = default!;

internal ProjectDepsWriter(global::System.IO.Stream @out, global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<global::DripSharp.Brine.Project.CanonicalPackageUri, global::DripSharp.Brine.Packages.Dependency> projectDeps) {
this.jsonWriter = new global::DripSharp.Brine.Util.Json.JsonWriter(new global::System.IO.StreamWriter(@out, global::DripSharp.Runtime.JavaStandardCharsets.UTF8));
this.jsonWriter.SetIndent("  ");
this.projectDeps = projectDeps;
}

internal void WriteChecksums(global::DripSharp.Brine.Packages.Checksums checksums) {
this.jsonWriter.BeginObject();
this.jsonWriter.Name("sha256").Value(checksums.GetSha256());
this.jsonWriter.EndObject();
}

internal void WriteRemoteDependency(global::DripSharp.Brine.Packages.Dependency.RemoteDependency remoteDependency) {
this.jsonWriter.BeginObject();
this.jsonWriter.Name("type").Value("remote");
this.jsonWriter.Name("uri").Value(remoteDependency.GetPackageUri().ToString());
this.jsonWriter.Name("checksums");
global::DripSharp.Runtime.JavaCompat.Assert(() => (remoteDependency.GetChecksums()! != default!));
this.WriteChecksums(remoteDependency.GetChecksums()!);
this.jsonWriter.EndObject();
}

internal void WriteLocalDependency(global::DripSharp.Brine.Packages.Dependency.LocalDependency localDependency) {
this.jsonWriter.BeginObject();
this.jsonWriter.Name("type").Value("local");
this.jsonWriter.Name("uri").Value(localDependency.GetPackageUri().ToString());
this.jsonWriter.Name("path").Value(global::DripSharp.Brine.Util.IoUtils.ToNormalizedPathString(localDependency.GetPath()));
this.jsonWriter.EndObject();
}

internal void Write() {
this.jsonWriter.BeginObject();
this.jsonWriter.Name("schemaVersion").Value((long)(1));
this.jsonWriter.Name("resolvedDependencies");
this.jsonWriter.BeginObject();
var cursor = this.projectDeps.GetEntries();
while (cursor.Advance()) {
this.jsonWriter.Name(cursor.GetKey().ToString());
var dependency = cursor.GetValue();
if ((dependency is global::DripSharp.Brine.Packages.Dependency.LocalDependency localDependency)) {
this.WriteLocalDependency(localDependency);
} else {
this.WriteRemoteDependency((global::DripSharp.Brine.Packages.Dependency.RemoteDependency)(dependency!));
}
}
this.jsonWriter.EndObject();
this.jsonWriter.EndObject();
this.jsonWriter.Newline();
this.jsonWriter.Close();
}
}
}
