// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/binary/LessThanNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Binary;

[global::DripSharp.Brine.Runtime.Truffle.api.nodes.NodeInfo("<")]
internal abstract partial class LessThanNode : global::DripSharp.Brine.Ast.Expression.Binary.ComparatorNode
{
protected internal LessThanNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection) : base(sourceSection) {

}

protected internal virtual bool Eval(string left, string right) {
return (global::DripSharp.Runtime.JavaCompat.StringCompareTo(left, right) < 0);
}

protected internal virtual bool Eval(long left, long right) {
return (left < right);
}

protected internal virtual bool Eval(long left, double right) {
return (left < right);
}

protected internal virtual bool Eval(double left, long right) {
return (left < right);
}

protected internal virtual bool Eval(double left, double right) {
return (left < right);
}

protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmDuration left, global::DripSharp.Brine.Runtime.VmDuration right) {
return (left.CompareTo(right) < 0);
}

protected internal virtual bool Eval(global::DripSharp.Brine.Runtime.VmDataSize left, global::DripSharp.Brine.Runtime.VmDataSize right) {
return (left.CompareTo(right) < 0);
}

public override global::DripSharp.Brine.Runtime.Truffle.api.instrumentation.InstrumentableNode.WrapperNode CreateWrapper(global::DripSharp.Brine.Runtime.Truffle.api.instrumentation.ProbeNode probe) {
return new global::DripSharp.Brine.Ast.Expression.Binary.LessThanNodeWrapper(base.sourceSection, this, probe);
}
}
