// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/binary/SubscriptNodeGen.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Binary;

internal sealed partial class SubscriptNodeGen : global::DripSharp.Brine.Ast.Expression.Binary.SubscriptNode
{
private global::DripSharp.Brine.Ast.ExpressionNode leftNode_ = default!;

private global::DripSharp.Brine.Ast.ExpressionNode rightNode_ = default!;

private int state_0_;

private global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode eval3_callNode_ = default!;

private global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode eval4_callNode_ = default!;

private global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode eval5_callNode_ = default!;

private SubscriptNodeGen(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Ast.ExpressionNode leftNode, global::DripSharp.Brine.Ast.ExpressionNode rightNode) : base(sourceSection) {

this.leftNode_ = leftNode;
this.rightNode_ = rightNode;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetLeftNode() {
return this.leftNode_;
}

protected internal override global::DripSharp.Brine.Ast.ExpressionNode GetRightNode() {
return this.rightNode_;
}

private bool FallbackGuard_(int state_0, object leftNodeValue, object rightNodeValue) {
if ((rightNodeValue is long)) {
if ((!(((state_0 & 1) != 0)) && (leftNodeValue is string))) {
return false;
}
if ((!(((state_0 & 2) != 0)) && (leftNodeValue is global::DripSharp.Brine.Runtime.VmList))) {
return false;
}
}
if ((!(((state_0 & 4) != 0)) && (leftNodeValue is global::DripSharp.Brine.Runtime.VmMap))) {
return false;
}
if (((!(((state_0 & 8) != 0)) && (leftNodeValue is global::DripSharp.Brine.Runtime.VmListing)) && (rightNodeValue is long))) {
return false;
}
if ((!(((state_0 & 16) != 0)) && (leftNodeValue is global::DripSharp.Brine.Runtime.VmMapping))) {
return false;
}
if ((!(((state_0 & 32) != 0)) && (leftNodeValue is global::DripSharp.Brine.Runtime.VmDynamic))) {
return false;
}
if ((!(((state_0 & 64) != 0)) && (leftNodeValue is global::DripSharp.Brine.Runtime.VmReference))) {
return false;
}
if (((!(((state_0 & 128) != 0)) && (leftNodeValue is global::DripSharp.Brine.Runtime.VmBytes)) && (rightNodeValue is long))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if ((((state_0 & 372) == 0) && (state_0 != 0))) {
return this.ExecuteGeneric_long0(state_0, frameValue);
} else {
return this.ExecuteGeneric_generic1(state_0, frameValue);
}
}

private object ExecuteGeneric_long0(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
object leftNodeValue_ = this.leftNode_.ExecuteGeneric(frameValue);
long rightNodeValue_;
try {
rightNodeValue_ = this.rightNode_.ExecuteInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(leftNodeValue_, ex.GetResult());
}
if (((state_0 & 139) != 0)) {
if ((((state_0 & 1) != 0) && (leftNodeValue_ is string))) {
string leftNodeValue____157_24 = (string)(leftNodeValue_!);
return this.Eval(leftNodeValue____157_24, rightNodeValue_);
}
if ((((state_0 & 2) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmList))) {
global::DripSharp.Brine.Runtime.VmList leftNodeValue____161_24 = (global::DripSharp.Brine.Runtime.VmList)(leftNodeValue_!);
return this.Eval(leftNodeValue____161_24, rightNodeValue_);
}
if ((((state_0 & 8) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing leftNodeValue____165_27 = (global::DripSharp.Brine.Runtime.VmListing)(leftNodeValue_!);
{
global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode callNode__ = this.eval3_callNode_;
if ((callNode__ != default!)) {
return this.Eval(leftNodeValue____165_27, rightNodeValue_, callNode__);
}
}
}
if ((((state_0 & 128) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmBytes))) {
global::DripSharp.Brine.Runtime.VmBytes leftNodeValue____174_25 = (global::DripSharp.Brine.Runtime.VmBytes)(leftNodeValue_!);
return this.Eval(leftNodeValue____174_25, rightNodeValue_);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(leftNodeValue_, rightNodeValue_);
}

private object ExecuteGeneric_generic1(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
object leftNodeValue_ = this.leftNode_.ExecuteGeneric(frameValue);
object rightNodeValue_ = this.rightNode_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 3) != 0) && (rightNodeValue_ is long))) {
long rightNodeValue____188_22 = (long)(rightNodeValue_);
if ((((state_0 & 1) != 0) && (leftNodeValue_ is string))) {
string leftNodeValue____190_28 = (string)(leftNodeValue_!);
return this.Eval(leftNodeValue____190_28, rightNodeValue____188_22);
}
if ((((state_0 & 2) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmList))) {
global::DripSharp.Brine.Runtime.VmList leftNodeValue____194_28 = (global::DripSharp.Brine.Runtime.VmList)(leftNodeValue_!);
return this.Eval(leftNodeValue____194_28, rightNodeValue____188_22);
}
}
if ((((state_0 & 4) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmMap))) {
global::DripSharp.Brine.Runtime.VmMap leftNodeValue____199_23 = (global::DripSharp.Brine.Runtime.VmMap)(leftNodeValue_!);
return this.Eval(leftNodeValue____199_23, rightNodeValue_);
}
if ((((state_0 & 8) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmListing))) {
global::DripSharp.Brine.Runtime.VmListing leftNodeValue____203_27 = (global::DripSharp.Brine.Runtime.VmListing)(leftNodeValue_!);
if ((rightNodeValue_ is long)) {
long rightNodeValue____205_26 = (long)(rightNodeValue_);
{
global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode callNode__ = this.eval3_callNode_;
if ((callNode__ != default!)) {
return this.Eval(leftNodeValue____203_27, rightNodeValue____205_26, callNode__);
}
}
}
}
if (((state_0 & 112) != 0)) {
if ((((state_0 & 16) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmMapping))) {
global::DripSharp.Brine.Runtime.VmMapping leftNodeValue____216_31 = (global::DripSharp.Brine.Runtime.VmMapping)(leftNodeValue_!);
{
global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode callNode__1 = this.eval4_callNode_;
if ((callNode__1 != default!)) {
return this.Eval(leftNodeValue____216_31, rightNodeValue_, callNode__1);
}
}
}
if ((((state_0 & 32) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmDynamic))) {
global::DripSharp.Brine.Runtime.VmDynamic leftNodeValue____225_31 = (global::DripSharp.Brine.Runtime.VmDynamic)(leftNodeValue_!);
{
global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode callNode__2 = this.eval5_callNode_;
if ((callNode__2 != default!)) {
return this.Eval(leftNodeValue____225_31, rightNodeValue_, callNode__2);
}
}
}
if ((((state_0 & 64) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmReference))) {
global::DripSharp.Brine.Runtime.VmReference leftNodeValue____234_33 = (global::DripSharp.Brine.Runtime.VmReference)(leftNodeValue_!);
return this.Eval(leftNodeValue____234_33, rightNodeValue_);
}
}
if ((((state_0 & 128) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmBytes))) {
global::DripSharp.Brine.Runtime.VmBytes leftNodeValue____239_25 = (global::DripSharp.Brine.Runtime.VmBytes)(leftNodeValue_!);
if ((rightNodeValue_ is long)) {
long rightNodeValue____241_26 = (long)(rightNodeValue_);
return this.Eval(leftNodeValue____239_25, rightNodeValue____241_26);
}
}
if (((state_0 & 256) != 0)) {
if (this.FallbackGuard_(state_0, leftNodeValue_, rightNodeValue_)) {
return this.Fallback(leftNodeValue_, rightNodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(leftNodeValue_, rightNodeValue_);
}

public override long ExecuteInt(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 318) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteGeneric(frameValue));
}
object leftNodeValue_ = this.leftNode_.ExecuteGeneric(frameValue);
long rightNodeValue_;
try {
rightNodeValue_ = this.rightNode_.ExecuteInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteAndSpecialize(leftNodeValue_, ex.GetResult()));
}
if ((((state_0 & 128) != 0) && (leftNodeValue_ is global::DripSharp.Brine.Runtime.VmBytes))) {
global::DripSharp.Brine.Runtime.VmBytes leftNodeValue__ = (global::DripSharp.Brine.Runtime.VmBytes)(leftNodeValue_!);
return this.Eval(leftNodeValue__, rightNodeValue_);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteAndSpecialize(leftNodeValue_, rightNodeValue_));
}

private object ExecuteAndSpecialize(object leftNodeValue, object rightNodeValue) {
int state_0 = this.state_0_;
if ((rightNodeValue is long)) {
long rightNodeValue___280_18 = (long)(rightNodeValue);
if ((leftNodeValue is string)) {
string leftNodeValue___282_24 = (string)(leftNodeValue!);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___282_24, rightNodeValue___280_18);
}
if ((leftNodeValue is global::DripSharp.Brine.Runtime.VmList)) {
global::DripSharp.Brine.Runtime.VmList leftNodeValue___288_24 = (global::DripSharp.Brine.Runtime.VmList)(leftNodeValue!);
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___288_24, rightNodeValue___280_18);
}
}
if ((leftNodeValue is global::DripSharp.Brine.Runtime.VmMap)) {
global::DripSharp.Brine.Runtime.VmMap leftNodeValue___295_19 = (global::DripSharp.Brine.Runtime.VmMap)(leftNodeValue!);
state_0 = (state_0 | 4);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___295_19, rightNodeValue);
}
if ((leftNodeValue is global::DripSharp.Brine.Runtime.VmListing)) {
global::DripSharp.Brine.Runtime.VmListing leftNodeValue___301_23 = (global::DripSharp.Brine.Runtime.VmListing)(leftNodeValue!);
if ((rightNodeValue is long)) {
long rightNodeValue___303_22 = (long)(rightNodeValue);
global::System.Threading.Thread.MemoryBarrier();
this.eval3_callNode_ = this.Insert(global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode.Create());
state_0 = (state_0 | 8);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___301_23, rightNodeValue___303_22, this.eval3_callNode_);
}
}
if ((leftNodeValue is global::DripSharp.Brine.Runtime.VmMapping)) {
global::DripSharp.Brine.Runtime.VmMapping leftNodeValue___312_23 = (global::DripSharp.Brine.Runtime.VmMapping)(leftNodeValue!);
global::System.Threading.Thread.MemoryBarrier();
this.eval4_callNode_ = this.Insert(global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode.Create());
state_0 = (state_0 | 16);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___312_23, rightNodeValue, this.eval4_callNode_);
}
if ((leftNodeValue is global::DripSharp.Brine.Runtime.VmDynamic)) {
global::DripSharp.Brine.Runtime.VmDynamic leftNodeValue___320_23 = (global::DripSharp.Brine.Runtime.VmDynamic)(leftNodeValue!);
global::System.Threading.Thread.MemoryBarrier();
this.eval5_callNode_ = this.Insert(global::DripSharp.Brine.Runtime.Truffle.api.nodes.IndirectCallNode.Create());
state_0 = (state_0 | 32);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___320_23, rightNodeValue, this.eval5_callNode_);
}
if ((leftNodeValue is global::DripSharp.Brine.Runtime.VmReference)) {
global::DripSharp.Brine.Runtime.VmReference leftNodeValue___328_25 = (global::DripSharp.Brine.Runtime.VmReference)(leftNodeValue!);
state_0 = (state_0 | 64);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___328_25, rightNodeValue);
}
if ((leftNodeValue is global::DripSharp.Brine.Runtime.VmBytes)) {
global::DripSharp.Brine.Runtime.VmBytes leftNodeValue___334_21 = (global::DripSharp.Brine.Runtime.VmBytes)(leftNodeValue!);
if ((rightNodeValue is long)) {
long rightNodeValue___336_22 = (long)(rightNodeValue);
state_0 = (state_0 | 128);
this.state_0_ = state_0;
return this.Eval(leftNodeValue___334_21, rightNodeValue___336_22);
}
}
state_0 = (state_0 | 256);
this.state_0_ = state_0;
return this.Fallback(leftNodeValue, rightNodeValue);
}

public static global::DripSharp.Brine.Ast.Expression.Binary.SubscriptNode Create(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Ast.ExpressionNode leftNode, global::DripSharp.Brine.Ast.ExpressionNode rightNode) {
return new SubscriptNodeGen(sourceSection, leftNode, rightNode);
}
}
