// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/ExternalMethod5Node.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib;

internal abstract partial class ExternalMethod5Node : global::DripSharp.Brine.Stdlib.ExternalMethodNode
{
protected internal abstract global::DripSharp.Brine.Ast.ExpressionNode GetArg1Node();

protected internal abstract global::DripSharp.Brine.Ast.ExpressionNode GetArg2Node();

protected internal abstract global::DripSharp.Brine.Ast.ExpressionNode GetArg3Node();

protected internal abstract global::DripSharp.Brine.Ast.ExpressionNode GetArg4Node();

protected internal abstract global::DripSharp.Brine.Ast.ExpressionNode GetArg5Node();

protected internal virtual object Fallback(object receiver, object arg1, object arg2, object arg3, object arg4, object arg5) {
throw this.ExceptionBuilder().EvalError("methodNotDefined5", this.GetQualifiedMemberName(), global::DripSharp.Brine.Runtime.VmUtils.GetClass(arg1), global::DripSharp.Brine.Runtime.VmUtils.GetClass(arg2), global::DripSharp.Brine.Runtime.VmUtils.GetClass(arg3), global::DripSharp.Brine.Runtime.VmUtils.GetClass(arg4), global::DripSharp.Brine.Runtime.VmUtils.GetClass(arg5)).WithProgramValue("Argument 1", arg1).WithProgramValue("Argument 2", arg2).WithProgramValue("Argument 3", arg3).WithProgramValue("Argument 4", arg4).WithProgramValue("Argument 5", arg5).Build();
}

internal delegate ExternalMethod5Node Factory(global::DripSharp.Brine.Ast.ExpressionNode receiverNode, global::DripSharp.Brine.Ast.ExpressionNode arg1Node, global::DripSharp.Brine.Ast.ExpressionNode arg2Node, global::DripSharp.Brine.Ast.ExpressionNode arg3Node, global::DripSharp.Brine.Ast.ExpressionNode arg4Node, global::DripSharp.Brine.Ast.ExpressionNode arg5Node);
}
