// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/PklConverter.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib;

internal sealed partial class PklConverter : global::DripSharp.Brine.Runtime.VmValueConverter<object>
{
public override object Convert(object value, global::System.Collections.Generic.IEnumerable<object> path) {
if ((value is global::DripSharp.Brine.Runtime.VmValue vmValue)) {
return vmValue.Accept(this, path);
}
if ((value is string @string)) {
return this.ConvertString(@string, path);
}
if ((value is bool b)) {
return this.ConvertBoolean(b, path);
}
if ((value is long l)) {
return this.ConvertInt(l, path);
}
if ((value is double d)) {
return this.ConvertFloat(d, path);
}
throw new global::System.ArgumentException(global::DripSharp.Runtime.JavaCompat.Concat("Cannot convert VM value with unexpected type: ", value));
}

private readonly global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.VmClass, global::DripSharp.Brine.Runtime.VmFunction> typeConverters = default!;

private readonly global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.VmClass, global::DripSharp.Brine.Runtime.VmFunction> convertPropertyTransformers = default!;

private readonly global::DripSharp.Brine.Util.Pair<object[], global::DripSharp.Brine.Runtime.VmFunction>[] pathConverters = default!;

private readonly object rendererOrParser = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? stringConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? booleanConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? intConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? floatConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? durationConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? dataSizeConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? bytesConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? intSeqConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? listConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? setConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? mapConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? listingConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? mappingConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? dynamicConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? pairConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? regexConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? nullConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? classConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? typeAliasConverter = default!;

private readonly global::DripSharp.Brine.Runtime.VmFunction? referenceConverter = default!;

private PklConverter(global::DripSharp.Brine.Runtime.VmMapping converters, global::DripSharp.Brine.Runtime.VmMapping convertPropertyTransformers, object rendererOrParser) {
converters.Force(false, false);
convertPropertyTransformers.Force(false, false);
this.typeConverters = this.CreateTypeConverters(converters);
this.convertPropertyTransformers = this.CreateConvertPropertyTransformers(convertPropertyTransformers);
this.pathConverters = this.CreatePathConverters(converters);
this.rendererOrParser = rendererOrParser;
this.stringConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetStringClass());
this.booleanConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetBooleanClass());
this.intConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetIntClass());
this.floatConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetFloatClass());
this.durationConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetDurationClass());
this.dataSizeConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetDataSizeClass());
this.bytesConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetBytesClass());
this.intSeqConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetIntSeqClass());
this.listConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetListClass());
this.setConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetSetClass());
this.mapConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetMapClass());
this.listingConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetListingClass());
this.mappingConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetMappingClass());
this.dynamicConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetDynamicClass());
this.pairConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetPairClass());
this.regexConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetRegexClass());
this.nullConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetNullClass());
this.classConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetClassClass());
this.typeAliasConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.BaseModule.GetTypeAliasClass());
this.referenceConverter = global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, global::DripSharp.Brine.Runtime.RefModule.GetReferenceClass());
}

public static readonly PklConverter NOOP = new PklConverter(global::DripSharp.Brine.Runtime.VmMapping.Empty(), global::DripSharp.Brine.Runtime.VmMapping.Empty(), global::DripSharp.Brine.Runtime.VmNull.WithoutDefault());

public static PklConverter FromRenderer(global::DripSharp.Brine.Runtime.VmTyped renderer) {
var converters = (global::DripSharp.Brine.Runtime.VmMapping)(global::DripSharp.Brine.Runtime.VmUtils.ReadMember(renderer, global::DripSharp.Brine.Runtime.Identifier.CONVERTERS)!);
var convertPropertyTransformers = (global::DripSharp.Brine.Runtime.VmMapping)(global::DripSharp.Brine.Runtime.VmUtils.ReadMember(renderer, global::DripSharp.Brine.Runtime.Identifier.CONVERT_PROPERTY_TRANSFORMERS)!);
return new PklConverter(converters, convertPropertyTransformers, renderer);
}

public static PklConverter FromParser(global::DripSharp.Brine.Runtime.VmTyped parser) {
var converters = (global::DripSharp.Brine.Runtime.VmMapping)(global::DripSharp.Brine.Runtime.VmUtils.ReadMember(parser, global::DripSharp.Brine.Runtime.Identifier.CONVERTERS)!);
return new PklConverter(converters, global::DripSharp.Brine.Runtime.VmMapping.Empty(), parser);
}

public override object ConvertString(string value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.stringConverter!);
}

public override object ConvertBoolean(bool value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.booleanConverter!);
}

public override object ConvertInt(long value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.intConverter!);
}

public override object ConvertFloat(double value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.floatConverter!);
}

public override object ConvertDuration(global::DripSharp.Brine.Runtime.VmDuration value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.durationConverter!);
}

public override object ConvertDataSize(global::DripSharp.Brine.Runtime.VmDataSize value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.dataSizeConverter!);
}

public override object ConvertBytes(global::DripSharp.Brine.Runtime.VmBytes value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.bytesConverter!);
}

public override object ConvertIntSeq(global::DripSharp.Brine.Runtime.VmIntSeq value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.intSeqConverter!);
}

public override object ConvertList(global::DripSharp.Brine.Runtime.VmList value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.listConverter!);
}

public override object ConvertSet(global::DripSharp.Brine.Runtime.VmSet value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.setConverter!);
}

public override object ConvertMap(global::DripSharp.Brine.Runtime.VmMap value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.mapConverter!);
}

public override object ConvertListing(global::DripSharp.Brine.Runtime.VmListing value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.listingConverter!);
}

public override object ConvertMapping(global::DripSharp.Brine.Runtime.VmMapping value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.mappingConverter!);
}

public override object ConvertDynamic(global::DripSharp.Brine.Runtime.VmDynamic value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.dynamicConverter!);
}

public override object ConvertTyped(global::DripSharp.Brine.Runtime.VmTyped value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.FindTypeConverter(value.GetVmClass())!);
}

public override object ConvertPair(global::DripSharp.Brine.Runtime.VmPair value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.pairConverter!);
}

public override object ConvertRegex(global::DripSharp.Brine.Runtime.VmRegex value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.regexConverter!);
}

public override object ConvertFunction(global::DripSharp.Brine.Runtime.VmFunction value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, global::DripSharp.Runtime.JavaCompat.MapGet(this.typeConverters, value.GetVmClass()));
}

public override object ConvertClass(global::DripSharp.Brine.Runtime.VmClass value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.classConverter!);
}

public override object ConvertTypeAlias(global::DripSharp.Brine.Runtime.VmTypeAlias value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.typeAliasConverter!);
}

public override object ConvertNull(global::DripSharp.Brine.Runtime.VmNull value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.nullConverter!);
}

public override object ConvertReference(global::DripSharp.Brine.Runtime.VmReference value, global::System.Collections.Generic.IEnumerable<object> path) {
return this.DoConvert(value, path, this.referenceConverter!);
}

public override global::DripSharp.Brine.Util.Pair<global::DripSharp.Brine.Runtime.Identifier, object> ConvertProperty(global::DripSharp.Brine.Ast.Member.ClassProperty property, object value, global::System.Collections.Generic.IEnumerable<object> path) {
var name = property.GetName();
var annotations = property.GetAllAnnotations(false);
if (global::DripSharp.Runtime.JavaCompat.ListIsEmpty(annotations)) {
return global::DripSharp.Brine.Util.Pair<object, object>.Of<global::DripSharp.Brine.Runtime.Identifier, object>(name, value);
}
var prop = new global::DripSharp.Brine.Runtime.VmPair(name.ToString(), value);
foreach (var __foreachValue_annotation in annotations) {
var annotation = __foreachValue_annotation;
{
if (!(annotation.GetVmClass().IsSubclassOf(global::DripSharp.Brine.Runtime.BaseModule.GetConvertPropertyClass()))) {
continue;
}
var transformer = this.FindConvertPropertyTransformer(annotation.GetVmClass())!;
if ((transformer! != default!)) {
annotation = (global::DripSharp.Brine.Runtime.VmTyped)(transformer!.Apply(annotation)!);
}
var renderFunction = (global::DripSharp.Brine.Runtime.VmFunction)(global::DripSharp.Brine.Runtime.VmUtils.ReadMember(annotation, global::DripSharp.Brine.Runtime.Identifier.RENDER)!);
prop = (global::DripSharp.Brine.Runtime.VmPair)(renderFunction.Apply(prop, this.rendererOrParser)!);
}
}
return global::DripSharp.Brine.Util.Pair<object, object>.Of<global::DripSharp.Brine.Runtime.Identifier, object>(global::DripSharp.Brine.Runtime.Identifier.Get((string)(prop.GetFirst()!)), prop.GetSecond());
}

private global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.VmClass, global::DripSharp.Brine.Runtime.VmFunction> CreateTypeConverters(global::DripSharp.Brine.Runtime.VmMapping converters) {
var result = global::DripSharp.Runtime.JavaCompat.NewJavaDictionary<global::DripSharp.Brine.Runtime.VmClass, global::DripSharp.Brine.Runtime.VmFunction>();
converters.IterateMemberValues((key, member, value) => {
global::DripSharp.Runtime.JavaCompat.Assert(() => (value != default!));
if ((key is global::DripSharp.Brine.Runtime.VmClass vmClass)) {
global::DripSharp.Runtime.JavaCompat.MapPut(result, vmClass, (global::DripSharp.Brine.Runtime.VmFunction)(value!));
}
return true;
});
return result;
}

private global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.VmClass, global::DripSharp.Brine.Runtime.VmFunction> CreateConvertPropertyTransformers(global::DripSharp.Brine.Runtime.VmMapping convertPropertyTransformers) {
var result = global::DripSharp.Runtime.JavaCompat.NewJavaDictionary<global::DripSharp.Brine.Runtime.VmClass, global::DripSharp.Brine.Runtime.VmFunction>();
convertPropertyTransformers.IterateMemberValues((key, member, value) => {
global::DripSharp.Runtime.JavaCompat.Assert(() => (value != default!));
global::DripSharp.Runtime.JavaCompat.MapPut(result, (global::DripSharp.Brine.Runtime.VmClass)(key!), (global::DripSharp.Brine.Runtime.VmFunction)(value!));
return true;
});
return result;
}

private global::DripSharp.Brine.Util.Pair<object[], global::DripSharp.Brine.Runtime.VmFunction>[] CreatePathConverters(global::DripSharp.Brine.Runtime.VmMapping converters) {
var result = new global::System.Collections.Generic.List<global::DripSharp.Brine.Util.Pair<object[], global::DripSharp.Brine.Runtime.VmFunction>>();
var parser = new global::DripSharp.Brine.Stdlib.PathSpecParser();
converters.IterateMemberValues((key, member, value) => {
global::DripSharp.Runtime.JavaCompat.Assert(() => (value != default!));
if ((key is string @string)) {
global::DripSharp.Runtime.JavaCompat.Add(result, global::DripSharp.Brine.Util.Pair<object, object>.Of<object[], global::DripSharp.Brine.Runtime.VmFunction>(parser.Parse(@string), (global::DripSharp.Brine.Runtime.VmFunction)(value!)));
}
return true;
});
return global::DripSharp.Runtime.JavaCompat.ToArray(result);
}

private global::DripSharp.Brine.Runtime.VmFunction? GetPathConverter(global::System.Collections.Generic.IEnumerable<object> path) {
foreach (var converter in this.pathConverters) {
if (global::DripSharp.Brine.Stdlib.PathConverterSupport.PathMatches(global::DripSharp.Runtime.JavaCompat.AsList<object>(converter.first), path)) {
return converter.second;
}
}
return default!;
}

private global::DripSharp.Brine.Runtime.VmFunction? FindTypeConverter(global::DripSharp.Brine.Runtime.VmClass clazz) {
return this.FindConverterByType<global::DripSharp.Brine.Runtime.VmFunction>(this.typeConverters, clazz)!;
}

private global::DripSharp.Brine.Runtime.VmFunction? FindConvertPropertyTransformer(global::DripSharp.Brine.Runtime.VmClass clazz) {
return this.FindConverterByType<global::DripSharp.Brine.Runtime.VmFunction>(this.convertPropertyTransformers, clazz)!;
}

private T? FindConverterByType<T>(global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.VmClass, T> bag, global::DripSharp.Brine.Runtime.VmClass clazz) {
for (var current = clazz; (current != default!); current = current.GetSuperclass()!) {
var found = global::DripSharp.Runtime.JavaCompat.MapGet(bag, current);
if ((found is not null)) {
return found;
}
}
return default!;
}

private object DoConvert(object value, global::System.Collections.Generic.IEnumerable<object> path, global::DripSharp.Brine.Runtime.VmFunction? typeConverter) {
var pathConverter = this.GetPathConverter(path)!;
if ((pathConverter! != default!)) {
return pathConverter!.Apply(value);
}
if ((typeConverter! != default!)) {
return typeConverter!.Apply(value);
}
return value;
}
}
