// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/VmObjectFactories.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib;

internal sealed partial class VmObjectFactories
{
public static readonly global::DripSharp.Brine.Stdlib.VmObjectFactory<global::DripSharp.Brine.Version> versionFactory = ((global::DripSharp.Brine.Stdlib.VmObjectFactory<global::DripSharp.Brine.Version>)(((global::DripSharp.Brine.Stdlib.VmObjectFactory<global::DripSharp.Brine.Version>)(((global::DripSharp.Brine.Stdlib.VmObjectFactory<global::DripSharp.Brine.Version>)(((global::DripSharp.Brine.Stdlib.VmObjectFactory<global::DripSharp.Brine.Version>)(((global::DripSharp.Brine.Stdlib.VmObjectFactory<global::DripSharp.Brine.Version>)(new global::DripSharp.Brine.Stdlib.VmObjectFactory<global::DripSharp.Brine.Version>(global::DripSharp.Brine.Runtime.SemVerModule.GetVersionClass).AddIntProperty("major", (value0) => value0.GetMajor()))).AddIntProperty("minor", (value0) => value0.GetMinor()))).AddIntProperty("patch", (value0) => value0.GetPatch()))).AddProperty<object>("preRelease", (version) => global::DripSharp.Brine.Runtime.VmNull.Lift(version.GetPreRelease()!)))).AddProperty<object>("build", (version) => global::DripSharp.Brine.Runtime.VmNull.Lift(version.GetBuild()!))));
}
