// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/member/ClassMethod.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Member;

internal sealed partial class ClassMethod : global::DripSharp.Brine.Ast.Member.ClassMember
{
private readonly global::System.Collections.Generic.IList<global::DripSharp.Brine.TypeParameter> typeParameters = default!;

private readonly string? deprecation = default!;

private global::DripSharp.Brine.Ast.Member.FunctionNode functionNode = default!;

public ClassMethod(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection headerSection, int modifiers, global::DripSharp.Brine.Runtime.Identifier name, string qualifiedName, global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection[] docComment, global::System.Collections.Generic.IList<global::DripSharp.Brine.Runtime.VmTyped> annotations, global::DripSharp.Brine.Runtime.VmTyped owner, global::System.Collections.Generic.IList<global::DripSharp.Brine.TypeParameter> typeParameters, string? deprecation) : base(sourceSection, headerSection, modifiers, name, qualifiedName, docComment, annotations, owner) {

this.typeParameters = typeParameters;
this.deprecation = deprecation!;
}

public void InitFunctionNode(global::DripSharp.Brine.Ast.Member.FunctionNode functionNode) {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.functionNode == default!));
this.functionNode = functionNode;
}

public global::DripSharp.Brine.Runtime.Truffle.api.CallTarget GetCallTarget() {
return this.functionNode.GetCallTarget();
}

private void ReportDeprecation(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection callSite) {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.deprecation! != default!));
var logger = global::DripSharp.Brine.Runtime.VmContext.Get((global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node?)default!).GetLogger();
((global::DripSharp.Brine.Logger)(logger)).Warn(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Method `", base.qualifiedName), "` is deprecated"), ((this.deprecation!.Length == 0) ? "" : global::DripSharp.Runtime.JavaCompat.Concat(": ", this.deprecation!))), global::DripSharp.Brine.Runtime.VmUtils.CreateStackFrame(callSite, (string?)default!));
}

public global::DripSharp.Brine.Runtime.Truffle.api.CallTarget GetCallTarget(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection callSite) {
if ((this.deprecation! != default!)) {
this.ReportDeprecation(callSite);
}
return this.functionNode.GetCallTarget();
}

public int GetParameterCount() {
return this.functionNode.GetParameterCount();
}

public global::DripSharp.Brine.Ast.Type.TypeNode? GetReturnTypeNode() {
return this.functionNode.GetReturnTypeNode()!;
}

public override string GetCallSignature() {
return this.functionNode.GetCallSignature();
}

public global::DripSharp.Brine.Runtime.VmTyped GetMirror() {
return global::DripSharp.Brine.Runtime.MirrorFactories.methodFactory.Create(this);
}

public global::DripSharp.Brine.Runtime.VmSet GetModifierMirrors() {
return global::DripSharp.Brine.Ast.VmModifier.GetMirrors(base.modifiers, false);
}

public global::DripSharp.Brine.Runtime.VmList GetTypeParameterMirrors() {
var builder = ((global::DripSharp.Brine.Runtime.VmCollection.Builder<global::DripSharp.Brine.Runtime.VmList>)(global::DripSharp.Brine.Runtime.VmList.EMPTY.CreateBuilder()));
foreach (var typeParameter in this.typeParameters) {
builder.Add(global::DripSharp.Brine.Runtime.MirrorFactories.typeParameterFactory.Create(typeParameter));
}
return builder.Build();
}

public global::DripSharp.Brine.Runtime.VmMap GetParameterMirrors() {
return this.functionNode.GetParameterMirrors();
}

public global::DripSharp.Brine.Runtime.VmTyped GetReturnTypeMirror() {
return this.functionNode.GetReturnTypeMirror();
}

public global::DripSharp.Brine.PClass.Method Export(global::DripSharp.Brine.PClass owner) {
return this.functionNode.Export(owner, base.docComment, base.annotations, base.modifiers, this.typeParameters);
}
}
