// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/member/DefaultPropertyBodyNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Member;

internal sealed partial class DefaultPropertyBodyNode : global::DripSharp.Brine.Ast.ExpressionNode
{
private readonly global::DripSharp.Brine.Runtime.Identifier propertyName = default!;

private readonly global::DripSharp.Brine.Ast.Member.PropertyTypeNode? typeNode = default!;

public DefaultPropertyBodyNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Runtime.Identifier propertyName, global::DripSharp.Brine.Ast.Member.PropertyTypeNode? typeNode) : base(sourceSection) {

this.propertyName = propertyName;
this.typeNode = typeNode!;
}

public bool IsUndefined(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
return ((this.typeNode! == default!) || (this.typeNode!.GetDefaultValue(frame)! == default!));
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
if ((this.typeNode! != default!)) {
var defaultValue = this.typeNode!.GetDefaultValue(frame)!;
if ((defaultValue! != default!)) {
return defaultValue!;
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw this.ExceptionBuilder().UndefinedPropertyValue(this.propertyName, global::DripSharp.Brine.Runtime.VmUtils.GetReceiver(frame)).Build();
}
}
