// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/member/ObjectMethodNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Member;

internal sealed partial class ObjectMethodNode : global::DripSharp.Brine.Ast.Member.RegularMemberNode
{
private readonly global::DripSharp.Brine.Runtime.VmLanguage language = default!;

private readonly int parameterCount;

private readonly global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode[]? unresolvedParameterTypeNodes = default!;

private global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode? unresolvedReturnTypeNode = default!;

private global::DripSharp.Brine.Ast.Member.FunctionNode functionNode = default!;

public ObjectMethodNode(global::DripSharp.Brine.Runtime.VmLanguage language, global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameDescriptor descriptor, global::DripSharp.Brine.Ast.Member.ObjectMember member, global::DripSharp.Brine.Ast.ExpressionNode bodyNode, int parameterCount, global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode[]? unresolvedParameterTypeNodes, global::DripSharp.Brine.Ast.Type.UnresolvedTypeNode? unresolvedReturnTypeNode) : base(language, descriptor, member, bodyNode) {

this.language = language;
this.parameterCount = parameterCount;
this.unresolvedParameterTypeNodes = unresolvedParameterTypeNodes!;
this.unresolvedReturnTypeNode = unresolvedReturnTypeNode!;
}

public global::DripSharp.Brine.Ast.Type.TypeNode? GetReturnTypeNode() {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.functionNode != default!));
return this.functionNode.GetReturnTypeNode()!;
}

protected internal override global::DripSharp.Brine.Runtime.Truffle.api.CallTarget ExecuteImpl(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
if ((this.functionNode == default!)) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
var parameterTypeNodes = global::DripSharp.Brine.Runtime.VmUtils.ResolveParameterTypes(frame, this.GetFrameDescriptor(), this.unresolvedParameterTypeNodes!);
var returnTypeNode = ((this.unresolvedReturnTypeNode! != default!) ? this.unresolvedReturnTypeNode!.Execute(frame) : (global::DripSharp.Brine.Ast.Type.TypeNode)(default!));
this.functionNode = new global::DripSharp.Brine.Ast.Member.FunctionNode(this.language, this.GetFrameDescriptor(), base.member, this.parameterCount, parameterTypeNodes, returnTypeNode, true, base.bodyNode);
}
return this.functionNode.GetCallTarget();
}
}
