// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/frame/ReadExactFrameSlotNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Frame;

internal abstract partial class ReadExactFrameSlotNode : global::DripSharp.Brine.Ast.ExpressionNode
{
private readonly int slot;

protected internal ReadExactFrameSlotNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, int slot) : base(sourceSection) {

this.slot = slot;
}

protected internal virtual long EvalInt(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
return frame.GetLong(this.slot);
}

protected internal virtual double EvalFloat(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
return frame.GetDouble(this.slot);
}

protected internal virtual bool EvalBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
return frame.GetBoolean(this.slot);
}

protected internal virtual object EvalObject(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
return frame.GetObject(this.slot);
}

protected internal virtual object EvalGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frame) {
return frame.GetValue(this.slot);
}
}
