// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/frame/ReadExactFrameSlotNodeGen.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Frame;

internal sealed partial class ReadExactFrameSlotNodeGen : global::DripSharp.Brine.Ast.Frame.ReadExactFrameSlotNode
{
private int state_0_;

private ReadExactFrameSlotNodeGen(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, int slot) : base(sourceSection, slot) {

}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 173) != 0)) {
if (((state_0 & 1) != 0)) {
try {
return this.EvalInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -2);
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
if (((state_0 & 8) != 0)) {
try {
return this.EvalFloat(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -9);
state_0 = (state_0 | 16);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
if (((state_0 & 32) != 0)) {
try {
return this.EvalBoolean(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -33);
state_0 = (state_0 | 64);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
if (((state_0 & 128) != 0)) {
try {
return this.EvalObject(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -129);
state_0 = (state_0 | 256);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
if (((state_0 & 4) != 0)) {
return this.EvalGeneric(frameValue);
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(frameValue);
}

public override bool ExecuteBoolean(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 132) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteGeneric(frameValue));
}
if (((state_0 & 32) != 0)) {
try {
return this.EvalBoolean(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -33);
state_0 = (state_0 | 64);
this.state_0_ = state_0;
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteAndSpecialize(frameValue));
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectBoolean(this.ExecuteAndSpecialize(frameValue));
}

public override double ExecuteFloat(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 132) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectDouble(this.ExecuteGeneric(frameValue));
}
if (((state_0 & 8) != 0)) {
try {
return this.EvalFloat(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -9);
state_0 = (state_0 | 16);
this.state_0_ = state_0;
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectDouble(this.ExecuteAndSpecialize(frameValue));
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectDouble(this.ExecuteAndSpecialize(frameValue));
}

public override long ExecuteInt(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 132) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteGeneric(frameValue));
}
if (((state_0 & 1) != 0)) {
try {
return this.EvalInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -2);
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteAndSpecialize(frameValue));
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteAndSpecialize(frameValue));
}

private object ExecuteAndSpecialize(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if ((((state_0 & 4) == 0) && ((state_0 & 2) == 0))) {
state_0 = (state_0 | 1);
this.state_0_ = state_0;
try {
return this.EvalInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -2);
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
if ((((state_0 & 4) == 0) && ((state_0 & 16) == 0))) {
state_0 = (state_0 | 8);
this.state_0_ = state_0;
try {
return this.EvalFloat(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -9);
state_0 = (state_0 | 16);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
if ((((state_0 & 4) == 0) && ((state_0 & 64) == 0))) {
state_0 = (state_0 | 32);
this.state_0_ = state_0;
try {
return this.EvalBoolean(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -33);
state_0 = (state_0 | 64);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
if ((((state_0 & 4) == 0) && ((state_0 & 256) == 0))) {
state_0 = (state_0 | 128);
this.state_0_ = state_0;
try {
return this.EvalObject(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.frame.FrameSlotTypeException) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
state_0 = this.state_0_;
state_0 = (state_0 & -129);
state_0 = (state_0 | 256);
this.state_0_ = state_0;
return this.ExecuteAndSpecialize(frameValue);
}
}
state_0 = (state_0 & -170);
state_0 = (state_0 | 4);
this.state_0_ = state_0;
return this.EvalGeneric(frameValue);
}

public static global::DripSharp.Brine.Ast.Frame.ReadExactFrameSlotNode Create(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, int slot) {
return new ReadExactFrameSlotNodeGen(sourceSection, slot);
}
}
