// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/MemberLookupMode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast;

internal sealed partial class MemberLookupMode
{
public static MemberLookupMode ValueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<MemberLookupMode>(name);
public static MemberLookupMode[] Values() => global::DripSharp.Runtime.JavaCompat.EnumValues<MemberLookupMode>();

[global::DripSharp.Runtime.JavaEnumNameAttribute("IMPLICIT_LEXICAL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly MemberLookupMode IMPLICIT_LEXICAL = new MemberLookupMode();

[global::DripSharp.Runtime.JavaEnumNameAttribute("IMPLICIT_BASE")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly MemberLookupMode IMPLICIT_BASE = new MemberLookupMode();

[global::DripSharp.Runtime.JavaEnumNameAttribute("IMPLICIT_THIS")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(3)]
public static readonly MemberLookupMode IMPLICIT_THIS = new MemberLookupMode();

[global::DripSharp.Runtime.JavaEnumNameAttribute("EXPLICIT_RECEIVER")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(4)]
public static readonly MemberLookupMode EXPLICIT_RECEIVER = new MemberLookupMode();

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
}
