// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/PklNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast;

[global::DripSharp.Brine.Runtime.Truffle.api.nodes.NodeInfo("")]
internal abstract partial class PklNode : global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node
{
protected internal readonly global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection = default!;

protected internal PklNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection) {
this.sourceSection = sourceSection;
}

protected internal PklNode() : this(global::DripSharp.Brine.Runtime.VmUtils.UnavailableSourceSection()) {

}

public sealed override global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection GetSourceSection() {
if ((this is global::DripSharp.Brine.Runtime.Truffle.api.instrumentation.InstrumentableNode.WrapperNode wrapperNode)) {
return wrapperNode.GetDelegateNode().GetSourceSection();
}
return this.sourceSection;
}

protected internal virtual global::DripSharp.Brine.Runtime.VmExceptionBuilder ExceptionBuilder() {
return new global::DripSharp.Brine.Runtime.VmExceptionBuilder().WithLocation(this);
}

protected internal string GetShortName() {
return global::DripSharp.Brine.Runtime.VmUtils.GetNodeInfo(this).ShortName();
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.JavaStringFormat("(%s:%d) %s", this.sourceSection.GetSource().GetName(), this.sourceSection.GetStartLine(), this.sourceSection.GetCharacters());
}
}
