// <auto-generated />
// Mechanically translated from: org/pkl/parser/syntax/Class.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Parser.Syntax;

public sealed partial class Class : global::DripSharp.Brine.Parser.Syntax.AbstractNode
{
private readonly int modifiersOffset;

private readonly int keywordOffset;

public Class(global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Node?> nodes, int modifiersOffset, int keywordOffset, global::DripSharp.Brine.Parser.Span span) : base(span, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Node?>>(nodes)) {

this.modifiersOffset = modifiersOffset;
this.keywordOffset = keywordOffset;
}

public override T Accept<T>(global::DripSharp.Brine.Parser.ParserVisitor<T> visitor) {
return visitor.VisitClass(this);
}

public global::DripSharp.Brine.Parser.Syntax.DocComment? GetDocComment() {
return global::DripSharp.Runtime.JavaCompat.CastReference<global::DripSharp.Brine.Parser.Syntax.DocComment>(global::DripSharp.Runtime.JavaCompat.ListGet(base.children, 0));
}

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Annotation> GetAnnotations() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Annotation>>(global::DripSharp.Runtime.JavaCompat.CastList<global::DripSharp.Brine.Parser.Syntax.Annotation>(global::DripSharp.Runtime.JavaCompat.SubList(base.children, 1, this.modifiersOffset)));
}

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Modifier> GetModifiers() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Modifier>>(global::DripSharp.Runtime.JavaCompat.CastList<global::DripSharp.Brine.Parser.Syntax.Modifier>(global::DripSharp.Runtime.JavaCompat.SubList(base.children, this.modifiersOffset, this.keywordOffset)));
}

public global::DripSharp.Brine.Parser.Syntax.Keyword GetClassKeyword() {
var ret = global::DripSharp.Runtime.JavaCompat.CastReference<global::DripSharp.Brine.Parser.Syntax.Keyword>(global::DripSharp.Runtime.JavaCompat.ListGet(base.children, this.keywordOffset));
global::DripSharp.Runtime.JavaCompat.Assert(() => (ret! != default!));
return ret!;
}

public global::DripSharp.Brine.Parser.Syntax.Identifier GetName() {
var ret = global::DripSharp.Runtime.JavaCompat.CastReference<global::DripSharp.Brine.Parser.Syntax.Identifier>(global::DripSharp.Runtime.JavaCompat.ListGet(base.children, (this.keywordOffset + 1)));
global::DripSharp.Runtime.JavaCompat.Assert(() => (ret! != default!));
return ret!;
}

public global::DripSharp.Brine.Parser.Syntax.TypeParameterList? GetTypeParameterList() {
return global::DripSharp.Runtime.JavaCompat.CastReference<global::DripSharp.Brine.Parser.Syntax.TypeParameterList>(global::DripSharp.Runtime.JavaCompat.ListGet(base.children, (this.keywordOffset + 2)));
}

public global::DripSharp.Brine.Parser.Syntax.Type? GetSuperClass() {
return global::DripSharp.Runtime.JavaCompat.CastReference<global::DripSharp.Brine.Parser.Syntax.Type>(global::DripSharp.Runtime.JavaCompat.ListGet(base.children, (this.keywordOffset + 3)));
}

public global::DripSharp.Brine.Parser.Syntax.ClassBody? GetBody() {
return global::DripSharp.Runtime.JavaCompat.CastReference<global::DripSharp.Brine.Parser.Syntax.ClassBody>(global::DripSharp.Runtime.JavaCompat.ListGet(base.children, (this.keywordOffset + 4)));
}

public global::DripSharp.Brine.Parser.Span GetHeaderSpan() {
global::DripSharp.Brine.Parser.Span start = default!;
for (var i = this.modifiersOffset; (i < global::DripSharp.Runtime.JavaCompat.CollectionCount(base.children)); i++) {
var child = global::DripSharp.Runtime.JavaCompat.ListGet(base.children, i);
if ((child! != default!)) {
start = child!.Span();
break;
}
}
global::DripSharp.Brine.Parser.Span end;
if ((this.GetSuperClass()! != default!)) {
end = this.GetSuperClass()!.Span();
} else {
if ((this.GetTypeParameterList()! != default!)) {
end = this.GetTypeParameterList()!.Span();
} else {
end = this.GetName().Span();
}
}
global::DripSharp.Runtime.JavaCompat.Assert(() => !global::System.Object.ReferenceEquals(start!, default!));
return start!.EndWith(end);
}
}
