// <auto-generated />
// Mechanically translated from: org/pkl/parser/syntax/Modifier.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Parser.Syntax;

public sealed partial class Modifier : global::DripSharp.Brine.Parser.Syntax.AbstractNode
{
private readonly ModifierValue value = default!;

public Modifier(ModifierValue value, global::DripSharp.Brine.Parser.Span span) : base(span, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Node?>>(global::DripSharp.Runtime.JavaCompat.ListOf<global::DripSharp.Brine.Parser.Syntax.Node>())) {

this.value = value;
}

public override T Accept<T>(global::DripSharp.Brine.Parser.ParserVisitor<T> visitor) {
return visitor.VisitModifier(this);
}

public ModifierValue GetValue() {
return this.value;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Modifier{value=", this.value), ", span="), base.span), '}');
}

public override bool Equals(object? o) {
if (((o! == default!) || (((object)(this)).GetType() != ((object)(o!)).GetType()))) {
return false;
}
if ((this == o!)) {
return true;
}
Modifier modifier = (Modifier)(o!);
return ((this.value == modifier!.value) && global::DripSharp.Runtime.JavaCompat.Equals(base.span, modifier!.span));
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.value, base.span);
}

public sealed partial class ModifierValue
{
public static ModifierValue ValueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<ModifierValue>(name);
public static ModifierValue[] Values() => global::DripSharp.Runtime.JavaCompat.EnumValues<ModifierValue>();

[global::DripSharp.Runtime.JavaEnumNameAttribute("EXTERNAL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly ModifierValue EXTERNAL = new ModifierValue();

[global::DripSharp.Runtime.JavaEnumNameAttribute("ABSTRACT")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly ModifierValue ABSTRACT = new ModifierValue();

[global::DripSharp.Runtime.JavaEnumNameAttribute("OPEN")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(2)]
public static readonly ModifierValue OPEN = new ModifierValue();

[global::DripSharp.Runtime.JavaEnumNameAttribute("LOCAL")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(3)]
public static readonly ModifierValue LOCAL = new ModifierValue();

[global::DripSharp.Runtime.JavaEnumNameAttribute("HIDDEN")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(4)]
public static readonly ModifierValue HIDDEN = new ModifierValue();

[global::DripSharp.Runtime.JavaEnumNameAttribute("FIXED")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(5)]
public static readonly ModifierValue FIXED = new ModifierValue();

[global::DripSharp.Runtime.JavaEnumNameAttribute("CONST")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(6)]
public static readonly ModifierValue CONST = new ModifierValue();

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
}
}
