// <auto-generated />
// Mechanically translated from: org/pkl/parser/syntax/ObjectBody.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Parser.Syntax;

public sealed partial class ObjectBody : global::DripSharp.Brine.Parser.Syntax.AbstractNode
{
private readonly int membersOffset;

public ObjectBody(global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Node> nodes, int membersOffset, global::DripSharp.Brine.Parser.Span span) : base(span, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Node?>>(nodes)) {

this.membersOffset = membersOffset;
}

public override T Accept<T>(global::DripSharp.Brine.Parser.ParserVisitor<T> visitor) {
return visitor.VisitObjectBody(this);
}

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Parameter> GetParameters() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Parameter>>(global::DripSharp.Runtime.JavaCompat.CastList<global::DripSharp.Brine.Parser.Syntax.Parameter>(global::DripSharp.Runtime.JavaCompat.SubList(base.children, 0, this.membersOffset)));
}

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.ObjectMember> GetMembers() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.ObjectMember>>(global::DripSharp.Runtime.JavaCompat.CastList<global::DripSharp.Brine.Parser.Syntax.ObjectMember>(global::DripSharp.Runtime.JavaCompat.SubList(base.children, this.membersOffset, global::DripSharp.Runtime.JavaCompat.CollectionCount(base.children))));
}
}
