// <auto-generated />
// Mechanically translated from: org/pkl/parser/syntax/QualifiedIdentifier.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Parser.Syntax;

public sealed partial class QualifiedIdentifier : global::DripSharp.Brine.Parser.Syntax.AbstractNode
{
public QualifiedIdentifier(global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Identifier> identifiers) : base(global::DripSharp.Runtime.JavaCompat.ListGet(identifiers, 0).span.EndWith(global::DripSharp.Runtime.JavaCompat.ListGet(identifiers, (global::DripSharp.Runtime.JavaCompat.CollectionCount(identifiers) - 1)).span), global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Node?>>(identifiers)) {

}

public override T Accept<T>(global::DripSharp.Brine.Parser.ParserVisitor<T> visitor) {
return visitor.VisitQualifiedIdentifier(this);
}

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Identifier> GetIdentifiers() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Identifier>>(global::DripSharp.Runtime.JavaCompat.CastList<global::DripSharp.Brine.Parser.Syntax.Identifier>(base.children));
}

public string Text() {
return global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(this.GetIdentifiers(), (value0) => value0.GetValue()), global::DripSharp.Runtime.JavaCompat.Joining("."));
}
}
