// <auto-generated />
// Mechanically translated from: org/pkl/parser/syntax/TypeAnnotation.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Parser.Syntax;

public sealed partial class TypeAnnotation : global::DripSharp.Brine.Parser.Syntax.AbstractNode
{
public TypeAnnotation(global::DripSharp.Brine.Parser.Syntax.Type type, global::DripSharp.Brine.Parser.Span span) : base(span, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Parser.Syntax.Node?>>(global::DripSharp.Runtime.JavaCompat.ListOf<global::DripSharp.Brine.Parser.Syntax.Type>(type))) {

}

public override T Accept<T>(global::DripSharp.Brine.Parser.ParserVisitor<T> visitor) {
return visitor.VisitTypeAnnotation(this);
}

public new global::DripSharp.Brine.Parser.Syntax.Type GetType() {
var ret = global::DripSharp.Runtime.JavaCompat.CastReference<global::DripSharp.Brine.Parser.Syntax.Type>(global::DripSharp.Runtime.JavaCompat.ListGet(base.children, 0));
global::DripSharp.Runtime.JavaCompat.Assert(() => (ret! != default!));
return ret!;
}
}
