// <auto-generated />
// Mechanically translated from: org/pkl/core/stdlib/registry/JsonnetMemberRegistry.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Stdlib.Registry;

internal sealed partial class JsonnetMemberRegistry : global::DripSharp.Brine.Stdlib.Registry.ExternalMemberRegistry
{
internal JsonnetMemberRegistry() {
this.Register("pkl.jsonnet#Renderer.renderDocument", global::DripSharp.Brine.Stdlib.Jsonnet.RendererNodesFactory.RenderDocumentNodeGen.Create);
this.Register("pkl.jsonnet#Renderer.renderValue", global::DripSharp.Brine.Stdlib.Jsonnet.RendererNodesFactory.RenderValueNodeGen.Create);
}
}
