// <auto-generated />
// Mechanically translated from: org/pkl/core/BufferedLogger.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine;

public sealed partial class BufferedLogger : global::DripSharp.Brine.Logger
{
private readonly global::System.Text.StringBuilder builder = new global::System.Text.StringBuilder();

private readonly global::DripSharp.Brine.Logger logger = default!;

public BufferedLogger(global::DripSharp.Brine.Logger logger) {
this.logger = logger;
}

public void Trace(string message, global::DripSharp.Brine.StackFrame frame) {
this.builder.Append(message).Append("\n");
((global::DripSharp.Brine.Logger)(this.logger)).Trace(message, frame);
}

public void Warn(string message, global::DripSharp.Brine.StackFrame frame) {
this.builder.Append(message).Append("\n");
((global::DripSharp.Brine.Logger)(this.logger)).Warn(message, frame);
}

public void Clear() {
this.builder.Length = 0;
}

public string GetLogs() {
return this.builder.ToString();
}
}
