// <auto-generated />
// Mechanically translated from: org/pkl/core/Evaluator.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine;

public partial interface Evaluator : global::System.IDisposable
{
public void Dispose() => this.Close();

public static Evaluator Preconfigured() {
return global::DripSharp.Brine.EvaluatorBuilder.Preconfigured().Build();
}

public global::DripSharp.Brine.PModule Evaluate(global::DripSharp.Brine.ModuleSource moduleSource);

public string EvaluateOutputText(global::DripSharp.Brine.ModuleSource moduleSource);

public byte[] EvaluateOutputBytes(global::DripSharp.Brine.ModuleSource moduleSource);

public object EvaluateOutputValue(global::DripSharp.Brine.ModuleSource moduleSource);

public global::System.Collections.Generic.IReadOnlyDictionary<string, global::DripSharp.Brine.FileOutput> EvaluateOutputFiles(global::DripSharp.Brine.ModuleSource moduleSource);

public object EvaluateExpression(global::DripSharp.Brine.ModuleSource moduleSource, string expression);

internal sbyte[] EvaluateExpressionPklBinary(global::DripSharp.Brine.ModuleSource moduleSource, string expression);

public string EvaluateExpressionString(global::DripSharp.Brine.ModuleSource moduleSource, string expression);

public global::DripSharp.Brine.ModuleSchema EvaluateSchema(global::DripSharp.Brine.ModuleSource moduleSource);

public T EvaluateOutputValueAs<T>(global::DripSharp.Brine.ModuleSource moduleSource, global::DripSharp.Brine.PClassInfo<T> classInfo);

internal global::DripSharp.Brine.TestResults EvaluateTest(global::DripSharp.Brine.ModuleSource moduleSource, bool overwrite);

internal void EvaluateCommand(global::DripSharp.Brine.ModuleSource moduleSource, global::System.Collections.Generic.ISet<string> reservedFlagNames, global::System.Collections.Generic.ISet<string> reservedFlagShortNames, global::System.Action<global::DripSharp.Brine.CommandSpec> run);

public void Close();
}
