// <auto-generated />
// Mechanically translated from: org/pkl/core/ImportGraph.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine;

public sealed partial record class ImportGraph(global::System.Collections.Generic.IReadOnlyDictionary<global::System.Uri, global::System.Collections.Generic.IReadOnlySet<global::DripSharp.Brine.ImportGraph.Import>> Imports, global::System.Collections.Generic.IReadOnlyDictionary<global::System.Uri, global::System.Uri> ResolvedImports)
{
public sealed partial record class Import(global::System.Uri Uri) : global::System.IComparable<global::DripSharp.Brine.ImportGraph.Import>
{
public int CompareTo(Import o) {
return global::DripSharp.Runtime.JavaCompat.CompareUri(this.Uri, o.Uri);
}

public bool Equals(Import? other) {
if (global::System.Object.ReferenceEquals(this, other)) return true;
return other is not null &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.Uri, other.Uri);
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.Uri);
}
}

public static ImportGraph ParseFromJson(string input) {
var parsed = global::DripSharp.Brine.Util.Json.Json.ParseObject(input);
var imports = ImportGraph.ParseImports(parsed.GetObject("imports"));
var resolvedImports = ImportGraph.ParseResolvedImports(parsed.GetObject("resolvedImports"));
return new ImportGraph(global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<global::System.Uri, global::System.Collections.Generic.IReadOnlySet<Import>>>(global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<global::System.Uri, global::System.Collections.Generic.IReadOnlySet<Import>>>(imports)), global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<global::System.Uri, global::System.Uri>>(global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<global::System.Uri, global::System.Uri>>(resolvedImports)));
}

private static global::System.Collections.Generic.IDictionary<global::System.Uri, global::System.Collections.Generic.ISet<Import>> ParseImports(global::DripSharp.Brine.Util.Json.Json.JsObject jsObject) {
var ret = global::DripSharp.Runtime.JavaCompat.NewSortedDictionary<global::System.Uri, global::System.Collections.Generic.ISet<Import>>();
foreach (var entry in jsObject.EntrySet()) {
try {
var key = global::DripSharp.Runtime.JavaCompat.NewUri(entry.Key);
var value = entry.Value;
var set = global::DripSharp.Runtime.JavaCompat.NewSortedSet<Import>();
if (!((value is global::DripSharp.Brine.Util.Json.Json.JsArray array))) {
throw new global::DripSharp.Brine.Util.Json.Json.FormatException("array", ((object)(value)).GetType());
}
foreach (var elem in array) {
if (!((elem is global::DripSharp.Brine.Util.Json.Json.JsObject importObj))) {
throw new global::DripSharp.Brine.Util.Json.Json.FormatException("object", ((object)(elem)).GetType());
}
set.Add(ImportGraph.ParseImport(importObj));
}
global::DripSharp.Runtime.JavaCompat.MapPut(ret, key, set);
} catch (global::System.UriFormatException e) {
throw new global::DripSharp.Brine.Util.Json.Json.MappingException(entry.Key, e);
}
}
return ret;
}

private static Import ParseImport(global::DripSharp.Brine.Util.Json.Json.JsObject jsObject) {
var uri = jsObject.GetURI("uri");
return new Import(uri);
}

private static global::System.Collections.Generic.IDictionary<global::System.Uri, global::System.Uri> ParseResolvedImports(global::DripSharp.Brine.Util.Json.Json.JsObject jsObject) {
var ret = global::DripSharp.Runtime.JavaCompat.NewSortedDictionary<global::System.Uri, global::System.Uri>();
foreach (var entry in jsObject.EntrySet()) {
try {
var key = global::DripSharp.Runtime.JavaCompat.NewUri(entry.Key);
var value = entry.Value;
if (!((value is string str))) {
throw new global::DripSharp.Brine.Util.Json.Json.FormatException("string", ((object)(value)).GetType());
}
var valueUri = global::DripSharp.Runtime.JavaCompat.NewUri(str);
global::DripSharp.Runtime.JavaCompat.MapPut(ret, key, valueUri);
} catch (global::System.UriFormatException e) {
throw new global::DripSharp.Brine.Util.Json.Json.MappingException(entry.Key, e);
}
}
return ret;
}

public bool Equals(ImportGraph? other) {
if (global::System.Object.ReferenceEquals(this, other)) return true;
return other is not null &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.Imports, other.Imports) &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.ResolvedImports, other.ResolvedImports);
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.Imports, this.ResolvedImports);
}
}
