// <auto-generated />
// Mechanically translated from: org/pkl/core/PklInfo.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine;

public sealed partial class PklInfo
{
private static readonly PklInfo CURRENT = default!;

private readonly PackageIndex packageIndex = default!;

public static PklInfo Current() {
return PklInfo.CURRENT;
}

public PackageIndex GetPackageIndex() {
return this.packageIndex;
}

public sealed partial record class PackageIndex(string Homepage)
{
public string GetPackagePage(string packageName, string packageVersion) {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(this.Homepage, packageName), "/"), packageVersion), "/");
}

public bool Equals(PackageIndex? other) {
if (global::System.Object.ReferenceEquals(this, other)) return true;
return other is not null &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.Homepage, other.Homepage);
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.Homepage);
}
}
}
