// <auto-generated />
// Mechanically translated from: org/pkl/core/PType.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine;

public abstract partial class PType
{
public static readonly PType UNKNOWN = new Anonymous_29_7();

public static readonly PType NOTHING = new Anonymous_40_7();

public static readonly PType MODULE = new Anonymous_51_7();

private PType() {}

public virtual global::System.Collections.Generic.IReadOnlyList<PType> GetTypeArguments() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(global::DripSharp.Runtime.JavaCompat.ListOf<PType>());
}

public sealed partial class StringLiteral : global::DripSharp.Brine.PType
{
internal readonly string literal = default!;

public StringLiteral(string literal) {
this.literal = literal;
}

public string GetLiteral() {
return this.literal;
}

public override string ToString() {
return global::DripSharp.Brine.ValueFormatter.Basic().FormatStringValue(this.literal, "");
}
}

public sealed partial class Class : global::DripSharp.Brine.PType
{
internal readonly global::DripSharp.Brine.PClass pClass = default!;

internal readonly global::System.Collections.Generic.IList<PType> typeArguments = default!;

public Class(global::DripSharp.Brine.PClass pClass, global::System.Collections.Generic.IReadOnlyList<PType> typeArguments) {
this.pClass = pClass;
this.typeArguments = global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<PType>>(typeArguments);
}

public Class(global::DripSharp.Brine.PClass pClass) : this(pClass, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(global::DripSharp.Runtime.JavaCompat.ListOf<PType>())) {

}

public Class(global::DripSharp.Brine.PClass pClass, PType typeArgument1) : this(pClass, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(global::DripSharp.Runtime.JavaCompat.ListOf<PType>(typeArgument1))) {

}

public Class(global::DripSharp.Brine.PClass pClass, PType typeArgument1, PType typeArgument2) : this(pClass, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(global::DripSharp.Runtime.JavaCompat.ListOf<PType>(typeArgument1, typeArgument2))) {

}

public global::DripSharp.Brine.PClass GetPClass() {
return this.pClass;
}

public override global::System.Collections.Generic.IReadOnlyList<PType> GetTypeArguments() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(this.typeArguments);
}

public override string ToString() {
var result = this.pClass.GetDisplayName();
if (!(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(this.typeArguments))) {
result += global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("<", global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(this.typeArguments), (value0) => global::DripSharp.Runtime.JavaCompat.StringValueOf(value0)), global::DripSharp.Runtime.JavaCompat.Joining(", "))), ">");
}
return result;
}
}

public sealed partial class Nullable : global::DripSharp.Brine.PType
{
internal readonly PType baseType = default!;

public Nullable(PType baseType) {
this.baseType = baseType;
}

public PType GetBaseType() {
return this.baseType;
}

public override string ToString() {
return (((this.baseType is Function) || (this.baseType is Union)) ? global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("(", this.baseType), ")?") : global::DripSharp.Runtime.JavaCompat.Concat(this.baseType, "?"));
}
}

public sealed partial class Constrained : global::DripSharp.Brine.PType
{
internal readonly PType baseType = default!;

internal readonly global::System.Collections.Generic.IList<string> constraints = default!;

public Constrained(PType baseType, global::System.Collections.Generic.IReadOnlyList<string> constraints) {
this.baseType = baseType;
this.constraints = global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<string>>(constraints);
}

public PType GetBaseType() {
return this.baseType;
}

public global::System.Collections.Generic.IReadOnlyList<string> GetConstraints() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<string>>(this.constraints);
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat((((this.baseType is Function) || (this.baseType is Union)) ? (object)(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("(", this.baseType), ")")) : (object)(this.baseType)), "("), global::DripSharp.Runtime.JavaCompat.StringJoin(", ", this.constraints)), ")");
}
}

public sealed partial class Alias : global::DripSharp.Brine.PType
{
internal readonly global::DripSharp.Brine.TypeAlias typeAlias = default!;

internal readonly global::System.Collections.Generic.IList<PType> typeArguments = default!;

internal readonly PType aliasedType = default!;

public Alias(global::DripSharp.Brine.TypeAlias typeAlias) : this(typeAlias, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(global::DripSharp.Runtime.JavaCompat.ListOf<PType>()), typeAlias.GetAliasedType()) {

}

public Alias(global::DripSharp.Brine.TypeAlias typeAlias, global::System.Collections.Generic.IReadOnlyList<PType> typeArguments, PType aliasedType) {
this.typeAlias = typeAlias;
this.typeArguments = global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<PType>>(typeArguments);
this.aliasedType = aliasedType;
}

public global::DripSharp.Brine.TypeAlias GetTypeAlias() {
return this.typeAlias;
}

public override global::System.Collections.Generic.IReadOnlyList<PType> GetTypeArguments() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(this.typeArguments);
}

public PType GetAliasedType() {
return this.aliasedType;
}

public override string ToString() {
var result = this.typeAlias.GetDisplayName();
if (!(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(this.typeArguments))) {
result += global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("<", global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(this.typeArguments), (value0) => global::DripSharp.Runtime.JavaCompat.StringValueOf(value0)), global::DripSharp.Runtime.JavaCompat.Joining(", "))), ">");
}
return result;
}
}

public sealed partial class Function : global::DripSharp.Brine.PType
{
internal readonly global::System.Collections.Generic.IList<PType> parameterTypes = default!;

internal readonly PType returnType = default!;

public Function(global::System.Collections.Generic.IReadOnlyList<PType> parameterTypes, PType returnType) {
this.parameterTypes = global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<PType>>(parameterTypes);
this.returnType = returnType;
}

public global::System.Collections.Generic.IReadOnlyList<PType> GetParameterTypes() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(this.parameterTypes);
}

public PType GetReturnType() {
return this.returnType;
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("(", global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(this.parameterTypes), (value0) => global::DripSharp.Runtime.JavaCompat.StringValueOf(value0)), global::DripSharp.Runtime.JavaCompat.Joining(", "))), ") -> "), this.returnType);
}
}

public sealed partial class Union : global::DripSharp.Brine.PType
{
internal readonly global::System.Collections.Generic.IList<PType> elementTypes = default!;

public Union(global::System.Collections.Generic.IReadOnlyList<PType> elementTypes) {
this.elementTypes = global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<PType>>(elementTypes);
}

public global::System.Collections.Generic.IReadOnlyList<PType> GetElementTypes() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<PType>>(this.elementTypes);
}

public override string ToString() {
return global::DripSharp.Runtime.JavaCompat.Collect(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.Stream(this.elementTypes), (value0) => global::DripSharp.Runtime.JavaCompat.StringValueOf(value0)), global::DripSharp.Runtime.JavaCompat.Joining(" | "));
}
}

public sealed partial class TypeVariable : global::DripSharp.Brine.PType
{
internal readonly global::DripSharp.Brine.TypeParameter typeParameter = default!;

public TypeVariable(global::DripSharp.Brine.TypeParameter typeParameter) {
this.typeParameter = typeParameter;
}

public string GetName() {
return this.typeParameter.GetName();
}

public global::DripSharp.Brine.TypeParameter GetTypeParameter() {
return this.typeParameter;
}

public override string ToString() {
return this.typeParameter.GetName();
}
}

private sealed class Anonymous_29_7 : PType
{
public Anonymous_29_7() {

}

internal static readonly long serialVersionUID = 0L;

public override string ToString() {
return "unknown";
}
}

private sealed class Anonymous_40_7 : PType
{
public Anonymous_40_7() {

}

internal static readonly long serialVersionUID = 0L;

public override string ToString() {
return "nothing";
}
}

private sealed class Anonymous_51_7 : PType
{
public Anonymous_51_7() {

}

internal static readonly long serialVersionUID = 0L;

public override string ToString() {
return "module";
}
}
}
