// <auto-generated />
// Mechanically translated from: org/pkl/core/SecurityManagers.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine;

public sealed partial class SecurityManagers
{
internal static readonly global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> defaultAllowedModules = global::DripSharp.Runtime.JavaCompat.ListOf<global::System.Text.RegularExpressions.Regex>(global::DripSharp.Runtime.JavaCompat.CompileRegex("repl:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("file:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("jar:file:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("jar:nested:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("modulepath:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("https:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("pkl:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("package:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("projectpackage:"));

internal static readonly global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> defaultAllowedResources = global::DripSharp.Runtime.JavaCompat.ListOf<global::System.Text.RegularExpressions.Regex>(global::DripSharp.Runtime.JavaCompat.CompileRegex("prop:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("env:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("file:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("modulepath:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("package:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("projectpackage:"), global::DripSharp.Runtime.JavaCompat.CompileRegex("https:"));

internal static readonly global::System.Func<global::System.Uri, int> defaultTrustLevels = SecurityManagers.GetDefaultTrustLevel;

private static int GetDefaultTrustLevel(global::System.Uri uri) {
return ((global::System.Func<int>)(() => { switch (global::DripSharp.Runtime.JavaCompat.UriScheme(uri)!) {
case var __case_82_12_0 when global::System.Object.Equals(__case_82_12_0, "repl"):
return 40;
case var __case_83_12_0 when global::System.Object.Equals(__case_83_12_0, "file"):
return ((global::DripSharp.Runtime.JavaCompat.UriHost(uri)! == default!) ? 30 : 10);
case var __case_84_12_0 when global::System.Object.Equals(__case_84_12_0, "jar"):
{
if (global::DripSharp.Runtime.JavaCompat.StringStartsWith(global::DripSharp.Runtime.JavaCompat.UriSchemeSpecificPart(uri)!, "nested:")) {
return 20;
} else {
return SecurityManagers.GetDefaultTrustLevel(global::DripSharp.Runtime.JavaCompat.CreateUri(global::DripSharp.Runtime.JavaCompat.UriToString(uri).Substring(4)));
}
}
case var __case_93_12_0 when global::System.Object.Equals(__case_93_12_0, "modulepath"):
return 20;
case var __case_94_12_0 when global::System.Object.Equals(__case_94_12_0, "pkl"):
return 0;
default:
return 10;
} }))();
}

internal static readonly global::DripSharp.Brine.SecurityManager defaultManager = new Standard(SecurityManagers.defaultAllowedModules, SecurityManagers.defaultAllowedResources, SecurityManagers.defaultTrustLevels, (string?)default!);

public static global::DripSharp.Brine.SecurityManager CreateStandard(global::System.Collections.Generic.IReadOnlyList<global::System.Text.RegularExpressions.Regex> allowedModules, global::System.Collections.Generic.IReadOnlyList<global::System.Text.RegularExpressions.Regex> allowedResources, global::System.Func<global::System.Uri, int> trustLevels, string? rootDir) {
return new Standard(global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex>>(global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex>>(allowedModules)), global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex>>(global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex>>(allowedResources)), trustLevels, rootDir!);
}

public static StandardBuilder CreateStandardBuilder() {
return new StandardBuilder();
}

internal partial class Standard : global::DripSharp.Brine.SecurityManager
{
public virtual string? ResolveSecurePath(global::System.Uri uri) {
return ((global::DripSharp.Brine.SecurityManager)this).ResolveSecurePath(uri, false)!;
}

internal readonly global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> allowedModules = default!;

internal readonly global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> allowedResources = default!;

internal readonly global::System.Func<global::System.Uri, int> trustLevels = default!;

internal readonly string? rootDir = default!;

internal Standard(global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> allowedModules, global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> allowedResources, global::System.Func<global::System.Uri, int> trustLevels, string? rootDir) {
this.allowedModules = allowedModules;
this.allowedResources = allowedResources;
this.trustLevels = trustLevels;
this.rootDir = this.NormalizePath(rootDir!)!;
}

public virtual void CheckResolveModule(global::System.Uri uri) {
this.CheckRead(uri, this.allowedModules, false);
}

public virtual void CheckResolveResource(global::System.Uri resource) {
this.CheckRead(resource, this.allowedResources, true);
}

public virtual void CheckReadResource(global::System.Uri uri) {
this.CheckRead(uri, this.allowedResources, true);
}

public virtual void CheckImportModule(global::System.Uri importingModule, global::System.Uri importedModule) {
var importingTrustLevel = (this.trustLevels)(importingModule);
var importedTrustLevel = (this.trustLevels)(importedModule);
if ((importingTrustLevel < importedTrustLevel)) {
var message = global::DripSharp.Brine.Util.ErrorMessages.Create("insufficientModuleTrustLevel", importedModule, importingModule);
throw new global::DripSharp.Brine.SecurityManagerException(message);
}
}

public virtual string? ResolveSecurePath(global::System.Uri uri, bool isResource) {
if (((((this.rootDir! == default!) || !uri.IsAbsoluteUri) || !(global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.Runtime.JavaCompat.UriScheme(uri)!, "file"))) || ((global::DripSharp.Runtime.JavaCompat.UriAuthority(uri)! != default!) && !((global::DripSharp.Runtime.JavaCompat.UriAuthority(uri)!.Length == 0))))) {
return default!;
}
var path = global::DripSharp.Runtime.JavaCompat.PathOfUri(uri);
var realPath = global::DripSharp.Runtime.JavaCompat.RealPath(path);
if (!(global::DripSharp.Runtime.JavaCompat.PathStartsWith(realPath, this.rootDir!))) {
var errorMessageKey = (isResource ? "resourcePastRootDir" : "modulePastRootDir");
var message = global::DripSharp.Brine.Util.ErrorMessages.Create(errorMessageKey, uri, this.rootDir!);
throw new global::DripSharp.Brine.SecurityManagerException(message);
}
return realPath;
}

internal string? NormalizePath(string? path) {
if ((path! == default!)) {
return default!;
}
try {
if (global::DripSharp.Runtime.JavaCompat.Exists(path!)) {
return global::DripSharp.Runtime.JavaCompat.RealPath(path!);
}
return global::System.IO.Path.GetFullPath(path!);
} catch (global::System.IO.IOException e) {
throw global::DripSharp.Runtime.JavaCompat.NewIOException(e);
}
}

internal void CheckRead(global::System.Uri uri, global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> allowedPatterns, bool isResource) {
foreach (var pattern in allowedPatterns) {
if (global::DripSharp.Runtime.JavaCompat.RegexMatcher(pattern, global::DripSharp.Runtime.JavaCompat.UriToString(uri)).LookingAt()) {
this.CheckIsUnderRootDir(uri, isResource);
return;
}
}
var messageKey = (isResource ? "resourceNotInAllowList" : "moduleNotInAllowList");
var message = global::DripSharp.Brine.Util.ErrorMessages.Create(messageKey, uri);
throw new global::DripSharp.Brine.SecurityManagerException(message);
}

internal void CheckIsUnderRootDir(global::System.Uri uri, bool isResource) {
var checkUri = (global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.Runtime.JavaCompat.UriScheme(uri)!, "jar") ? global::DripSharp.Brine.Util.IoUtils.CreateUri(global::DripSharp.Runtime.JavaCompat.UriSchemeSpecificPart(uri)!) : uri);
if (!checkUri.IsAbsoluteUri) {
throw new global::DripSharp.Runtime.JavaAssertionError(global::DripSharp.Runtime.JavaCompat.Concat("Expected absolute URI but got: ", checkUri));
}
if (((this.rootDir! == default!) || !(global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.Runtime.JavaCompat.UriScheme(checkUri)!, "file")))) {
return;
}
var path = global::DripSharp.Runtime.JavaCompat.PathOfUri(checkUri);
if (((global::DripSharp.Runtime.JavaCompat.UriAuthority(checkUri)! != default!) && !((global::DripSharp.Runtime.JavaCompat.UriAuthority(checkUri)!.Length == 0)))) {
this.DoCheckIsUnderRootDir(global::DripSharp.Runtime.JavaCompat.NormalizePath(path), uri, isResource);
}
if (global::DripSharp.Runtime.JavaCompat.Exists(path)) {
try {
path = global::DripSharp.Runtime.JavaCompat.RealPath(path);
} catch (global::System.IO.IOException e) {
throw global::DripSharp.Runtime.JavaCompat.NewIOException(e);
}
} else {
path = global::DripSharp.Runtime.JavaCompat.NormalizePath(path);
}
this.DoCheckIsUnderRootDir(path, uri, isResource);
}

internal void DoCheckIsUnderRootDir(string path, global::System.Uri uri, bool isResource) {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.rootDir! != default!));
if (!(global::DripSharp.Runtime.JavaCompat.PathStartsWith(path, this.rootDir!))) {
var errorMessageKey = (isResource ? "resourcePastRootDir" : "modulePastRootDir");
var message = global::DripSharp.Brine.Util.ErrorMessages.Create(errorMessageKey, uri, this.rootDir!);
throw new global::DripSharp.Brine.SecurityManagerException(message);
}
}
}

public partial class StandardBuilder : global::DripSharp.Brine.SecurityManagerBuilder<global::DripSharp.Brine.SecurityManagers.StandardBuilder>
{
internal readonly global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> allowedModules = new global::System.Collections.Generic.List<global::System.Text.RegularExpressions.Regex>();

internal readonly global::System.Collections.Generic.IList<global::System.Text.RegularExpressions.Regex> allowedResources = new global::System.Collections.Generic.List<global::System.Text.RegularExpressions.Regex>();

internal string? rootDir = default!;

internal StandardBuilder() {}

public virtual StandardBuilder AddAllowedModule(global::System.Text.RegularExpressions.Regex pattern) {
global::DripSharp.Runtime.JavaCompat.Add(this.allowedModules, pattern);
return this;
}

public virtual StandardBuilder AddAllowedModules(global::System.Collections.Generic.IReadOnlyCollection<global::System.Text.RegularExpressions.Regex> patterns) {
global::DripSharp.Runtime.JavaCompat.AddAll(this.allowedModules, global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.ICollection<global::System.Text.RegularExpressions.Regex>>(patterns));
return this;
}

public virtual StandardBuilder SetAllowedModules(global::System.Collections.Generic.IReadOnlyCollection<global::System.Text.RegularExpressions.Regex> patterns) {
(this.allowedModules).Clear();
global::DripSharp.Runtime.JavaCompat.AddAll(this.allowedModules, global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.ICollection<global::System.Text.RegularExpressions.Regex>>(patterns));
return this;
}

public virtual global::System.Collections.Generic.IReadOnlyList<global::System.Text.RegularExpressions.Regex> GetAllowedModules() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::System.Text.RegularExpressions.Regex>>(this.allowedModules);
}

public virtual StandardBuilder AddAllowedResource(global::System.Text.RegularExpressions.Regex pattern) {
global::DripSharp.Runtime.JavaCompat.Add(this.allowedResources, pattern);
return this;
}

public virtual StandardBuilder AddAllowedResources(global::System.Collections.Generic.IReadOnlyCollection<global::System.Text.RegularExpressions.Regex> patterns) {
global::DripSharp.Runtime.JavaCompat.AddAll(this.allowedResources, global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.ICollection<global::System.Text.RegularExpressions.Regex>>(patterns));
return this;
}

public virtual StandardBuilder SetAllowedResources(global::System.Collections.Generic.IReadOnlyCollection<global::System.Text.RegularExpressions.Regex> patterns) {
(this.allowedResources).Clear();
global::DripSharp.Runtime.JavaCompat.AddAll(this.allowedResources, global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.ICollection<global::System.Text.RegularExpressions.Regex>>(patterns));
return this;
}

public virtual global::System.Collections.Generic.IReadOnlyList<global::System.Text.RegularExpressions.Regex> GetAllowedResources() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::System.Text.RegularExpressions.Regex>>(this.allowedResources);
}

public virtual StandardBuilder SetRootDir(string? rootDir) {
this.rootDir = rootDir!;
return this;
}

public virtual string? GetRootDir() {
return this.rootDir!;
}

public virtual global::DripSharp.Brine.SecurityManager Build() {
if ((global::DripSharp.Runtime.JavaCompat.ListIsEmpty(this.allowedResources) && global::DripSharp.Runtime.JavaCompat.ListIsEmpty(this.allowedModules))) {
throw new global::System.InvalidOperationException("No security manager set.");
}
return new Standard(this.allowedModules, this.allowedResources, SecurityManagers.defaultTrustLevels, this.rootDir!);
}
}
}
