// <auto-generated />
// Mechanically translated from: org/pkl/core/TypeAlias.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine;

public sealed partial class TypeAlias : global::DripSharp.Brine.Member, global::DripSharp.Brine.Value
{
private readonly string moduleName = default!;

private readonly string qualifiedName = default!;

private readonly global::System.Collections.Generic.IList<global::DripSharp.Brine.TypeParameter> typeParameters = default!;

private readonly global::DripSharp.Brine.PClass moduleClass = default!;

private global::DripSharp.Brine.PType aliasedType = default!;

public TypeAlias(string? docComment, global::DripSharp.Brine.Member.SourceLocation sourceLocation, global::System.Collections.Generic.IReadOnlySet<global::DripSharp.Brine.Modifier> modifiers, global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.PObject> annotations, string simpleName, string moduleName, string qualifiedName, global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.TypeParameter> typeParameters, global::DripSharp.Brine.PClass moduleClass) : base(docComment!, sourceLocation, global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlySet<global::DripSharp.Brine.Modifier>>(modifiers), global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.PObject>>(annotations), simpleName) {

this.moduleName = moduleName;
this.qualifiedName = qualifiedName;
this.typeParameters = global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IList<global::DripSharp.Brine.TypeParameter>>(typeParameters);
this.moduleClass = moduleClass;
}

public void InitAliasedType(global::DripSharp.Brine.PType type) {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.aliasedType == default!));
this.aliasedType = type;
}

public override string GetModuleName() {
return this.moduleName;
}

public string GetQualifiedName() {
return this.qualifiedName;
}

public string GetDisplayName() {
return (global::DripSharp.Runtime.JavaCompat.Equals(this.moduleName, "pkl.base") ? this.GetSimpleName() : this.qualifiedName);
}

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.TypeParameter> GetTypeParameters() {
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.TypeParameter>>(this.typeParameters);
}

public global::DripSharp.Brine.PClass GetModuleClass() {
return this.moduleClass;
}

public global::DripSharp.Brine.PType GetAliasedType() {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.aliasedType != default!));
return this.aliasedType;
}

public void Accept(global::DripSharp.Brine.ValueVisitor visitor) {
((global::DripSharp.Brine.ValueVisitor)(visitor)).VisitTypeAlias(this);
}

public T Accept<T>(global::DripSharp.Brine.ValueConverter<T> converter) {
return converter.ConvertTypeAlias(this);
}

public global::DripSharp.Brine.PClassInfo<object> GetClassInfo() {
return global::DripSharp.Brine.Runtime.PklRuntimeBridge.PClassInfoAsObject(global::DripSharp.Brine.PClassInfo<object>.TypeAlias);
}

public override string ToString() {
return this.GetDisplayName();
}
}
