// <auto-generated />
// Mechanically translated from: org/pkl/core/util/yaml/YamlEmitter.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Util.Yaml;

internal abstract partial class YamlEmitter
{
private static readonly global::DripSharp.Brine.Util.Yaml.YamlEscaper escaper = new global::DripSharp.Brine.Util.Yaml.YamlEscaper();

protected internal readonly global::System.Text.StringBuilder builder = default!;

protected internal readonly string indent = default!;

protected internal YamlEmitter(global::System.Text.StringBuilder builder, string indent) {
this.builder = builder;
this.indent = indent;
}

public static YamlEmitter Create(global::System.Text.StringBuilder builder, string mode, string indent) {
return ((global::System.Func<YamlEmitter>)(() => { switch (mode) {
case var __case_38_12_0 when global::System.Object.Equals(__case_38_12_0, "compat"):
return new global::DripSharp.Brine.Util.Yaml.YamlCompatEmitter(builder, indent);
case var __case_39_12_0 when global::System.Object.Equals(__case_39_12_0, "1.1"):
return new global::DripSharp.Brine.Util.Yaml.Yaml11Emitter(builder, indent);
case var __case_40_12_0 when global::System.Object.Equals(__case_40_12_0, "1.2"):
return new global::DripSharp.Brine.Util.Yaml.Yaml12Emitter(builder, indent);
default:
throw new global::System.ArgumentException(mode);
} }))();
}

public virtual void Emit(string str, global::System.Text.StringBuilder currIndent, bool isKey) {
if (this.IsReservedWord(str)) {
this.EmitSingleQuotedString(str, -1);
return;
}
var length = str.Length;
var needsEscaping = false;
var needsQuoting = false;
var hasNonNumberChar = false;
var newlineIndex = -1;
var colonIndex = -1;
var singleQuoteIndex = -1;
var first = str[0];
switch (first) {
case var __case_61_12_0 when __case_61_12_0 == '\n':
newlineIndex = 0;
break;
case var __case_64_12_0 when __case_64_12_0 == '\'':
needsQuoting = true;
singleQuoteIndex = 0;
break;
case var __case_68_12_0 when __case_68_12_0 == '!':
case var __case_69_12_0 when __case_69_12_0 == '%':
case var __case_70_12_0 when __case_70_12_0 == '&':
case var __case_71_12_0 when __case_71_12_0 == '*':
case var __case_72_12_0 when __case_72_12_0 == '{':
case var __case_73_12_0 when __case_73_12_0 == '}':
case var __case_74_12_0 when __case_74_12_0 == '[':
case var __case_75_12_0 when __case_75_12_0 == ']':
case var __case_76_12_0 when __case_76_12_0 == ',':
case var __case_77_12_0 when __case_77_12_0 == '#':
case var __case_78_12_0 when __case_78_12_0 == '|':
case var __case_79_12_0 when __case_79_12_0 == '>':
case var __case_80_12_0 when __case_80_12_0 == '@':
case var __case_81_12_0 when __case_81_12_0 == '`':
case var __case_82_12_0 when __case_82_12_0 == '"':
case var __case_83_12_0 when __case_83_12_0 == ' ':
needsQuoting = true;
break;
case var __case_86_12_0 when __case_86_12_0 == '-':
case var __case_87_12_0 when __case_87_12_0 == ':':
case var __case_88_12_0 when __case_88_12_0 == '?':
needsQuoting = ((length == 1) || ((int)(str[1]) == (int)(' ')));
break;
case var __case_90_12_0 when __case_90_12_0 == '0':
case var __case_91_12_0 when __case_91_12_0 == '1':
case var __case_92_12_0 when __case_92_12_0 == '2':
case var __case_93_12_0 when __case_93_12_0 == '3':
case var __case_94_12_0 when __case_94_12_0 == '4':
case var __case_95_12_0 when __case_95_12_0 == '5':
case var __case_96_12_0 when __case_96_12_0 == '6':
case var __case_97_12_0 when __case_97_12_0 == '7':
case var __case_98_12_0 when __case_98_12_0 == '8':
case var __case_99_12_0 when __case_99_12_0 == '9':
case var __case_100_12_0 when __case_100_12_0 == '+':
case var __case_101_12_0 when __case_101_12_0 == '.':
case var __case_102_12_0 when __case_102_12_0 == 'o':
break;
default:
needsEscaping = ((int)(first) < 32);
hasNonNumberChar = true;
break;
}
for (int i = 1; (i < length); i++) {
var ch = str[i];
switch (ch) {
case var __case_112_14_0 when __case_112_14_0 == '\n':
{
if ((newlineIndex == -1)) {
newlineIndex = i;
}
}
break;
case var __case_117_14_0 when __case_117_14_0 == '\'':
{
hasNonNumberChar = true;
if ((singleQuoteIndex == -1)) {
singleQuoteIndex = i;
}
}
break;
case var __case_123_14_0 when __case_123_14_0 == ' ':
{
needsQuoting = (needsQuoting || (i == (length - 1)));
hasNonNumberChar = true;
}
break;
case var __case_127_14_0 when __case_127_14_0 == '[':
case var __case_127_19_1 when __case_127_19_1 == ']':
case var __case_127_24_2 when __case_127_24_2 == '{':
case var __case_127_29_3 when __case_127_29_3 == '}':
case var __case_127_34_4 when __case_127_34_4 == ',':
{
needsQuoting = (needsQuoting || isKey);
hasNonNumberChar = true;
}
break;
case var __case_131_14_0 when __case_131_14_0 == '#':
{
needsQuoting = (needsQuoting || ((int)(str[(i - 1)]) == (int)(' ')));
hasNonNumberChar = true;
}
break;
case var __case_135_14_0 when __case_135_14_0 == ':':
{
if ((colonIndex == -1)) {
colonIndex = i;
}
needsQuoting = ((needsQuoting || (i == (length - 1))) || (((i + 1) < length) && ((int)(str[(i + 1)]) == (int)(' '))));
}
break;
case var __case_143_14_0 when __case_143_14_0 == '0':
case var __case_144_13_1 when __case_144_13_1 == '1':
case var __case_145_13_2 when __case_145_13_2 == '2':
case var __case_146_13_3 when __case_146_13_3 == '3':
case var __case_147_13_4 when __case_147_13_4 == '4':
case var __case_148_13_5 when __case_148_13_5 == '5':
case var __case_149_13_6 when __case_149_13_6 == '6':
case var __case_150_13_7 when __case_150_13_7 == '7':
case var __case_151_13_8 when __case_151_13_8 == '8':
case var __case_152_13_9 when __case_152_13_9 == '9':
case var __case_153_13_10 when __case_153_13_10 == 'A':
case var __case_154_13_11 when __case_154_13_11 == 'B':
case var __case_155_13_12 when __case_155_13_12 == 'C':
case var __case_156_13_13 when __case_156_13_13 == 'D':
case var __case_157_13_14 when __case_157_13_14 == 'E':
case var __case_158_13_15 when __case_158_13_15 == 'F':
case var __case_159_13_16 when __case_159_13_16 == 'a':
case var __case_160_13_17 when __case_160_13_17 == 'b':
case var __case_161_13_18 when __case_161_13_18 == 'c':
case var __case_162_13_19 when __case_162_13_19 == 'd':
case var __case_163_13_20 when __case_163_13_20 == 'e':
case var __case_164_13_21 when __case_164_13_21 == 'f':
case var __case_165_13_22 when __case_165_13_22 == '+':
case var __case_166_13_23 when __case_166_13_23 == '-':
case var __case_167_13_24 when __case_167_13_24 == '_':
case var __case_168_13_25 when __case_168_13_25 == '.':
case var __case_169_13_26 when __case_169_13_26 == 'o':
case var __case_170_13_27 when __case_170_13_27 == 'x':
{}
break;
default:
{
needsEscaping = (needsEscaping || ((int)(ch) < 32));
hasNonNumberChar = true;
}
break;
}
}
var pos = this.builder.Length;
if (needsEscaping) {
this.EmitDoubleQuotedString(str);
} else {
if ((newlineIndex != -1)) {
this.EmitMultilineString(str, newlineIndex, currIndent);
} else {
if ((needsQuoting || (!hasNonNumberChar && this.IsNumber(str, colonIndex)))) {
this.EmitSingleQuotedString(str, singleQuoteIndex);
} else {
this.builder.Append(str);
}
}
}
if ((isKey && (((this.builder.Length - pos) > 1024) || (!needsEscaping && (newlineIndex != -1))))) {
this.builder.Insert(pos, "? ").Append('\n').Append(currIndent.ToString());
}
}

public void Emit(long value) {
global::DripSharp.Runtime.JavaCompat.StringBuilderAppendInvariant(this.builder, value);
}

public void Emit(double value) {
this.builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf((double.IsNaN(value) ? (object)(".NaN") : ((value == double.PositiveInfinity) ? (object)(".Inf") : ((value == double.NegativeInfinity) ? (object)("-.Inf") : (object)(value))))));
}

public void Emit(bool value) {
global::DripSharp.Runtime.JavaCompat.StringBuilderAppendInvariant(this.builder, value);
}

public void Emit(sbyte[] value, global::System.Text.StringBuilder currIndent, bool isKey) {
this.builder.Append("!!binary ");
this.Emit(global::DripSharp.Runtime.JavaBase64.GetEncoder().EncodeToString(value), currIndent, isKey);
}

public void EmitNull() {
this.builder.Append("null");
}

protected internal abstract bool IsNumber(string str, int colonIndex);

protected internal abstract bool IsReservedWord(string str);

protected internal static bool IsReserved11Word(string str) {
if ((str.Length > 5)) {
return false;
}
return ((global::System.Func<bool>)(() => { switch (str) {
case var __case_237_12_0 when global::System.Object.Equals(__case_237_12_0, ""):
case var __case_238_11_1 when global::System.Object.Equals(__case_238_11_1, "~"):
case var __case_239_11_2 when global::System.Object.Equals(__case_239_11_2, "null"):
case var __case_240_11_3 when global::System.Object.Equals(__case_240_11_3, "Null"):
case var __case_241_11_4 when global::System.Object.Equals(__case_241_11_4, "NULL"):
case var __case_242_11_5 when global::System.Object.Equals(__case_242_11_5, ".nan"):
case var __case_243_11_6 when global::System.Object.Equals(__case_243_11_6, ".NaN"):
case var __case_244_11_7 when global::System.Object.Equals(__case_244_11_7, ".NAN"):
case var __case_245_11_8 when global::System.Object.Equals(__case_245_11_8, ".inf"):
case var __case_246_11_9 when global::System.Object.Equals(__case_246_11_9, ".Inf"):
case var __case_247_11_10 when global::System.Object.Equals(__case_247_11_10, ".INF"):
case var __case_248_11_11 when global::System.Object.Equals(__case_248_11_11, "+.inf"):
case var __case_249_11_12 when global::System.Object.Equals(__case_249_11_12, "+.Inf"):
case var __case_250_11_13 when global::System.Object.Equals(__case_250_11_13, "+.INF"):
case var __case_251_11_14 when global::System.Object.Equals(__case_251_11_14, "-.inf"):
case var __case_252_11_15 when global::System.Object.Equals(__case_252_11_15, "-.Inf"):
case var __case_253_11_16 when global::System.Object.Equals(__case_253_11_16, "-.INF"):
case var __case_254_11_17 when global::System.Object.Equals(__case_254_11_17, "true"):
case var __case_255_11_18 when global::System.Object.Equals(__case_255_11_18, "True"):
case var __case_256_11_19 when global::System.Object.Equals(__case_256_11_19, "TRUE"):
case var __case_257_11_20 when global::System.Object.Equals(__case_257_11_20, "false"):
case var __case_258_11_21 when global::System.Object.Equals(__case_258_11_21, "False"):
case var __case_259_11_22 when global::System.Object.Equals(__case_259_11_22, "FALSE"):
case var __case_260_11_23 when global::System.Object.Equals(__case_260_11_23, "on"):
case var __case_261_11_24 when global::System.Object.Equals(__case_261_11_24, "On"):
case var __case_262_11_25 when global::System.Object.Equals(__case_262_11_25, "ON"):
case var __case_263_11_26 when global::System.Object.Equals(__case_263_11_26, "off"):
case var __case_264_11_27 when global::System.Object.Equals(__case_264_11_27, "Off"):
case var __case_265_11_28 when global::System.Object.Equals(__case_265_11_28, "OFF"):
case var __case_266_11_29 when global::System.Object.Equals(__case_266_11_29, "y"):
case var __case_267_11_30 when global::System.Object.Equals(__case_267_11_30, "Y"):
case var __case_268_11_31 when global::System.Object.Equals(__case_268_11_31, "yes"):
case var __case_269_11_32 when global::System.Object.Equals(__case_269_11_32, "Yes"):
case var __case_270_11_33 when global::System.Object.Equals(__case_270_11_33, "YES"):
case var __case_271_11_34 when global::System.Object.Equals(__case_271_11_34, "n"):
case var __case_272_11_35 when global::System.Object.Equals(__case_272_11_35, "N"):
case var __case_273_11_36 when global::System.Object.Equals(__case_273_11_36, "no"):
case var __case_274_11_37 when global::System.Object.Equals(__case_274_11_37, "No"):
case var __case_275_11_38 when global::System.Object.Equals(__case_275_11_38, "NO"):
return true;
default:
return false;
} }))();
}

private void EmitMultilineString(string str, int newlineIndex, global::System.Text.StringBuilder currIndent) {
currIndent.Append(this.indent);
this.builder.Append('|');
if (((int)(str[0]) == (int)(' '))) {
this.builder.Append(this.indent.Length);
}
var length = str.Length;
if (((int)(str[(length - 1)]) == (int)('\n'))) {
if (((length == 1) || ((int)(str[(length - 2)]) == (int)('\n')))) {
this.builder.Append('+');
}
} else {
this.builder.Append('-');
}
this.builder.Append('\n');
var start = 0;
for (int i = newlineIndex; (i < length); i++) {
var ch = str[i];
if (((int)(ch) != (int)('\n'))) {
continue;
}
if ((i == start)) {
this.builder.Append('\n');
} else {
this.builder.Append(currIndent.ToString()).Append(str, start, ((i + 1) - start));
}
start = (i + 1);
}
if ((start < length)) {
this.builder.Append(currIndent.ToString()).Append(str, start, (length - start));
}
currIndent.Length = (currIndent.Length - this.indent.Length);
}

private void EmitDoubleQuotedString(string str) {
this.builder.Append('"');
YamlEmitter.escaper.Escape(str, this.builder);
this.builder.Append('"');
}

private void EmitSingleQuotedString(string str, int singleQuoteIndex) {
this.builder.Append('\'');
if ((singleQuoteIndex == -1)) {
this.builder.Append(str);
} else {
var start = 0;
var length = str.Length;
for (var i = singleQuoteIndex; (i < length); i++) {
if (((int)(str[i]) == (int)('\''))) {
this.builder.Append(str, start, (i - start)).Append("''");
start = (i + 1);
}
}
if ((start < length)) {
this.builder.Append(str, start, (length - start));
}
}
this.builder.Append('\'');
}
}
