// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/unary/LogicalNotNode.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Unary;

[global::DripSharp.Brine.Runtime.Truffle.api.nodes.NodeInfo("!")]
internal abstract partial class LogicalNotNode : global::DripSharp.Brine.Ast.Expression.Unary.UnaryExpressionNode
{
protected internal LogicalNotNode(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection) : base(sourceSection) {

}

protected internal virtual bool Eval(bool operand) {
return !operand;
}
}
