// <auto-generated />
// Mechanically translated from: org/pkl/core/ast/expression/unary/UnaryMinusNodeGen.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Ast.Expression.Unary;

internal sealed partial class UnaryMinusNodeGen : global::DripSharp.Brine.Ast.Expression.Unary.UnaryMinusNode
{
private global::DripSharp.Brine.Ast.ExpressionNode operandNode_ = default!;

private int state_0_;

private UnaryMinusNodeGen(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Ast.ExpressionNode operandNode) : base(sourceSection) {

this.operandNode_ = operandNode;
}

private bool FallbackGuard_(int state_0, object operandNodeValue) {
if ((!(((state_0 & 1) != 0)) && (operandNodeValue is long))) {
return false;
}
if ((!(((state_0 & 2) != 0)) && (operandNodeValue is double))) {
return false;
}
if ((!(((state_0 & 4) != 0)) && (operandNodeValue is global::DripSharp.Brine.Runtime.VmDuration))) {
return false;
}
if ((!(((state_0 & 8) != 0)) && (operandNodeValue is global::DripSharp.Brine.Runtime.VmDataSize))) {
return false;
}
return true;
}

public override object ExecuteGeneric(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if ((((state_0 & 30) == 0) && (state_0 != 0))) {
return this.ExecuteGeneric_long0(state_0, frameValue);
} else {
if ((((state_0 & 29) == 0) && (state_0 != 0))) {
return this.ExecuteGeneric_double1(state_0, frameValue);
} else {
return this.ExecuteGeneric_generic2(state_0, frameValue);
}
}
}

private object ExecuteGeneric_long0(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
long operandNodeValue_;
try {
operandNodeValue_ = this.operandNode_.ExecuteInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(ex.GetResult());
}
global::DripSharp.Runtime.JavaCompat.Assert(() => ((state_0 & 1) != 0));
return this.Eval(operandNodeValue_);
}

private object ExecuteGeneric_double1(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
double operandNodeValue_;
try {
operandNodeValue_ = this.operandNode_.ExecuteFloat(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(ex.GetResult());
}
global::DripSharp.Runtime.JavaCompat.Assert(() => ((state_0 & 2) != 0));
return this.Eval(operandNodeValue_);
}

private object ExecuteGeneric_generic2(int state_0__, global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = state_0__;
object operandNodeValue_ = this.operandNode_.ExecuteGeneric(frameValue);
if ((state_0 != 0)) {
if ((((state_0 & 1) != 0) && (operandNodeValue_ is long))) {
long operandNodeValue____114_22 = (long)(operandNodeValue_);
return this.Eval(operandNodeValue____114_22);
}
if ((((state_0 & 2) != 0) && (operandNodeValue_ is double))) {
double operandNodeValue____118_24 = (double)(operandNodeValue_);
return this.Eval(operandNodeValue____118_24);
}
if ((((state_0 & 4) != 0) && (operandNodeValue_ is global::DripSharp.Brine.Runtime.VmDuration))) {
global::DripSharp.Brine.Runtime.VmDuration operandNodeValue____122_28 = (global::DripSharp.Brine.Runtime.VmDuration)(operandNodeValue_!);
return this.Eval(operandNodeValue____122_28);
}
if ((((state_0 & 8) != 0) && (operandNodeValue_ is global::DripSharp.Brine.Runtime.VmDataSize))) {
global::DripSharp.Brine.Runtime.VmDataSize operandNodeValue____126_28 = (global::DripSharp.Brine.Runtime.VmDataSize)(operandNodeValue_!);
return this.Eval(operandNodeValue____126_28);
}
if (((state_0 & 16) != 0)) {
if (this.FallbackGuard_(state_0, operandNodeValue_)) {
return this.Fallback(operandNodeValue_);
}
}
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return this.ExecuteAndSpecialize(operandNodeValue_);
}

public override double ExecuteFloat(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 16) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectDouble(this.ExecuteGeneric(frameValue));
}
double operandNodeValue_;
try {
operandNodeValue_ = this.operandNode_.ExecuteFloat(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectDouble(this.ExecuteAndSpecialize(ex.GetResult()));
}
if (((state_0 & 2) != 0)) {
return this.Eval(operandNodeValue_);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectDouble(this.ExecuteAndSpecialize(operandNodeValue_));
}

public override long ExecuteInt(global::DripSharp.Brine.Runtime.Truffle.api.frame.VirtualFrame frameValue) {
int state_0 = this.state_0_;
if (((state_0 & 16) != 0)) {
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteGeneric(frameValue));
}
long operandNodeValue_;
try {
operandNodeValue_ = this.operandNode_.ExecuteInt(frameValue);
} catch (global::DripSharp.Brine.Runtime.Truffle.api.nodes.UnexpectedResultException ex) {
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteAndSpecialize(ex.GetResult()));
}
if (((state_0 & 1) != 0)) {
return this.Eval(operandNodeValue_);
}
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreterAndInvalidate();
return global::DripSharp.Brine.Runtime.VmTypesGen.ExpectLong(this.ExecuteAndSpecialize(operandNodeValue_));
}

private object ExecuteAndSpecialize(object operandNodeValue) {
int state_0 = this.state_0_;
if ((operandNodeValue is long)) {
long operandNodeValue___182_18 = (long)(operandNodeValue);
state_0 = (state_0 | 1);
this.state_0_ = state_0;
return this.Eval(operandNodeValue___182_18);
}
if ((operandNodeValue is double)) {
double operandNodeValue___188_20 = (double)(operandNodeValue);
state_0 = (state_0 | 2);
this.state_0_ = state_0;
return this.Eval(operandNodeValue___188_20);
}
if ((operandNodeValue is global::DripSharp.Brine.Runtime.VmDuration)) {
global::DripSharp.Brine.Runtime.VmDuration operandNodeValue___194_24 = (global::DripSharp.Brine.Runtime.VmDuration)(operandNodeValue!);
state_0 = (state_0 | 4);
this.state_0_ = state_0;
return this.Eval(operandNodeValue___194_24);
}
if ((operandNodeValue is global::DripSharp.Brine.Runtime.VmDataSize)) {
global::DripSharp.Brine.Runtime.VmDataSize operandNodeValue___200_24 = (global::DripSharp.Brine.Runtime.VmDataSize)(operandNodeValue!);
state_0 = (state_0 | 8);
this.state_0_ = state_0;
return this.Eval(operandNodeValue___200_24);
}
state_0 = (state_0 | 16);
this.state_0_ = state_0;
return this.Fallback(operandNodeValue);
}

public static global::DripSharp.Brine.Ast.Expression.Unary.UnaryMinusNode Create(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::DripSharp.Brine.Ast.ExpressionNode operandNode) {
return new UnaryMinusNodeGen(sourceSection, operandNode);
}
}
