// <auto-generated />
// Mechanically translated from: org/pkl/core/externalreader/ExternalModuleResolver.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Externalreader;

public partial interface ExternalModuleResolver
{
internal static ExternalModuleResolver Of(global::DripSharp.Brine.Messaging.MessageTransport transport, long evaluatorId) {
return new global::DripSharp.Brine.Externalreader.ExternalModuleResolverImpl(transport, evaluatorId);
}

public string ResolveModule(global::DripSharp.Brine.SecurityManager securityManager, global::System.Uri uri);

public bool HasElement(global::DripSharp.Brine.SecurityManager securityManager, global::System.Uri elementUri);

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Module.PathElement> ListElements(global::DripSharp.Brine.SecurityManager securityManager, global::System.Uri baseUri);
}
