// <auto-generated />
// Mechanically translated from: org/pkl/core/externalreader/ExternalResourceResolverImpl.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Externalreader;

internal sealed partial class ExternalResourceResolverImpl : global::DripSharp.Brine.Externalreader.ExternalResourceResolver
{
public global::DripSharp.Brine.Externalreader.ExternalResourceResolver Of(global::DripSharp.Brine.Messaging.MessageTransport transport, long evaluatorId) {
return new ExternalResourceResolverImpl(transport, evaluatorId);
}

private readonly global::DripSharp.Brine.Messaging.MessageTransport transport = default!;

private readonly long evaluatorId;

private readonly global::System.Collections.Generic.IDictionary<global::System.Uri, global::DripSharp.Runtime.JavaFuture<sbyte[]>> readResponses = new global::System.Collections.Concurrent.ConcurrentDictionary<global::System.Uri, global::DripSharp.Runtime.JavaFuture<sbyte[]>>();

private readonly global::System.Collections.Generic.IDictionary<global::System.Uri, global::DripSharp.Runtime.JavaFuture<global::System.Collections.Generic.IList<global::DripSharp.Brine.Module.PathElement>>> listResponses = new global::System.Collections.Concurrent.ConcurrentDictionary<global::System.Uri, global::DripSharp.Runtime.JavaFuture<global::System.Collections.Generic.IList<global::DripSharp.Brine.Module.PathElement>>>();

private readonly global::DripSharp.Runtime.JavaRandom requestIdGenerator = new global::DripSharp.Runtime.JavaRandom();

internal ExternalResourceResolverImpl(global::DripSharp.Brine.Messaging.MessageTransport transport, long evaluatorId) {
this.transport = transport;
this.evaluatorId = evaluatorId;
}

public object? Read(global::System.Uri uri) {
var result = this.DoRead(uri);
return (((result == default!) ? global::DripSharp.Brine.Runtime.JavaOptional<object>.Empty() : global::DripSharp.Brine.Runtime.JavaOptional<object>.Of(new global::DripSharp.Brine.Resource.Resource(uri, result)))).OrElse(default!);
}

public bool HasElement(global::DripSharp.Brine.SecurityManager securityManager, global::System.Uri elementUri) {
securityManager.CheckResolveResource(elementUri);
try {
return (this.DoRead(elementUri) != default!);
} catch (global::System.IO.IOException) {
return false;
}
}

public global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Module.PathElement> ListElements(global::DripSharp.Brine.SecurityManager securityManager, global::System.Uri baseUri) {
securityManager.CheckResolveResource(baseUri);
return global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyList<global::DripSharp.Brine.Module.PathElement>>(this.DoListElements(baseUri));
}

public global::System.Collections.Generic.IList<global::DripSharp.Brine.Module.PathElement> DoListElements(global::System.Uri baseUri) {
return global::DripSharp.Brine.Messaging.MessageTransports.ResolveFuture<global::System.Collections.Generic.IList<global::DripSharp.Brine.Module.PathElement>>(global::DripSharp.Runtime.JavaCompat.ComputeIfAbsent(this.listResponses, baseUri, (uri) => {
var future = new global::DripSharp.Runtime.JavaFuture<global::System.Collections.Generic.IList<global::DripSharp.Brine.Module.PathElement>>();
var request = new global::DripSharp.Brine.Messaging.Messages.ListResourcesRequest(this.requestIdGenerator.NextLong(), this.evaluatorId, uri);
try {
this.transport.Send(request, (response) => {
if ((response is global::DripSharp.Brine.Messaging.Messages.ListResourcesResponse resp)) {
if ((resp.Error! != default!)) {
future.CompleteExceptionally(new global::System.IO.IOException(resp.Error!));
} else {
future.Complete(global::DripSharp.Runtime.JavaCompat.RequireNonNullElseGet(resp.PathElements!, () => global::DripSharp.Runtime.JavaCompat.ListOf<global::DripSharp.Brine.Module.PathElement>()));
}
} else {
future.CompleteExceptionally(new global::DripSharp.Brine.Messaging.ProtocolException("unexpected response"));
}
});
} catch (global::System.Exception e) when (e is global::DripSharp.Brine.Messaging.ProtocolException or global::System.IO.IOException) {
future.CompleteExceptionally(e);
}
return future;
}));
}

public sbyte[] DoRead(global::System.Uri baseUri) {
return global::DripSharp.Brine.Messaging.MessageTransports.ResolveFuture<sbyte[]>(global::DripSharp.Runtime.JavaCompat.ComputeIfAbsent(this.readResponses, baseUri, (uri) => {
var future = new global::DripSharp.Runtime.JavaFuture<sbyte[]>();
var request = new global::DripSharp.Brine.Messaging.Messages.ReadResourceRequest(this.requestIdGenerator.NextLong(), this.evaluatorId, uri);
try {
this.transport.Send(request, (response) => {
if ((response is global::DripSharp.Brine.Messaging.Messages.ReadResourceResponse resp)) {
if ((resp.Error! != default!)) {
future.CompleteExceptionally(new global::System.IO.IOException(resp.Error!));
} else {
future.Complete(resp.Contents);
}
} else {
future.CompleteExceptionally(new global::DripSharp.Brine.Messaging.ProtocolException("unexpected response"));
}
});
} catch (global::System.Exception e) when (e is global::DripSharp.Brine.Messaging.ProtocolException or global::System.IO.IOException) {
future.CompleteExceptionally(e);
}
return future;
}));
}
}
