// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/BaseModule.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal sealed partial class BaseModule : global::DripSharp.Brine.Runtime.StdLibModule
{
internal static readonly global::DripSharp.Brine.Runtime.VmTyped instance = global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyModule();

static BaseModule() {
global::DripSharp.Brine.Runtime.StdLibModule.LoadModule(global::DripSharp.Brine.PClassInfo<object>.pklBaseUri, BaseModule.instance);
}

public static global::DripSharp.Brine.Runtime.VmTyped GetModule() {
return BaseModule.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetAnyClass() {
return AnyClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetTypedClass() {
return TypedClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetNullClass() {
return NullClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetNumberClass() {
return NumberClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetIntClass() {
return IntClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFloatClass() {
return FloatClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetStringClass() {
return StringClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetBooleanClass() {
return BooleanClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetDurationClass() {
return DurationClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetDataSizeClass() {
return DataSizeClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetBytesClass() {
return BytesClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetIntSeqClass() {
return IntSeqClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetCollectionClass() {
return CollectionClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetListClass() {
return ListClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetSetClass() {
return SetClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetListingClass() {
return ListingClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetMapClass() {
return MapClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetMappingClass() {
return MappingClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetDynamicClass() {
return DynamicClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetRenderDirectiveClass() {
return RenderDirectiveClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetModuleClass() {
return ModuleClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetClassClass() {
return ClassClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetTypeAliasClass() {
return TypeAliasClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetRegexClass() {
return RegexClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetRegexMatchClass() {
return RegexMatchClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunctionClass() {
return FunctionClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunctionNClass(int paramCount) {
return ((global::System.Func<global::DripSharp.Brine.Runtime.VmClass>)(() => { switch (paramCount) {
case var __case_144_12_0 when __case_144_12_0 == 0:
return BaseModule.GetFunction0Class();
case var __case_145_12_0 when __case_145_12_0 == 1:
return BaseModule.GetFunction1Class();
case var __case_146_12_0 when __case_146_12_0 == 2:
return BaseModule.GetFunction2Class();
case var __case_147_12_0 when __case_147_12_0 == 3:
return BaseModule.GetFunction3Class();
case var __case_148_12_0 when __case_148_12_0 == 4:
return BaseModule.GetFunction4Class();
case var __case_149_12_0 when __case_149_12_0 == 5:
return BaseModule.GetFunction5Class();
default:
{
global::DripSharp.Brine.Runtime.Truffle.api.CompilerDirectives.TransferToInterpreter();
throw new global::System.ArgumentException(global::DripSharp.Runtime.JavaCompat.JavaStringFormat("Class `Function%d` does not exist.", paramCount));
}
} }))();
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunction0Class() {
return Function0Class.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunction1Class() {
return Function1Class.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunction2Class() {
return Function2Class.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunction3Class() {
return Function3Class.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunction4Class() {
return Function4Class.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetFunction5Class() {
return Function5Class.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetPairClass() {
return PairClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetVarArgsClass() {
return VarArgsClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetModuleInfoClass() {
return ModuleInfoClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetAnnotationClass() {
return AnnotationClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetConvertPropertyClass() {
return ConvertPropertyClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetDeprecatedClass() {
return DeprecatedClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmClass GetResourceClass() {
return ResourceClass.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetNonNullTypeAlias() {
return NonNullTypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetInt8TypeAlias() {
return Int8TypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetInt16TypeAlias() {
return Int16TypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetInt32TypeAlias() {
return Int32TypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetMixinTypeAlias() {
return MixinTypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetUIntTypeAlias() {
return UIntTypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetUInt8TypeAlias() {
return UInt8TypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetUInt16TypeAlias() {
return UInt16TypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetUInt32TypeAlias() {
return UInt32TypeAlias.instance;
}

public static global::DripSharp.Brine.Runtime.VmTypeAlias GetCharTypeAlias() {
return CharTypeAlias.instance;
}

internal sealed partial class AnyClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Any");
}

internal sealed partial class TypedClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Typed");
}

internal sealed partial class NullClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Null");
}

internal sealed partial class NumberClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Number");
}

internal sealed partial class IntClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Int");
}

internal sealed partial class FloatClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Float");
}

internal sealed partial class StringClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("String");
}

internal sealed partial class BooleanClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Boolean");
}

internal sealed partial class DurationClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Duration");
}

internal sealed partial class DataSizeClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("DataSize");
}

internal sealed partial class BytesClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Bytes");
}

internal sealed partial class IntSeqClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("IntSeq");
}

internal sealed partial class CollectionClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Collection");
}

internal sealed partial class ListClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("List");
}

internal sealed partial class SetClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Set");
}

internal sealed partial class ListingClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Listing");
}

internal sealed partial class MapClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Map");
}

internal sealed partial class MappingClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Mapping");
}

internal sealed partial class DynamicClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Dynamic");
}

internal sealed partial class ModuleClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Module");
}

internal sealed partial class ClassClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Class");
}

internal sealed partial class TypeAliasClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("TypeAlias");
}

internal sealed partial class RegexClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Regex");
}

internal sealed partial class RegexMatchClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("RegexMatch");
}

internal sealed partial class RenderDirectiveClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("RenderDirective");
}

internal sealed partial class PairClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Pair");
}

internal sealed partial class VarArgsClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("VarArgs");
}

internal sealed partial class ModuleInfoClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("ModuleInfo");
}

internal sealed partial class AnnotationClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Annotation");
}

internal sealed partial class ConvertPropertyClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("ConvertProperty");
}

internal sealed partial class DeprecatedClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Deprecated");
}

internal sealed partial class ResourceClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Resource");
}

internal sealed partial class FunctionClass
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Function");
}

internal sealed partial class Function0Class
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Function0");
}

internal sealed partial class Function1Class
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Function1");
}

internal sealed partial class Function2Class
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Function2");
}

internal sealed partial class Function3Class
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Function3");
}

internal sealed partial class Function4Class
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Function4");
}

internal sealed partial class Function5Class
{
internal static readonly global::DripSharp.Brine.Runtime.VmClass instance = BaseModule.LoadClass("Function5");
}

internal sealed partial class NonNullTypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("NonNull");
}

internal sealed partial class Int8TypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("Int8");
}

internal sealed partial class Int16TypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("Int16");
}

internal sealed partial class Int32TypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("Int32");
}

internal sealed partial class UIntTypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("UInt");
}

internal sealed partial class UInt8TypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("UInt8");
}

internal sealed partial class UInt16TypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("UInt16");
}

internal sealed partial class UInt32TypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("UInt32");
}

internal sealed partial class CharTypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("Char");
}

internal sealed partial class MixinTypeAlias
{
internal static readonly global::DripSharp.Brine.Runtime.VmTypeAlias instance = BaseModule.LoadTypeAlias("Mixin");
}

private static global::DripSharp.Brine.Runtime.VmClass LoadClass(string className) {
var theModule = BaseModule.GetModule();
return (global::DripSharp.Brine.Runtime.VmClass)(global::DripSharp.Brine.Runtime.VmUtils.ReadMember(theModule, global::DripSharp.Brine.Runtime.Identifier.Get(className))!);
}

private static global::DripSharp.Brine.Runtime.VmTypeAlias LoadTypeAlias(string typeAliasName) {
var theModule = BaseModule.GetModule();
return (global::DripSharp.Brine.Runtime.VmTypeAlias)(global::DripSharp.Brine.Runtime.VmUtils.ReadMember(theModule, global::DripSharp.Brine.Runtime.Identifier.Get(typeAliasName))!);
}
}
