// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/Iterators.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal sealed partial class Iterators
{
public static global::DripSharp.Runtime.JavaIterator<T> EmptyTruffleIterator<T>() {
return global::DripSharp.Runtime.JavaCompat.EmptyJavaIterator<T>();
}

private static readonly global::DripSharp.Runtime.JavaIterator<object> EMPTY_TRUFFLE_ITERATOR = new Anonymous_33_7();

internal sealed partial class TruffleIterator<T> : global::DripSharp.Runtime.JavaIterator<T>
{
internal readonly global::DripSharp.Runtime.JavaIterator<T> @delegate = default!;

public TruffleIterator(global::System.Collections.Generic.IEnumerable<T> iterable) {
this.@delegate = global::DripSharp.Runtime.JavaCompat.Iterator(iterable);
}

public bool HasNext() {
return (this.@delegate).HasNext();
}

public T Next() {
return (this.@delegate).Next()!;
}

public void Remove() {
throw new global::System.NotSupportedException("remove");
}

public void ForEachRemaining(global::System.Action<T> action) {
throw new global::System.NotSupportedException("forEachRemaining");
}
}

internal sealed partial class ReverseTruffleIterator<T> : global::DripSharp.Runtime.JavaIterator<T>
{
internal readonly global::DripSharp.Runtime.JavaListIterator<T> @delegate = default!;

public ReverseTruffleIterator(global::System.Collections.Generic.IEnumerable<T> list) {
this.@delegate = global::DripSharp.Runtime.JavaCompat.ListIterator(list, global::DripSharp.Runtime.JavaCompat.CollectionCount(list));
}

public bool HasNext() {
return this.@delegate.HasPrevious();
}

public T Next() {
return this.@delegate.Previous();
}

public void Remove() {
throw new global::System.NotSupportedException("remove");
}

public void ForEachRemaining(global::System.Action<T> action) {
throw new global::System.NotSupportedException("forEachRemaining");
}
}

private sealed class Anonymous_33_7 : global::DripSharp.Runtime.JavaIterator<object>
{
public Anonymous_33_7() {

}

public bool HasNext() {
return false;
}

public object Next() {
throw new global::System.InvalidOperationException();
}

public void Remove() {
throw new global::System.InvalidOperationException();
}

public void ForEachRemaining(global::System.Action action) {
throw new global::System.NotSupportedException("forEachRemaining");
}
}
}
