// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/ModuleResolver.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal sealed partial class ModuleResolver
{
private readonly global::System.Collections.Generic.ICollection<global::DripSharp.Brine.Module.ModuleKeyFactory> factories = default!;

public ModuleResolver(global::System.Collections.Generic.ICollection<global::DripSharp.Brine.Module.ModuleKeyFactory> factories) {
this.factories = factories;
}

public global::DripSharp.Brine.Module.ModuleKey Resolve(global::DripSharp.Brine.ModuleSource moduleSource) {
if (!(moduleSource.GetUri()).IsAbsoluteUri) {
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().EvalError("cannotEvaluateRelativeModuleUri", moduleSource.GetUri()).Build();
}
if ((moduleSource.GetContents()! != default!)) {
if (global::DripSharp.Runtime.JavaCompat.Equals(moduleSource.GetUri(), global::DripSharp.Brine.Runtime.VmUtils.REPL_TEXT_URI)) {
return global::DripSharp.Brine.Module.ModuleKeys.CreateSynthetic(moduleSource.GetUri(), moduleSource.GetContents()!);
}
return this.ResolveCached(moduleSource.GetUri(), moduleSource.GetContents()!);
}
return this.Resolve(moduleSource.GetUri());
}

public global::DripSharp.Brine.Module.ModuleKey Resolve(global::System.Uri moduleUri) {
return this.Resolve(moduleUri, (global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node?)default!);
}

public global::DripSharp.Brine.Module.ModuleKey ResolveCached(global::System.Uri moduleUri, string text) {
var underlyingModuleKey = this.Resolve(moduleUri);
return global::DripSharp.Brine.Module.ModuleKeys.Cached(underlyingModuleKey, text);
}

public global::DripSharp.Brine.Module.ModuleKey Resolve(global::System.Uri moduleUri, global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node? importNode) {
if (!moduleUri.IsAbsoluteUri) {
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().WithOptionalLocation(importNode!).Bug("Cannot resolve relative URI `%s`.", moduleUri).Build();
}
var normalized = global::DripSharp.Runtime.JavaCompat.NormalizeUri(moduleUri);
foreach (var factory in this.factories) {
global::DripSharp.Brine.Runtime.JavaOptional<global::DripSharp.Brine.Module.ModuleKey> key;
try {
key = global::DripSharp.Brine.Runtime.JavaOptional<global::DripSharp.Brine.Module.ModuleKey>.OfNullable(factory.Create(normalized));
} catch (global::System.UriFormatException e) {
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().WithOptionalLocation(importNode!).EvalError("invalidModuleUri", moduleUri).WithHint(global::DripSharp.Runtime.JavaCompat.UriSyntaxReason(e)).Build();
} catch (global::DripSharp.Brine.Externalreader.ExternalReaderProcessException e) {
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().WithOptionalLocation(importNode!).EvalError("externalReaderFailure").WithCause(e).Build();
} catch (global::System.IO.IOException e) {
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().WithOptionalLocation(importNode!).EvalError("ioErrorLoadingModule").WithCause(e).Build();
}
if (key.IsPresent()) {
return key.Get();
}
}
throw new global::DripSharp.Brine.Runtime.VmExceptionBuilder().EvalError("noModuleLoaderRegistered", moduleUri).WithOptionalLocation(importNode!).Build();
}
}
