// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/PowerAssertions.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal partial class PowerAssertions
{
public static bool IsEnabled() {
return global::DripSharp.Brine.Runtime.VmContext.Get((global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node?)default!).GetPowerAssertionsEnabled();
}

private static readonly global::DripSharp.Brine.Runtime.VmValueRenderer vmValueRenderer = global::DripSharp.Brine.Runtime.VmValueRenderer.SingleLine(100);

private static readonly global::DripSharp.Brine.Parser.Parser parser = new global::DripSharp.Brine.Parser.Parser();

public static void Render(global::DripSharp.Brine.Util.AnsiStringBuilder @out, string indent, global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection, global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node, global::System.Collections.Generic.IList<object>> trackedValues, global::System.Action<global::DripSharp.Brine.Util.AnsiStringBuilder>? firstFrameSuffix) {
global::DripSharp.Runtime.JavaCompat.Assert(() => sourceSection.IsAvailable(), () => "Power assertions require an available source section");
@out.AppendSandboxed(() => {
var lines = PowerAssertions.Lines(sourceSection);
var layerEntries = PowerAssertions.GetLayerEntries(trackedValues, sourceSection);
var indentation = ((global::DripSharp.Runtime.JavaCompat.CollectionCount(lines) == 1) ? 0 : global::DripSharp.Runtime.JavaCompat.CollectionMin(global::DripSharp.Runtime.JavaCompat.ToListValues(global::DripSharp.Runtime.JavaCompat.Map(global::DripSharp.Runtime.JavaCompat.DropValues(global::DripSharp.Runtime.JavaCompat.Stream(lines), (long)(1)), (it) => PowerAssertions.LeadingWhitespace(it.GetCharacters())))));
var sourceLines = PowerAssertions.Lines(sourceSection);
var renderedMarkers = false;
for (var i = 0; (i < global::DripSharp.Runtime.JavaCompat.CollectionCount(sourceLines)); i++) {
if (renderedMarkers) {
@out.Append("\n\n");
}
var line = global::DripSharp.Runtime.JavaCompat.ListGet(sourceLines, i);
var offset = ((i == 0) ? (line.GetStartColumn() - 1) : indentation);
renderedMarkers = PowerAssertions.RenderLine(@out, indent, line, layerEntries, offset, ((i == 0) ? firstFrameSuffix! : (global::System.Action<global::DripSharp.Brine.Util.AnsiStringBuilder>)(default!)));
}
});
}

private static bool IsInForGeneratorOrLambdaOrPredicate(global::DripSharp.Brine.Parser.Syntax.Node myNode, global::DripSharp.Brine.Parser.Syntax.Expr rootExpr) {
var parent = myNode.Parent();
while ((parent != default!)) {
if ((parent is global::DripSharp.Brine.Parser.Syntax.Expr.FunctionLiteralExpr)) {
return !(global::DripSharp.Runtime.JavaCompat.Equals(parent, rootExpr));
}
if ((parent is global::DripSharp.Brine.Parser.Syntax.ObjectMember.MemberPredicate)) {
return true;
}
if ((parent is global::DripSharp.Brine.Parser.Syntax.ObjectMember.ForGenerator forGenerator)) {
return !(forGenerator.GetExpr().Span().Contains(myNode.Span()));
}
parent = parent.Parent();
}
return false;
}

private static bool IsLiteral(global::DripSharp.Brine.Parser.Syntax.Node parserNode) {
if (((((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.IntLiteralExpr) || (parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.FloatLiteralExpr)) || (parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.BoolLiteralExpr)) || (parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.NullLiteralExpr))) {
return true;
}
if ((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.StringLiteralExpr stringLiteralExpr)) {
return !(stringLiteralExpr.HasInterpolation());
}
return false;
}

private static bool IsLiteral(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node truffleNode, global::DripSharp.Brine.Parser.Syntax.Node parserNode) {
if (PowerAssertions.IsLiteral(parserNode)) {
return true;
}
if ((truffleNode is global::DripSharp.Brine.Ast.ConstantValueNode)) {
if ((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.UnqualifiedAccessExpr unqualifiedAccessExpr)) {
return (unqualifiedAccessExpr.GetArgumentList() != default!);
}
return true;
}
if (!((truffleNode is global::DripSharp.Brine.Ast.Expression.Member.InvokeMethodDirectNode))) {
return false;
}
var accessExpr = (global::DripSharp.Brine.Parser.Syntax.Expr.UnqualifiedAccessExpr)(parserNode!);
if (!(global::DripSharp.Runtime.JavaCompat.IsUpperCase(accessExpr.GetIdentifier().GetValue()[0]))) {
return false;
}
var argsList = accessExpr.GetArgumentList();
global::DripSharp.Runtime.JavaCompat.Assert(() => (argsList != default!));
return global::DripSharp.Runtime.JavaCompat.AllValues(global::DripSharp.Runtime.JavaCompat.Stream(argsList.GetArguments()), PowerAssertions.IsLiteral);
}

private static bool ShouldHide(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node truffleNode, global::DripSharp.Brine.Parser.Syntax.Node parserNode, object value, global::DripSharp.Brine.Parser.Syntax.Expr rootExpr) {
if (PowerAssertions.IsLiteral(truffleNode, parserNode)) {
return true;
}
if ((((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.LetExpr) || (parserNode is global::DripSharp.Brine.Parser.Syntax.StringPart.StringInterpolation)) || (parserNode is global::DripSharp.Brine.Parser.Syntax.StringPart.StringChars))) {
return true;
}
if (PowerAssertions.IsInForGeneratorOrLambdaOrPredicate(parserNode, rootExpr)) {
return true;
}
if ((value is global::DripSharp.Brine.Runtime.VmFunction)) {
return true;
}
return ((((truffleNode is global::DripSharp.Brine.Ast.Type.GetParentForTypeNode) || (truffleNode is global::DripSharp.Brine.Ast.Expression.Member.InferParentWithinMethodNode)) || (truffleNode is global::DripSharp.Brine.Ast.Expression.Member.InferParentWithinObjectMethodNode)) || (truffleNode is global::DripSharp.Brine.Ast.Expression.Member.InferParentWithinPropertyNode));
}

private static global::DripSharp.Brine.Parser.Syntax.Node? FindParserNode(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node node, global::DripSharp.Brine.Parser.Syntax.Node? parserNode, int offset) {
if (!(node.GetSourceSection().IsAvailable())) {
return default!;
}
if ((parserNode! == default!)) {
return default!;
}
var span = parserNode!.Span();
var charIndex = (span.CharIndex + offset);
var ss = node.GetSourceSection();
if (((charIndex == ss.GetCharIndex()) && (span.Length == ss.GetCharLength()))) {
return parserNode!;
}
var children = global::DripSharp.Runtime.JavaCompat.ToMutable<global::System.Collections.Generic.IEnumerable<global::DripSharp.Brine.Parser.Syntax.Node>>(parserNode!.Children());
foreach (var child in children) {
var found = PowerAssertions.FindParserNode(node, child, offset)!;
if ((found! != default!)) {
return found!;
}
}
return default!;
}

private static global::System.Collections.Generic.ICollection<LayerEntry> GetLayerEntries(global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node, global::System.Collections.Generic.IList<object>> trackedValues, global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection) {
var exprNode = PowerAssertions.parser.ParseExpressionInput(sourceSection.GetCharacters());
var ret = new global::System.Collections.Generic.HashSet<LayerEntry>();
foreach (var entry in global::DripSharp.Runtime.JavaCompat.MapEntrySet(trackedValues)) {
var truffleNode = entry.Key;
var values = entry.Value;
var parserNode = PowerAssertions.FindParserNode(truffleNode, exprNode, sourceSection.GetCharIndex())!;
if ((parserNode! == default!)) {
continue;
}
if ((global::DripSharp.Runtime.JavaCompat.CollectionCount(values) > 1)) {
continue;
}
var value = global::DripSharp.Runtime.JavaCompat.ListGet(values, 0);
if (PowerAssertions.ShouldHide(truffleNode, parserNode!, value, exprNode)) {
continue;
}
ret.Add(SourceEntry.Create(truffleNode, parserNode!, value));
}
return ret;
}

private static bool CanFit(global::DripSharp.Runtime.JavaDeque<LayerEntry> layer, LayerEntry elem) {
if (global::DripSharp.Runtime.JavaCompat.CollectionIsEmpty(layer)) {
return true;
}
var nextEntry = global::DripSharp.Runtime.JavaCompat.DequeGetFirst(layer);
return (((elem.StartColumn + elem.Length()) + 1) < nextEntry.StartColumn);
}

private static bool CanFitMarker(global::DripSharp.Runtime.JavaDeque<LayerEntry> layer, LayerEntry elem) {
if (global::DripSharp.Runtime.JavaCompat.CollectionIsEmpty(layer)) {
return true;
}
var nextEntry = global::DripSharp.Runtime.JavaCompat.DequeGetFirst(layer);
return (elem.StartColumn < nextEntry.StartColumn);
}

private static global::System.Collections.Generic.IList<global::System.Collections.Generic.ICollection<LayerEntry>> BuildLayers(global::System.Collections.Generic.ICollection<LayerEntry> layerEntries, global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection line) {
var sortedSections = global::DripSharp.Runtime.JavaCompat.ToListValues(global::DripSharp.Runtime.JavaCompat.StreamSorted(global::DripSharp.Runtime.JavaCompat.StreamFilter(global::DripSharp.Runtime.JavaCompat.Stream(layerEntries), (it) => (it.StartLine == line.GetStartLine())), global::DripSharp.Runtime.JavaCompat.ToComparison(global::DripSharp.Runtime.JavaCompat.ComparingInt<LayerEntry>((it) => -it.StartColumn))));
if ((sortedSections.Count == 0)) {
return global::System.Array.Empty<global::System.Collections.Generic.ICollection<LayerEntry>>();
}
var layers = new global::System.Collections.Generic.List<global::System.Collections.Generic.ICollection<LayerEntry>>();
global::DripSharp.Runtime.JavaCompat.Add(layers, PowerAssertions.FirstLayerMarkers(sortedSections));
while (!((sortedSections.Count == 0))) {
var layer = new global::DripSharp.Runtime.JavaDeque<LayerEntry>();
var iter = global::DripSharp.Runtime.JavaCompat.Iterator(sortedSections);
while (iter.HasNext()) {
var next = iter.Next()!;
if (PowerAssertions.CanFit(layer, next)) {
layer.AddFirst(next);
iter.Remove();
} else {
if (PowerAssertions.CanFitMarker(layer, next)) {
layer.AddFirst(((LayerEntry)(next)).ToMarker());
}
}
}
global::DripSharp.Runtime.JavaCompat.Add(layers, layer);
}
return layers;
}

private static global::System.Collections.Generic.ICollection<LayerEntry> FirstLayerMarkers(global::System.Collections.Generic.IList<LayerEntry> entries) {
var layer = new global::DripSharp.Runtime.JavaDeque<LayerEntry>();
LayerEntry prevEntry = default!;
foreach (var entry in entries) {
if (((prevEntry! != default!) && ((prevEntry!).StartColumn == entry.StartColumn))) {
continue;
}
layer.AddFirst(((LayerEntry)(entry)).ToMarker());
prevEntry = entry;
}
return layer;
}

private static global::System.Collections.Generic.IList<global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection> Lines(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection sourceSection) {
var startLine = sourceSection.GetStartLine();
var endLine = sourceSection.GetEndLine();
if ((!(sourceSection.IsAvailable()) || (startLine == endLine))) {
return global::DripSharp.Runtime.JavaCompat.ListOf<global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection>(sourceSection);
}
var result = new global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection>();
var source = sourceSection.GetSource();
var charIndex = sourceSection.GetCharIndex();
var endCharIndex = (charIndex + sourceSection.GetCharLength());
for (var lineNumber = startLine; (lineNumber <= endLine); lineNumber++) {
var lineSection = source.CreateSection(lineNumber);
var lineStartChar = lineSection.GetCharIndex();
var lineEndChar = (lineStartChar + lineSection.GetCharLength());
var sectionStartChar = global::System.Math.Max(charIndex, lineStartChar);
var sectionEndChar = global::System.Math.Min(endCharIndex, lineEndChar);
if ((sectionStartChar < sectionEndChar)) {
global::DripSharp.Runtime.JavaCompat.Add(result, source.CreateSection(sectionStartChar, (sectionEndChar - sectionStartChar)));
}
}
return result;
}

public static string TrimLeadingWhitespace(string str, int n) {
var i = 0;
while ((((i < str.Length) && (i < n)) && global::DripSharp.Runtime.JavaCompat.IsWhitespace(str[i]))) {
i++;
}
return str.Substring(i);
}

private static bool RenderLine(global::DripSharp.Brine.Util.AnsiStringBuilder @out, string indent, global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection line, global::System.Collections.Generic.ICollection<LayerEntry> layerEntries, int trimStart, global::System.Action<global::DripSharp.Brine.Util.AnsiStringBuilder>? lineSuffix) {
var layers = PowerAssertions.BuildLayers(layerEntries, line);
var content = PowerAssertions.TrimLeadingWhitespace(line.GetCharacters(), trimStart);
@out.Append(indent).Append(content);
if ((lineSuffix! != default!)) {
(lineSuffix!)(@out);
}
@out.Append('\n');
if (global::DripSharp.Runtime.JavaCompat.ListIsEmpty(layers)) {
return false;
}
for (var i = 0; (i < global::DripSharp.Runtime.JavaCompat.CollectionCount(layers)); i++) {
var layer = global::DripSharp.Runtime.JavaCompat.ListGet(layers, i);
@out.Append(indent);
var cursor = 0;
foreach (var entry in layer) {
var currentOffset = (((entry.StartColumn - 1) - trimStart) - cursor);
@out.Append(global::DripSharp.Runtime.JavaCompat.Repeat(" ", currentOffset));
entry.AppendTo(@out);
cursor += (currentOffset + entry.Length());
}
if ((i < (global::DripSharp.Runtime.JavaCompat.CollectionCount(layers) - 1))) {
@out.Append('\n');
}
}
return true;
}

private static int LeadingWhitespace(string src) {
var result = 0;
for (var i = 0; (i < src.Length); i++) {
var c = src[i];
if ((((int)(c) != (int)(' ')) && ((int)(c) != (int)('\t')))) {
break;
}
result++;
}
return result;
}

internal partial interface LayerEntry
{
public int StartLine { get; }

public int StartColumn { get; }

public int Length();

public void AppendTo(global::DripSharp.Brine.Util.AnsiStringBuilder builder);

public MarkerEntry ToMarker();
}

internal sealed partial record class SourceEntry(int StartLine, int StartColumn, string Src) : global::DripSharp.Brine.Runtime.PowerAssertions.LayerEntry
{
public MarkerEntry ToMarker() {
return new MarkerEntry(this.StartLine, this.StartColumn);
}

internal static SourceEntry Create(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node truffleNode, global::DripSharp.Brine.Parser.Syntax.Node parserNode, object value) {
var effectiveSourceSection = truffleNode.GetSourceSection().GetSource().CreateSection(SourceEntry.GetCharIndex(truffleNode, parserNode), 1);
return new SourceEntry(effectiveSourceSection.GetStartLine(), effectiveSourceSection.GetStartColumn(), PowerAssertions.vmValueRenderer.Render(value));
}

internal static int GetCharIndex(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node truffleNode, global::DripSharp.Brine.Parser.Syntax.Node parserNode) {
if ((truffleNode is global::DripSharp.Brine.Runtime.Truffle.api.instrumentation.InstrumentableNode.WrapperNode wrapperNode)) {
truffleNode = wrapperNode.GetDelegateNode();
}
var originalSource = truffleNode.GetSourceSection();
if (!(originalSource.IsAvailable())) {
return originalSource.GetCharIndex();
}
var exprText = originalSource.GetCharacters();
var skip = 0;
if ((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.BinaryOperatorExpr binaryOperatorExpr)) {
skip = (binaryOperatorExpr.GetLeft().Span().StopIndexExclusive() - (parserNode.Span()).CharIndex);
} else {
if ((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.TypeCheckExpr typeCheckExpr)) {
skip = (typeCheckExpr.GetExpr().Span().StopIndexExclusive() - (parserNode.Span()).CharIndex);
} else {
if ((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.SubscriptExpr subscriptExpr)) {
skip = (subscriptExpr.GetExpr().Span().StopIndexExclusive() - (parserNode.Span()).CharIndex);
} else {
if (((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.SuperAccessExpr) || (parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.SuperSubscriptExpr))) {
skip = "super".Length;
} else {
if ((parserNode is global::DripSharp.Brine.Parser.Syntax.Expr.QualifiedAccessExpr qualifiedAccessExpr)) {
skip = (qualifiedAccessExpr.GetExpr().Span().StopIndexExclusive() - (parserNode.Span()).CharIndex);
}
}
}
}
}
if ((skip == 0)) {
return originalSource.GetCharIndex();
}
var lexer = new global::DripSharp.Brine.Parser.Lexer(exprText.Substring(skip));
var nextToken = lexer.Next();
while (!(nextToken.IsOperator())) {
nextToken = lexer.Next();
}
var span = lexer.Span();
if (((nextToken == global::DripSharp.Brine.Parser.Token.DOT) || (nextToken == global::DripSharp.Brine.Parser.Token.QDOT))) {
return (((originalSource.GetCharIndex() + skip) + span.CharIndex) + span.Length);
}
return ((originalSource.GetCharIndex() + skip) + span.CharIndex);
}

public int Length() {
return this.Src.Length;
}

public void AppendTo(global::DripSharp.Brine.Util.AnsiStringBuilder builder) {
global::DripSharp.Brine.Util.SyntaxHighlighter.WriteTo(builder, this.Src);
}

public bool Equals(SourceEntry? other) {
if (global::System.Object.ReferenceEquals(this, other)) return true;
return other is not null &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.StartLine, other.StartLine) &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.StartColumn, other.StartColumn) &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.Src, other.Src);
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.StartLine, this.StartColumn, this.Src);
}
}

internal sealed partial record class MarkerEntry(int StartLine, int StartColumn) : global::DripSharp.Brine.Runtime.PowerAssertions.LayerEntry
{
public int Length() {
return 1;
}

public void AppendTo(global::DripSharp.Brine.Util.AnsiStringBuilder builder) {
builder.Append(global::DripSharp.Brine.Util.AnsiStringBuilder.AnsiCode.FAINT, "\u2502");
}

public MarkerEntry ToMarker() {
return this;
}

public bool Equals(MarkerEntry? other) {
if (global::System.Object.ReferenceEquals(this, other)) return true;
return other is not null &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.StartLine, other.StartLine) &&
            global::DripSharp.Runtime.JavaCompat.Equals(this.StartColumn, other.StartColumn);
}

public override int GetHashCode() {
return global::DripSharp.Runtime.JavaCompat.Hash(this.StartLine, this.StartColumn);
}
}
}
