// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/TestModule.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal sealed partial class TestModule : global::DripSharp.Brine.Runtime.StdLibModule
{
internal static readonly global::DripSharp.Brine.Runtime.VmTyped instance = global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyModule();

static TestModule() {
global::DripSharp.Brine.Runtime.StdLibModule.LoadModule(global::DripSharp.Runtime.JavaCompat.CreateUri("pkl:test"), TestModule.instance);
}

public static global::DripSharp.Brine.Runtime.VmTyped GetModule() {
return TestModule.instance;
}
}
