// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/VmExceptionBuilder.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal sealed partial class VmExceptionBuilder
{
private object? receiver = default!;

private global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.Truffle.api.CallTarget, global::DripSharp.Brine.StackFrame>? insertedStackFrames = default!;

private global::DripSharp.Brine.Runtime.VmException? wrappedException = default!;

private global::System.Action<global::DripSharp.Brine.Util.AnsiStringBuilder, bool>? hintBuilder = default!;

internal partial class MultilineValue
{
internal readonly global::System.Collections.Generic.IEnumerable<object> lines = default!;

internal MultilineValue(global::System.Collections.Generic.IEnumerable<object> lines) {
this.lines = lines;
}

public override string ToString() {
var builder = new global::System.Text.StringBuilder();
var first = true;
foreach (var value in this.lines) {
if (first) {
first = false;
} else {
builder.Append("\n");
}
builder.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(value));
}
return builder.ToString();
}
}

private string? message = default!;

private global::System.Action<global::DripSharp.Brine.Util.AnsiStringBuilder, bool>? messageBuilder = default!;

private global::System.Exception? cause = default!;

private global::DripSharp.Brine.Runtime.VmException.Kind kind = global::DripSharp.Brine.Runtime.VmException.Kind.EVAL_ERROR;

private bool isExternalMessage;

private object[]? messageArguments = new object[0];

private readonly global::System.Collections.Generic.IList<global::DripSharp.Brine.Runtime.VmException.ProgramValue> programValues = new global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.VmException.ProgramValue>();

private global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node? location = default!;

private global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection? sourceSection = default!;

private string? memberName = default!;

public VmExceptionBuilder TypeMismatch(object value, global::DripSharp.Brine.Runtime.VmClass expectedType) {
if ((value is global::DripSharp.Brine.Runtime.VmNull)) {
return this.EvalError("typeMismatchValue", expectedType, "null");
}
return this.EvalError("typeMismatch", expectedType, global::DripSharp.Brine.Runtime.VmUtils.GetClass(value)).WithProgramValue("Value", value);
}

public VmExceptionBuilder TypeMismatch(object value, global::DripSharp.Brine.Runtime.VmClass expectedType1, global::DripSharp.Brine.Runtime.VmClass expectedType2) {
if ((value is global::DripSharp.Brine.Runtime.VmNull)) {
return this.EvalError("typeMismatchValue2", expectedType1, expectedType2, "null");
}
return this.EvalError("typeMismatch2", expectedType1, expectedType2, global::DripSharp.Brine.Runtime.VmUtils.GetClass(value)).WithProgramValue("Value", value);
}

public VmExceptionBuilder UnreachableCode() {
return this.Bug("Unreachable code.");
}

public VmExceptionBuilder UndefinedValue() {
this.kind = global::DripSharp.Brine.Runtime.VmException.Kind.UNDEFINED_VALUE;
return this.WithExternalMessage("undefinedValue");
}

public VmExceptionBuilder UndefinedPropertyValue(global::DripSharp.Brine.Runtime.Identifier propertyName, object receiver) {
this.kind = global::DripSharp.Brine.Runtime.VmException.Kind.UNDEFINED_VALUE;
this.receiver = receiver;
return this.WithExternalMessage("undefinedPropertyValue", propertyName);
}

public VmExceptionBuilder CannotFindMember(global::DripSharp.Brine.Runtime.VmObjectLike receiver, object memberKey) {
if ((memberKey is global::DripSharp.Brine.Runtime.Identifier identifier)) {
return this.CannotFindProperty(receiver, identifier, true, false);
}
if ((memberKey is string @string)) {
var candidates = global::DripSharp.Brine.Runtime.KeyLookupSuggestions.ForObject(receiver, @string);
if (!(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(candidates))) {
return this.EvalError("cannotFindKeyListCandidates", new global::DripSharp.Brine.Runtime.VmException.ProgramValue("", memberKey), new MultilineValue(candidates));
}
}
return this.EvalError("cannotFindKey", new global::DripSharp.Brine.Runtime.VmException.ProgramValue("", memberKey));
}

public VmExceptionBuilder CannotFindProperty(global::DripSharp.Brine.Runtime.VmObjectLike receiver, global::DripSharp.Brine.Runtime.Identifier propertyName, bool isRead, bool isImplicitReceiver) {
var memberKinds = (isRead ? global::DripSharp.Runtime.JavaCompat.EnumSetAllOf<global::DripSharp.Brine.Runtime.MemberLookupSuggestions.Candidate.Kind>(typeof(global::DripSharp.Brine.Runtime.MemberLookupSuggestions.Candidate.Kind)) : global::DripSharp.Runtime.JavaCompat.EnumSetOf<global::DripSharp.Brine.Runtime.MemberLookupSuggestions.Candidate.Kind>(global::DripSharp.Brine.Runtime.MemberLookupSuggestions.Candidate.Kind.PROPERTY));
var candidates = new global::DripSharp.Brine.Runtime.MemberLookupSuggestions(receiver, propertyName, -1, memberKinds).Find(isImplicitReceiver);
if (global::DripSharp.Runtime.JavaCompat.ListIsEmpty(candidates)) {
if (isImplicitReceiver) {
this.EvalError("cannotFindPropertyInScope", propertyName);
} else {
if (receiver.IsModuleObject()) {
this.EvalError("cannotFindPropertyInModule", propertyName, global::DripSharp.Brine.Runtime.VmUtils.GetModuleInfo(receiver).GetModuleName(), new MultilineValue(this.CollectPropertyNames(receiver, isRead)));
} else {
var propertyNames = this.CollectPropertyNames(receiver, isRead);
this.EvalError("cannotFindPropertyInObject", propertyName, receiver.GetVmClass(), (global::DripSharp.Runtime.JavaCompat.ListIsEmpty(propertyNames) ? (object)("(none)") : (object)(new MultilineValue(propertyNames))));
}
}
} else {
if (isImplicitReceiver) {
this.EvalError("cannotFindPropertyInScopeListCandidates", propertyName, new MultilineValue(candidates));
} else {
if (receiver.IsModuleObject()) {
this.EvalError("cannotFindPropertyInModuleListCandidates", propertyName, global::DripSharp.Brine.Runtime.VmUtils.GetModuleInfo(receiver).GetModuleName(), new MultilineValue(candidates));
} else {
this.EvalError("cannotFindPropertyInObjectListCandidates", propertyName, receiver.GetVmClass(), new MultilineValue(candidates));
}
}
}
return this;
}

public VmExceptionBuilder CannotFindMethod(global::DripSharp.Brine.Runtime.VmObjectLike receiver, global::DripSharp.Brine.Runtime.Identifier methodName, int arity, bool isImplicitReceiver) {
var candidates = new global::DripSharp.Brine.Runtime.MemberLookupSuggestions(receiver, methodName, arity, global::DripSharp.Runtime.JavaCompat.EnumSetAllOf<global::DripSharp.Brine.Runtime.MemberLookupSuggestions.Candidate.Kind>(typeof(global::DripSharp.Brine.Runtime.MemberLookupSuggestions.Candidate.Kind))).Find(isImplicitReceiver);
if (global::DripSharp.Runtime.JavaCompat.ListIsEmpty(candidates)) {
if (isImplicitReceiver) {
this.EvalError("cannotFindMethodInScope", methodName);
} else {
if (receiver.IsModuleObject()) {
this.EvalError("cannotFindMethodInModule", methodName, global::DripSharp.Brine.Runtime.VmUtils.GetModuleInfo(receiver).GetModuleName(), new MultilineValue(this.CollectMethodNames(receiver.GetVmClass())));
} else {
this.EvalError("cannotFindMethodInClass", methodName, receiver.GetVmClass(), new MultilineValue(this.CollectMethodNames(receiver.GetVmClass())));
}
}
} else {
if (isImplicitReceiver) {
this.EvalError("cannotFindMethodInScopeListCandidates", methodName, new MultilineValue(candidates));
} else {
if (receiver.IsModuleObject()) {
this.EvalError("cannotFindMethodInModuleListCandidates", methodName, global::DripSharp.Brine.Runtime.VmUtils.GetModuleInfo(receiver).GetModuleName(), new MultilineValue(candidates));
} else {
this.EvalError("cannotFindMethodInClassListCandidates", methodName, receiver.GetVmClass(), new MultilineValue(candidates));
}
}
}
return this;
}

public VmExceptionBuilder CannotFindKey(global::DripSharp.Brine.Runtime.VmMap map, object key) {
if ((key is string @string)) {
var candidates = global::DripSharp.Brine.Runtime.KeyLookupSuggestions.ForMap(map, @string);
if (!(global::DripSharp.Runtime.JavaCompat.ListIsEmpty(candidates))) {
return this.EvalError("cannotFindKeyListCandidates", new global::DripSharp.Brine.Runtime.VmException.ProgramValue("", key), new MultilineValue(candidates));
}
}
return this.EvalError("cannotFindKey", new global::DripSharp.Brine.Runtime.VmException.ProgramValue("", key));
}

public VmExceptionBuilder Bug(string? message, params object[]? args) {
this.kind = global::DripSharp.Brine.Runtime.VmException.Kind.BUG;
return this.WithMessage(message!, args!);
}

private VmExceptionBuilder WithMessage(string? message, params object[]? args) {
this.message = message!;
this.messageArguments = args!;
this.isExternalMessage = false;
return this;
}

private VmExceptionBuilder WithExternalMessage(string message, params object[]? args) {
this.message = message;
this.messageArguments = args!;
this.isExternalMessage = true;
return this;
}

public VmExceptionBuilder EvalError(string messageKey, params object[]? args) {
return this.WithExternalMessage(messageKey, args!);
}

public VmExceptionBuilder AdhocEvalError(string? message, params object[]? args) {
return this.WithMessage(message!, args!);
}

public VmExceptionBuilder WithMessageBuilder(global::System.Action<global::DripSharp.Brine.Util.AnsiStringBuilder, bool> messageBuilder) {
this.messageBuilder = messageBuilder;
return this;
}

public VmExceptionBuilder WithProgramValue(string name, object value) {
global::DripSharp.Runtime.JavaCompat.Add(this.programValues, new global::DripSharp.Brine.Runtime.VmException.ProgramValue(name, value));
return this;
}

public VmExceptionBuilder WithLocation(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node location) {
this.location = location;
this.WithSourceSection(location.GetSourceSection());
return this;
}

public VmExceptionBuilder WithOptionalLocation(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node? location) {
if ((location! != default!)) {
this.WithLocation(location!);
}
return this;
}

public VmExceptionBuilder WithSourceSection(global::DripSharp.Brine.Runtime.Truffle.api.source.SourceSection? sourceSection) {
this.sourceSection = sourceSection!;
return this;
}

public VmExceptionBuilder WithMemberName(string memberName) {
this.memberName = memberName;
return this;
}

public VmExceptionBuilder WithCause(global::System.Exception? cause) {
this.cause = cause!;
return this;
}

public VmExceptionBuilder WithHint(string? hint) {
if ((hint! != default!)) {
this.hintBuilder = (builder, ignored) => builder.Append(hint!);
}
return this;
}

public VmExceptionBuilder WithHintBuilder(global::System.Action<global::DripSharp.Brine.Util.AnsiStringBuilder, bool>? hintBuilder) {
this.hintBuilder = hintBuilder!;
return this;
}

public VmExceptionBuilder Wrapping(global::DripSharp.Brine.Runtime.VmException nestedException) {
this.wrappedException = nestedException;
this.kind = global::DripSharp.Brine.Runtime.VmException.Kind.WRAPPED;
return this;
}

public VmExceptionBuilder WithInsertedStackFrames(global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.Truffle.api.CallTarget, global::DripSharp.Brine.StackFrame> insertedStackFrames) {
this.insertedStackFrames = insertedStackFrames;
return this;
}

public global::DripSharp.Brine.Runtime.VmException Build() {
if (((this.message! != default!) && (this.messageBuilder! != default!))) {
throw new global::System.InvalidOperationException("Both message and messageBuilder are set");
}
if (((this.message! == default!) && (this.messageBuilder! == default!))) {
if ((this.cause! == default!)) {
throw new global::System.InvalidOperationException("No message set.");
}
var causeMessage = global::DripSharp.Runtime.JavaCompat.ExceptionMessage(this.cause!);
this.message = ((causeMessage == default!) ? "None (cause has no message)" : causeMessage);
}
var effectiveInsertedStackFrames = ((this.insertedStackFrames! == default!) ? (global::System.Collections.Generic.IDictionary<global::DripSharp.Brine.Runtime.Truffle.api.CallTarget, global::DripSharp.Brine.StackFrame>)(global::DripSharp.Runtime.JavaCompat.NewJavaDictionary<global::DripSharp.Brine.Runtime.Truffle.api.CallTarget, global::DripSharp.Brine.StackFrame>()) : this.insertedStackFrames!);
return ((global::System.Func<global::DripSharp.Brine.Runtime.VmException>)(() => { switch (global::DripSharp.Runtime.JavaCompat.EnumOrdinal(this.kind)) {
case 0:
return new global::DripSharp.Brine.Runtime.VmEvalException(this.message!, this.cause!, this.isExternalMessage, this.messageArguments!, this.messageBuilder!, this.programValues, this.location!, this.sourceSection!, this.memberName!, this.hintBuilder!, effectiveInsertedStackFrames);
case 1:
return new global::DripSharp.Brine.Runtime.VmUndefinedValueException(this.message!, this.cause!, this.isExternalMessage, this.messageArguments!, this.messageBuilder!, this.programValues, this.location!, this.sourceSection!, this.memberName!, this.hintBuilder!, this.receiver!, effectiveInsertedStackFrames);
case 3:
return new global::DripSharp.Brine.Runtime.VmBugException(this.message!, this.cause!, this.isExternalMessage, this.messageArguments!, this.messageBuilder!, this.programValues, this.location!, this.sourceSection!, this.memberName!, this.hintBuilder!, effectiveInsertedStackFrames);
case 2:
{
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.wrappedException! != default!));
return new global::DripSharp.Brine.Runtime.VmWrappedEvalException(this.message!, this.cause!, this.isExternalMessage, this.messageArguments!, this.messageBuilder!, this.programValues, this.location!, this.sourceSection!, this.memberName!, this.hintBuilder!, effectiveInsertedStackFrames, this.wrappedException!);
}
} throw new global::System.InvalidOperationException(); }))();
}

private global::System.Collections.Generic.IList<global::DripSharp.Brine.Runtime.Identifier> CollectPropertyNames(global::DripSharp.Brine.Runtime.VmObjectLike @object, bool isRead) {
var result = new global::System.Collections.Generic.HashSet<global::DripSharp.Brine.Runtime.Identifier>();
@object.IterateMembers((key, member) => {
if ((member.IsProp() && (isRead || !(member.IsExternal())))) {
result.Add(member.GetName());
}
return true;
});
return global::DripSharp.Runtime.JavaCompat.ToListValues(global::DripSharp.Runtime.JavaCompat.StreamSorted(global::DripSharp.Runtime.JavaCompat.Stream(result)));
}

private global::System.Collections.Generic.IList<global::DripSharp.Brine.Runtime.Identifier> CollectMethodNames(global::DripSharp.Brine.Runtime.VmClass clazz) {
var result = new global::System.Collections.Generic.List<global::DripSharp.Brine.Runtime.Identifier>();
global::DripSharp.Runtime.JavaCompat.ForEach(clazz.GetMethods(), (method) => global::DripSharp.Runtime.JavaCompat.Add(result, method.GetName()));
global::DripSharp.Runtime.JavaCompat.SortList(result, global::DripSharp.Runtime.JavaCompat.ToComparison(global::DripSharp.Runtime.JavaCompat.NaturalOrder<global::DripSharp.Brine.Runtime.Identifier>()));
return result;
}
}
