// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/VmLanguage.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal sealed partial class VmLanguage : global::DripSharp.Brine.Runtime.Truffle.api.TruffleLanguage<global::DripSharp.Brine.Runtime.VmContext>
{
public VmLanguage() { this.localContext = this.locals.CreateContextThreadLocal<VmLocalContext>((ignoredCtx, ignoredThread) => new VmLocalContext()); }

public static readonly string MIME_TYPE = "application/x-pkl";

private static readonly global::DripSharp.Brine.Runtime.Truffle.api.TruffleLanguage.LanguageReference<VmLanguage> REFERENCE = global::DripSharp.Brine.Runtime.Truffle.api.TruffleLanguage.LanguageReference<VmLanguage>.Create(typeof(VmLanguage));

public static VmLanguage Get(global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node? node) {
return VmLanguage.REFERENCE.Get(node!);
}

public readonly global::DripSharp.Brine.Runtime.Truffle.api.ContextThreadLocal<global::DripSharp.Brine.Runtime.VmLocalContext> localContext = default!;

protected internal override global::DripSharp.Brine.Runtime.VmContext CreateContext(global::DripSharp.Brine.Runtime.Truffle.api.TruffleLanguage.Env env) {
return new global::DripSharp.Brine.Runtime.VmContext(this, env);
}

protected internal override global::DripSharp.Brine.Runtime.Truffle.api.CallTarget Parse(global::DripSharp.Brine.Runtime.Truffle.api.TruffleLanguage.ParsingRequest request) {
throw new global::System.NotSupportedException("parse");
}

public global::DripSharp.Brine.Runtime.VmTyped LoadModule(global::DripSharp.Brine.Module.ModuleKey moduleKey) {
var context = global::DripSharp.Brine.Runtime.VmContext.Get((global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node?)default!);
return context.GetModuleCache().GetOrLoad(moduleKey, context.GetSecurityManager(), context.GetModuleResolver(), global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyModule, this.InitializeModule, (global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node?)default!);
}

public global::DripSharp.Brine.Runtime.VmTyped LoadModule(global::DripSharp.Brine.Module.ModuleKey moduleKey, global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node? importNode) {
var context = global::DripSharp.Brine.Runtime.VmContext.Get((global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node?)default!);
return context.GetModuleCache().GetOrLoad(moduleKey, context.GetSecurityManager(), context.GetModuleResolver(), global::DripSharp.Brine.Runtime.VmUtils.CreateEmptyModule, this.InitializeModule, importNode!);
}

internal void InitializeModule(global::DripSharp.Brine.Module.ModuleKey moduleKey, global::DripSharp.Brine.Module.ResolvedModuleKey resolvedModuleKey, global::DripSharp.Brine.Runtime.ModuleResolver moduleResolver, global::DripSharp.Brine.Runtime.Truffle.api.source.Source source, global::DripSharp.Brine.Runtime.VmTyped emptyModule, global::DripSharp.Brine.Runtime.Truffle.api.nodes.Node? importNode) {
var parser = new global::DripSharp.Brine.Parser.Parser();
global::DripSharp.Brine.Parser.Syntax.Module moduleContext;
var sourceStr = source.GetCharacters();
try {
moduleContext = parser.ParseModule(sourceStr);
} catch (global::DripSharp.Brine.Parser.ParserError e) {
var moduleName = global::DripSharp.Brine.Util.IoUtils.InferModuleName(moduleKey);
global::DripSharp.Brine.Runtime.MinPklVersionChecker.Check(moduleName, e.GetPartialParseResult(), importNode!, sourceStr);
throw global::DripSharp.Brine.Runtime.VmUtils.ToVmException(e, source, moduleName);
}
var builder = global::DripSharp.Brine.Ast.Builder.AstBuilder.Create(source, this, moduleContext, moduleKey, resolvedModuleKey, moduleResolver);
var moduleNode = ((global::DripSharp.Brine.Ast.PklRootNode)(builder.VisitModule(moduleContext)));
moduleNode.GetCallTarget().Call(emptyModule, emptyModule);
global::DripSharp.Brine.Runtime.MinPklVersionChecker.Check(emptyModule, importNode!);
}
}
