// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/VmObjectLike.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal abstract partial class VmObjectLike : global::DripSharp.Brine.Runtime.VmValue
{
protected internal readonly global::DripSharp.Brine.Runtime.Truffle.api.frame.MaterializedFrame enclosingFrame = default!;

protected internal object? extraStorage = default!;

protected internal VmObjectLike(global::DripSharp.Brine.Runtime.Truffle.api.frame.MaterializedFrame enclosingFrame) {
this.enclosingFrame = enclosingFrame;
}

public global::DripSharp.Brine.Runtime.Truffle.api.frame.MaterializedFrame GetEnclosingFrame() {
return this.enclosingFrame;
}

public object? GetEnclosingReceiver() {
return global::DripSharp.Brine.Runtime.VmUtils.GetReceiverOrNull(this.enclosingFrame)!;
}

public VmObjectLike? GetEnclosingOwner() {
return global::DripSharp.Brine.Runtime.VmUtils.GetOwnerOrNull(this.enclosingFrame)!;
}

public virtual object GetExtraStorage() {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.extraStorage! != default!));
return this.extraStorage!;
}

public void SetExtraStorage(object? extraStorage) {
this.extraStorage = extraStorage!;
}

public virtual bool IsModuleObject() {
return false;
}

public abstract VmObjectLike? GetParent();

public abstract bool HasMember(object key);

public abstract global::DripSharp.Brine.Ast.Member.ObjectMember? GetMember(object key);

public abstract global::DripSharp.Brine.Runtime.GraalCollections.UnmodifiableEconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember> GetMembers();

public virtual bool IsParseTimeInvisibleScope() {
return false;
}

public abstract object? GetCachedValue(object key);

public abstract void SetCachedValue(object key, object value);

public abstract bool HasCachedValue(object key);

public abstract bool IterateMemberValues(MemberValueConsumer consumer);

public abstract bool ForceAndIterateMemberValues(ForcedMemberValueConsumer consumer);

public abstract bool IterateAlreadyForcedMemberValues(ForcedMemberValueConsumer consumer);

public abstract bool IterateMembers(global::System.Func<object, global::DripSharp.Brine.Ast.Member.ObjectMember, bool> consumer);

public abstract void Force(bool allowUndefinedValues, bool recurse);

public abstract override object Export();

internal delegate bool MemberValueConsumer(object key, global::DripSharp.Brine.Ast.Member.ObjectMember member, object? value);

internal delegate bool ForcedMemberValueConsumer(object key, global::DripSharp.Brine.Ast.Member.ObjectMember member, object value);
}
