// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/VmTyped.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal sealed partial class VmTyped : global::DripSharp.Brine.Runtime.VmObject
{
private global::DripSharp.Brine.Runtime.VmClass clazz = default!;

public VmTyped(global::DripSharp.Brine.Runtime.Truffle.api.frame.MaterializedFrame enclosingFrame, VmTyped? parent, global::DripSharp.Brine.Runtime.VmClass clazz, global::DripSharp.Brine.Runtime.GraalCollections.UnmodifiableEconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember> members) : base(enclosingFrame, parent!, members) {

this.clazz = clazz;
}

public VmTyped(global::DripSharp.Brine.Runtime.Truffle.api.frame.MaterializedFrame enclosingFrame, VmTyped? parent, global::DripSharp.Brine.Runtime.GraalCollections.UnmodifiableEconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember> members) : base(enclosingFrame, parent!, members) {

}

public void LateInitVmClass(global::DripSharp.Brine.Runtime.VmClass clazz) {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.clazz == default!), () => "VmTyped.clazz has already been initialized.");
this.clazz = clazz;
}

public void AddProperty(global::DripSharp.Brine.Ast.Member.ObjectMember property) {
global::DripSharp.Brine.Util.EconomicMaps.Put<object, global::DripSharp.Brine.Ast.Member.ObjectMember>((global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember>)(base.members!), property.GetName(), property);
}

public void AddProperties(global::DripSharp.Brine.Runtime.GraalCollections.UnmodifiableEconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember> properties) {
global::DripSharp.Brine.Util.EconomicMaps.PutAll<object, global::DripSharp.Brine.Ast.Member.ObjectMember>((global::DripSharp.Brine.Runtime.GraalCollections.EconomicMap<object, global::DripSharp.Brine.Ast.Member.ObjectMember>)(base.members!), properties);
}

public override global::DripSharp.Brine.Runtime.VmClass GetVmClass() {
global::DripSharp.Runtime.JavaCompat.Assert(() => (this.clazz != default!), () => "VmTyped.clazz was not initialized.");
return this.clazz;
}

public override global::DripSharp.Brine.Runtime.VmObjectLike GetParent() {
return (VmTyped)(base.parent!);
}

public override bool IsPrototype() {
return (this == this.GetPrototype());
}

public override bool IsModuleObject() {
return (base.extraStorage! is global::DripSharp.Brine.Runtime.ModuleInfo);
}

public global::DripSharp.Brine.Runtime.ModuleInfo GetModuleInfo() {
global::DripSharp.Runtime.JavaCompat.Assert(() => this.IsModuleObject());
return (global::DripSharp.Brine.Runtime.ModuleInfo)(this.GetExtraStorage()!);
}

public VmTyped GetModuleMirror() {
global::DripSharp.Runtime.JavaCompat.Assert(() => this.IsModuleObject());
return this.GetModuleInfo().GetMirror(this);
}

public global::DripSharp.Brine.Runtime.VmValue GetSupermoduleMirror() {
global::DripSharp.Runtime.JavaCompat.Assert(() => this.IsModuleObject());
var parent = ((VmTyped)(this.GetParent()))!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (parent! != default!));
return ((parent! == global::DripSharp.Brine.Runtime.BaseModule.GetModuleClass().GetPrototype()) ? (global::DripSharp.Brine.Runtime.VmValue)(global::DripSharp.Brine.Runtime.VmNull.WithoutDefault()) : (global::DripSharp.Brine.Runtime.VmValue)(parent!.GetModuleMirror()));
}

public global::DripSharp.Brine.Runtime.VmMap GetImports() {
global::DripSharp.Runtime.JavaCompat.Assert(() => this.IsModuleObject());
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var member in base.members.GetValues()) {
if (member.IsImport()) {
var memberNode = member.GetMemberNode()!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (memberNode! != default!));
var bodyNode = memberNode!.GetBodyNode();
if ((bodyNode is global::DripSharp.Brine.Runtime.Truffle.api.instrumentation.InstrumentableNode.WrapperNode wrapper)) {
bodyNode = (global::DripSharp.Brine.Ast.ExpressionNode)(wrapper.GetDelegateNode()!);
}
builder.Add(member.GetName().ToString(), global::DripSharp.Runtime.JavaCompat.UriToString(((global::DripSharp.Brine.Ast.Expression.Unary.ImportNode)(bodyNode!)).GetImportUri()));
}
}
return builder.Build();
}

public global::DripSharp.Brine.Runtime.VmMap GetClassMirrors() {
global::DripSharp.Runtime.JavaCompat.Assert(() => this.IsModuleObject());
if (this.GetModuleInfo().IsAmend()) {
return global::DripSharp.Brine.Runtime.VmMap.EMPTY;
}
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var member in base.members.GetValues()) {
if ((member.IsClass() && !(member.IsLocal()))) {
var className = member.GetName();
var clazz = (global::DripSharp.Brine.Runtime.VmClass)(this.GetCachedValue(className)!);
if ((clazz! == default!)) {
clazz = (global::DripSharp.Brine.Runtime.VmClass)(global::DripSharp.Brine.Runtime.VmUtils.DoReadMember(this, this, className, member)!);
}
builder.Add(className.ToString(), clazz!.GetMirror());
}
}
return builder.Build();
}

public global::DripSharp.Brine.Runtime.VmMap GetTypeAliasMirrors() {
global::DripSharp.Runtime.JavaCompat.Assert(() => this.IsModuleObject());
if (this.GetModuleInfo().IsAmend()) {
return global::DripSharp.Brine.Runtime.VmMap.EMPTY;
}
var builder = global::DripSharp.Brine.Runtime.VmMap.CreateBuilder();
foreach (var member in base.members.GetValues()) {
if ((member.IsTypeAlias() && !(member.IsLocal()))) {
var typeAliasName = member.GetName();
var typeAlias = (global::DripSharp.Brine.Runtime.VmTypeAlias)(this.GetCachedValue(typeAliasName)!);
if ((typeAlias! == default!)) {
typeAlias = (global::DripSharp.Brine.Runtime.VmTypeAlias)(global::DripSharp.Brine.Runtime.VmUtils.DoReadMember(this, this, typeAliasName, member)!);
}
builder.Add(typeAliasName.ToString(), typeAlias!.GetMirror());
}
}
return builder.Build();
}

public override object Export() {
if (!(this.IsModuleObject())) {
return new global::DripSharp.Brine.PObject(global::DripSharp.Brine.Runtime.PklRuntimeBridge.PClassInfoAsObject(this.clazz.GetPClassInfo()), global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<string, object>>(global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<string, object>>(this.ExportMembers())));
}
var moduleInfo = this.GetModuleInfo();
return new global::DripSharp.Brine.PModule(moduleInfo.GetModuleKey().GetUri(), moduleInfo.GetModuleName(), global::DripSharp.Brine.Runtime.PklRuntimeBridge.PClassInfoAsObject(this.clazz.GetPClassInfo()), global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<string, object>>(global::DripSharp.Runtime.JavaCompat.ToReadOnly<global::System.Collections.Generic.IReadOnlyDictionary<string, object>>(this.ExportMembers())));
}

public override void Accept(global::DripSharp.Brine.Runtime.VmValueVisitor visitor) {
visitor.VisitTyped(this);
}

public override T Accept<T>(global::DripSharp.Brine.Runtime.VmValueConverter<T> converter, global::System.Collections.Generic.IEnumerable<object> path) {
return converter.ConvertTyped(this, path);
}

public override bool Equals(object? obj) {
if ((this == obj!)) {
return true;
}
if (!((obj! is VmTyped other))) {
return false;
}
if ((this.clazz != other.clazz)) {
return false;
}
this.Force(false);
other.Force(false);
foreach (var key in this.clazz.GetAllRegularPropertyNames()) {
var value = this.GetCachedValue(key)!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (value! != default!));
var otherValue = other.GetCachedValue(key)!;
if (!(global::DripSharp.Runtime.JavaCompat.Equals(value!, otherValue!))) {
return false;
}
}
return true;
}

public override int GetHashCode() {
if ((base.cachedHash != 0)) {
return base.cachedHash;
}
this.Force(false);
var result = 0;
foreach (var key in this.clazz.GetAllRegularPropertyNames()) {
var value = this.GetCachedValue(key)!;
global::DripSharp.Runtime.JavaCompat.Assert(() => (value! != default!));
result = ((31 * result) + value!.GetHashCode());
}
base.cachedHash = result;
return result;
}
}
