// <auto-generated />
// Mechanically translated from: org/pkl/core/runtime/VmValue.java
// Upstream repository: https://github.com/apple/pkl.git
// Upstream revision: f7cac257ade5775c1dfc255f4fda2eacc296e9d0
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable enable
namespace DripSharp.Brine.Runtime;

internal abstract partial class VmValue
{
public override int GetHashCode() => base.GetHashCode();

public abstract global::DripSharp.Brine.Runtime.VmClass GetVmClass();

public virtual global::DripSharp.Brine.Runtime.VmTyped GetPrototype() {
return this.GetVmClass().GetPrototype();
}

public virtual bool IsPrototype() {
return false;
}

public virtual bool IsDynamic() {
return (this is global::DripSharp.Brine.Runtime.VmDynamic);
}

public virtual bool IsTyped() {
return (this is global::DripSharp.Brine.Runtime.VmTyped);
}

public virtual bool IsSequence() {
return false;
}

public abstract void Force(bool allowUndefinedValues);

public abstract object Export();

public abstract void Accept(global::DripSharp.Brine.Runtime.VmValueVisitor visitor);

public abstract T Accept<T>(global::DripSharp.Brine.Runtime.VmValueConverter<T> converter, global::System.Collections.Generic.IEnumerable<object> path);

public static void Force(object value, bool allowUndefinedValues) {
if ((value is VmValue vmValue)) {
vmValue.Force(allowUndefinedValues);
}
}

public static object Export(object value) {
if ((value is VmValue vmValue)) {
return vmValue.Export();
}
return value;
}

public static object? ExportNullable(object? value) {
if ((value! is VmValue vmValue)) {
return vmValue.Export();
}
return value!;
}

public abstract override bool Equals(object obj);
}
